"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Plus, Trash2, Users } from "lucide-react";
import { AuthGate, errorMessage, getAccessToken } from "../../../../components/auth-provider";
import Sidebar from "../../../../components/sidebar";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api/v1";
type Row=Record<string,any>;
async function api(path:string,init?:RequestInit){const response=await fetch(API+path,{...init,headers:{Authorization:`Bearer ${getAccessToken()??""}`,...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers}});const json=await response.json().catch(()=>null);if(!response.ok)throw new Error(json?.error?.message??"Request failed");return json}
function Content(){
 const [teams,setTeams]=useState<Row[]>([]),[options,setOptions]=useState<Row>({branches:[],departments:[],users:[]}),[error,setError]=useState(""),[notice,setNotice]=useState(""),[form,setForm]=useState({name:"",description:"",branchId:"",departmentId:"",members:[] as string[]}),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{try{const[t,o]=await Promise.all([api("/meeting-teams"),api("/meetings/options")]);setTeams(t.data??[]);setOptions(o.data??{});setError("")}catch(e){setError(errorMessage(e))}},[]);
 useEffect(()=>{void load()},[load]);
 const users=useMemo(()=>!form.branchId?(options.users??[]):(options.users??[]).filter((u:Row)=>u.teacherProfile?.branchId===form.branchId||u.employee?.branchId===form.branchId||(u.branchAssignments??[]).some((b:Row)=>b.branchId===form.branchId)),[options.users,form.branchId]);
 function toggle(id:string){setForm(v=>({...v,members:v.members.includes(id)?v.members.filter(x=>x!==id):[...v.members,id]}))}
 async function create(e:FormEvent){e.preventDefault();setSaving(true);try{await api("/meeting-teams",{method:"POST",body:JSON.stringify({name:form.name,description:form.description||null,branchId:form.branchId||null,departmentId:form.departmentId||null,memberUserIds:form.members})});setForm({name:"",description:"",branchId:"",departmentId:"",members:[]});setNotice("Meeting team created.");await load()}catch(e){setError(errorMessage(e))}finally{setSaving(false)}}
 async function remove(teamId:string,userId:string){try{await api(`/meeting-teams/${teamId}/members/${userId}`,{method:"DELETE"});setNotice("Team member removed.");await load()}catch(e){setError(errorMessage(e))}}
 return <div className="min-h-screen bg-slate-50 dark:bg-slate-950"><Sidebar/><main className="p-5 md:ml-64 md:p-10"><div className="mx-auto max-w-6xl"><Link href="/admin/meetings" className="text-sm font-bold text-brand-700">← Meetings</Link><div className="mt-2"><p className="text-xs font-black uppercase tracking-[.18em] text-brand-700">Reusable audiences</p><h1 className="mt-1 text-3xl font-black">Meeting Teams</h1><p className="mt-2 text-sm text-slate-500">Create cross-functional staff groups for committees, HOD coordination, interview panels and recurring meetings.</p></div>
 {error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
 <div className="mt-7 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><form onSubmit={create} className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><div className="flex items-center gap-2"><Plus size={18}/><h2 className="font-bold">Create team</h2></div><label className="mt-4 block text-sm font-semibold">Name<input required className="field" value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></label><label className="mt-3 block text-sm font-semibold">Description<textarea className="field min-h-20" value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/></label><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Branch<select className="field" value={form.branchId} onChange={e=>setForm(v=>({...v,branchId:e.target.value,members:[]}))}><option value="">Any branch</option>{(options.branches??[]).map((b:Row)=><option key={b.id} value={b.id}>{b.branchName}</option>)}</select></label><label className="text-sm font-semibold">Department<select className="field" value={form.departmentId} onChange={e=>setForm(v=>({...v,departmentId:e.target.value}))}><option value="">Any department</option>{(options.departments??[]).map((d:Row)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><fieldset className="mt-4"><legend className="text-sm font-bold">Members</legend><div className="mt-2 max-h-64 space-y-2 overflow-y-auto">{users.map((u:Row)=><label key={u.id} className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" checked={form.members.includes(u.id)} onChange={()=>toggle(u.id)}/><span>{u.name}<small className="block text-slate-500">{u.role} · {u.email}</small></span></label>)}</div></fieldset><button disabled={saving} className="mt-5 w-full rounded-xl bg-brand-700 p-3 font-bold text-white disabled:opacity-50">{saving?"Creating…":"Create meeting team"}</button></form>
 <section className="space-y-4">{teams.map(team=><article key={team.id} className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><Users size={17} className="text-brand-700"/><h2 className="font-bold">{team.name}</h2></div><p className="mt-1 text-sm text-slate-500">{team.description||"No description"} · {team.members?.length??0} members</p></div></div><div className="mt-4 space-y-2">{(team.members??[]).map((m:Row)=>{const user=(options.users??[]).find((u:Row)=>u.id===m.userId);return <div key={m.userId} className="flex items-center justify-between rounded-xl border p-3 text-sm"><span><b>{user?.name??m.userId}</b><small className="ml-2 text-slate-500">{user?.role??""}</small></span><button onClick={()=>void remove(team.id,m.userId)} className="p-1 text-red-600" title="Remove"><Trash2 size={15}/></button></div>})}{!team.members?.length&&<p className="text-sm text-slate-500">No members.</p>}</div></article>)}{!teams.length&&<div className="rounded-2xl border bg-white p-8 text-center text-sm text-slate-500 dark:bg-slate-900">No meeting teams yet.</div>}</section></div></div></main><style jsx global>{`.field{margin-top:.35rem;width:100%;border:1px solid #d7dee8;border-radius:.75rem;padding:.65rem .8rem;background:transparent}.dark .field{border-color:#334155}`}</style></div>
}
export default function Page(){return <AuthGate roles={["SUPER_ADMIN","BRANCH_ADMIN"]}><Content/></AuthGate>}
