import type { Metadata } from "next";
import { ExternalLink } from "lucide-react";
import { SiteHeader } from "../../components/site-header";
import { faculty } from "../../content/public-content";

export const metadata: Metadata = {
  title: "Faculty",
  description: "Meet Being Brilliant Academy faculty for CBSE, JEE, NEET and CUET preparation.",
  alternates: { canonical: "/faculty" },
  openGraph: { title: "Expert Faculty", description: "Learn from experienced educators for CBSE, JEE, NEET and CUET.", url: "/faculty" },
};

export default function FacultyPage() {
  const schema = { "@context": "https://schema.org", "@type": "ItemList", name: "Being Brilliant Academy Faculty", itemListElement: faculty.map((member, index) => ({ "@type": "ListItem", position: index + 1, item: { "@type": "Person", name: member.name, jobTitle: `${member.subject} Faculty`, description: member.bio, worksFor: { "@type": "EducationalOrganization", name: "Being Brilliant Academy" } } })) };
  return <><SiteHeader/><main id="main-content"><section className="hero-grid border-b border-blue-100 py-16 sm:py-24 dark:border-slate-800 dark:bg-none"><div className="container-page"><p className="pill inline-block">Meet your mentors</p><h1 className="section-title mt-5 max-w-3xl">Great teaching makes ambitious goals feel possible.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">Our faculty combine deep subject expertise, exam experience and individual feedback to help every learner progress with confidence.</p></div></section><section className="container-page py-16 sm:py-20" aria-labelledby="faculty-heading"><div className="max-w-2xl"><h2 id="faculty-heading" className="text-3xl font-black tracking-tight">Faculty directory</h2><p className="mt-3 text-slate-600 dark:text-slate-300">Specialists across board and competitive examination programmes.</p></div><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{faculty.map((member) => <article key={member.name} className="card overflow-hidden"><div className="flex items-center gap-4 bg-gradient-to-br from-blue-50 to-cyan-50 p-6 dark:from-blue-950 dark:to-slate-900"><div aria-hidden="true" className="grid size-16 shrink-0 place-items-center rounded-2xl bg-brand-700 text-xl font-black text-white shadow-glow">{member.initials}</div><div><p className="text-sm font-bold text-brand-700">{member.subject}</p><h3 className="mt-1 text-xl font-black">{member.name}</h3></div></div><div className="p-6"><dl className="grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">Qualification</dt><dd className="mt-1 font-semibold">{member.qualification}</dd></div><div><dt className="text-slate-500">Experience</dt><dd className="mt-1 font-semibold">{member.experience}</dd></div></dl><p className="mt-5 text-sm leading-6 text-slate-600 dark:text-slate-300">{member.bio}</p><div className="mt-5 flex flex-wrap gap-4">{member.socials.map((social) => <a key={social.label} href={social.href} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-sm font-bold text-brand-700" aria-label={`${member.name} on ${social.label} (opens in a new tab)`}>{social.label}<ExternalLink aria-hidden="true" size={14}/></a>)}</div></div></article>)}</div></section><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }}/></main></>;
}
