ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'LEAVE';
ALTER TABLE "Attendance" ADD COLUMN IF NOT EXISTS "checkIn" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "checkOut" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "teacherId" TEXT, ADD COLUMN IF NOT EXISTS "remarks" TEXT, ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
DO $$ BEGIN ALTER TABLE "Attendance" ADD CONSTRAINT "Attendance_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "TeacherProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS "Attendance_date_idx" ON "Attendance"("date");
CREATE INDEX IF NOT EXISTS "Attendance_teacherId_idx" ON "Attendance"("teacherId");
CREATE TABLE IF NOT EXISTS "TeacherAttendance" ("id" TEXT NOT NULL, "teacherId" TEXT NOT NULL, "date" DATE NOT NULL, "status" "AttendanceStatus" NOT NULL, "checkIn" TIMESTAMP(3), "checkOut" TIMESTAMP(3), "remarks" TEXT, "markedById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TeacherAttendance_pkey" PRIMARY KEY ("id"));
DO $$ BEGIN ALTER TABLE "TeacherAttendance" ADD CONSTRAINT "TeacherAttendance_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "TeacherProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE UNIQUE INDEX IF NOT EXISTS "TeacherAttendance_teacherId_date_key" ON "TeacherAttendance"("teacherId", "date");
CREATE INDEX IF NOT EXISTS "TeacherAttendance_date_idx" ON "TeacherAttendance"("date");
CREATE TABLE IF NOT EXISTS "Holiday" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "date" DATE NOT NULL, "branchId" TEXT, "remarks" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Holiday_pkey" PRIMARY KEY ("id"));
DO $$ BEGIN ALTER TABLE "Holiday" ADD CONSTRAINT "Holiday_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE UNIQUE INDEX IF NOT EXISTS "Holiday_date_branchId_key" ON "Holiday"("date", "branchId");
CREATE INDEX IF NOT EXISTS "Holiday_date_idx" ON "Holiday"("date");
