-- Baseline for the original application schema. The following migrations expand
-- these core tables; this makes the chain executable on an empty PostgreSQL DB.
-- Existing installations already contain this legacy schema, so the baseline is
-- deliberately a no-op there and can safely be recorded by migrate deploy.
DO $baseline$
BEGIN
IF to_regclass('public."User"') IS NOT NULL THEN
  RETURN;
END IF;

CREATE TYPE "Role" AS ENUM ('SUPER_ADMIN', 'BRANCH_ADMIN', 'TEACHER', 'STUDENT', 'PARENT');
CREATE TYPE "CourseType" AS ENUM ('LEGACY');
CREATE TYPE "EnrollmentStatus" AS ENUM ('ACTIVE', 'COMPLETED', 'CANCELLED');
CREATE TYPE "AttendanceStatus" AS ENUM ('PRESENT', 'ABSENT', 'LATE', 'EXCUSED');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'PAID', 'FAILED', 'REFUNDED');
CREATE TYPE "QuestionType" AS ENUM ('MCQ', 'MSQ', 'NUMERICAL', 'ASSERTION_REASON', 'PARAGRAPH', 'MATCHING', 'SUBJECTIVE');

CREATE TABLE "User" ("id" TEXT NOT NULL,"email" TEXT NOT NULL,"phone" TEXT,"passwordHash" TEXT NOT NULL,"name" TEXT NOT NULL,"role" "Role" NOT NULL DEFAULT 'STUDENT',"avatarUrl" TEXT,"emailVerifiedAt" TIMESTAMP(3),"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE UNIQUE INDEX "User_phone_key" ON "User"("phone");
CREATE TABLE "Session" ("id" TEXT NOT NULL,"tokenHash" TEXT NOT NULL,"userId" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Session_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash");
CREATE TABLE "PasswordResetToken" ("id" TEXT NOT NULL,"tokenHash" TEXT NOT NULL,"userId" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"usedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PasswordResetToken_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "PasswordResetToken_tokenHash_key" ON "PasswordResetToken"("tokenHash"); CREATE INDEX "PasswordResetToken_userId_expiresAt_idx" ON "PasswordResetToken"("userId","expiresAt");
CREATE TABLE "Branch" ("id" TEXT NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"address" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Branch_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "Branch_code_key" ON "Branch"("code");
CREATE TABLE "BranchUser" ("branchId" TEXT NOT NULL,"userId" TEXT NOT NULL,CONSTRAINT "BranchUser_pkey" PRIMARY KEY ("branchId","userId"));
CREATE TABLE "Category" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"slug" TEXT NOT NULL,CONSTRAINT "Category_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "Category_name_key" ON "Category"("name"); CREATE UNIQUE INDEX "Category_slug_key" ON "Category"("slug");
CREATE TABLE "Course" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"slug" TEXT NOT NULL,"description" TEXT NOT NULL,"type" "CourseType" NOT NULL DEFAULT 'LEGACY',"level" TEXT,"durationDays" INTEGER,"price" INTEGER NOT NULL,"salePrice" INTEGER,"thumbnailUrl" TEXT,"trailerUrl" TEXT,"language" TEXT NOT NULL DEFAULT 'English',"featured" BOOLEAN NOT NULL DEFAULT false,"published" BOOLEAN NOT NULL DEFAULT false,"categoryId" TEXT,"instructorId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Course_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "Course_slug_key" ON "Course"("slug");
CREATE TABLE "Module" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"position" INTEGER NOT NULL,"courseId" TEXT NOT NULL,CONSTRAINT "Module_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "Module_courseId_position_key" ON "Module"("courseId","position");
CREATE TABLE "Lesson" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"position" INTEGER NOT NULL,"type" TEXT NOT NULL,"videoUrl" TEXT,"content" TEXT,"durationSeconds" INTEGER NOT NULL DEFAULT 0,"preview" BOOLEAN NOT NULL DEFAULT false,"moduleId" TEXT NOT NULL,CONSTRAINT "Lesson_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "Lesson_moduleId_position_key" ON "Lesson"("moduleId","position");
CREATE TABLE "Enrollment" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"courseId" TEXT NOT NULL,"status" "EnrollmentStatus" NOT NULL DEFAULT 'ACTIVE',"progressPercent" INTEGER NOT NULL DEFAULT 0,"enrolledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3),CONSTRAINT "Enrollment_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "Enrollment_userId_courseId_key" ON "Enrollment"("userId","courseId");
CREATE TABLE "LessonProgress" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"lessonId" TEXT NOT NULL,"watchedSeconds" INTEGER NOT NULL DEFAULT 0,"completed" BOOLEAN NOT NULL DEFAULT false,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "LessonProgress_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "LessonProgress_userId_lessonId_key" ON "LessonProgress"("userId","lessonId");
CREATE TABLE "Batch" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"code" TEXT NOT NULL,"branchId" TEXT NOT NULL,"courseId" TEXT,"startsAt" TIMESTAMP(3) NOT NULL,"endsAt" TIMESTAMP(3),CONSTRAINT "Batch_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "Batch_code_key" ON "Batch"("code");
CREATE TABLE "StudentProfile" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"admissionNo" TEXT NOT NULL,"fatherName" TEXT NOT NULL,"className" TEXT NOT NULL,"branchId" TEXT NOT NULL,"batchId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "StudentProfile_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "StudentProfile_userId_key" ON "StudentProfile"("userId"); CREATE UNIQUE INDEX "StudentProfile_admissionNo_key" ON "StudentProfile"("admissionNo"); CREATE INDEX "StudentProfile_branchId_className_idx" ON "StudentProfile"("branchId","className"); CREATE INDEX "StudentProfile_batchId_idx" ON "StudentProfile"("batchId");
CREATE TABLE "Attendance" ("id" TEXT NOT NULL,"studentId" TEXT NOT NULL,"batchId" TEXT NOT NULL,"date" DATE NOT NULL,"status" "AttendanceStatus" NOT NULL,"markedById" TEXT,CONSTRAINT "Attendance_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "Attendance_studentId_batchId_date_key" ON "Attendance"("studentId","batchId","date");
CREATE TABLE "Assignment" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"instructions" TEXT NOT NULL,"dueAt" TIMESTAMP(3),"courseId" TEXT NOT NULL,CONSTRAINT "Assignment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AssignmentSubmission" ("id" TEXT NOT NULL,"assignmentId" TEXT NOT NULL,"studentId" TEXT NOT NULL,"fileUrl" TEXT,"text" TEXT,"marks" DECIMAL(5,2),"remarks" TEXT,"submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AssignmentSubmission_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "AssignmentSubmission_assignmentId_studentId_key" ON "AssignmentSubmission"("assignmentId","studentId");
CREATE TABLE "Exam" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"durationMinutes" INTEGER NOT NULL,"instructions" TEXT,"courseId" TEXT,CONSTRAINT "Exam_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Question" ("id" TEXT NOT NULL,"examId" TEXT NOT NULL,"body" TEXT NOT NULL,"type" "QuestionType" NOT NULL,"options" JSONB,"answer" JSONB,"marks" DECIMAL(5,2) NOT NULL,"negativeMarks" DECIMAL(5,2) NOT NULL DEFAULT 0,"explanation" TEXT,CONSTRAINT "Question_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ExamAttempt" ("id" TEXT NOT NULL,"examId" TEXT NOT NULL,"studentId" TEXT NOT NULL,"answers" JSONB,"score" DECIMAL(6,2),"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"submittedAt" TIMESTAMP(3),CONSTRAINT "ExamAttempt_pkey" PRIMARY KEY ("id")); CREATE INDEX "ExamAttempt_studentId_examId_idx" ON "ExamAttempt"("studentId","examId");
CREATE TABLE "Invoice" ("id" TEXT NOT NULL,"invoiceNo" TEXT NOT NULL,"userId" TEXT NOT NULL,"amount" INTEGER NOT NULL,"currency" TEXT NOT NULL DEFAULT 'INR',"status" "PaymentStatus" NOT NULL DEFAULT 'PENDING',"provider" TEXT,"providerOrderId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"paidAt" TIMESTAMP(3),CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "Invoice_invoiceNo_key" ON "Invoice"("invoiceNo"); CREATE UNIQUE INDEX "Invoice_providerOrderId_key" ON "Invoice"("providerOrderId");
CREATE TABLE "Payment" ("id" TEXT NOT NULL,"invoiceId" TEXT NOT NULL,"providerPaymentId" TEXT,"amount" INTEGER NOT NULL,"status" "PaymentStatus" NOT NULL DEFAULT 'PENDING',"raw" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Payment_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "Payment_providerPaymentId_key" ON "Payment"("providerPaymentId");
CREATE TABLE "Coupon" ("id" TEXT NOT NULL,"code" TEXT NOT NULL,"percentOff" INTEGER,"amountOff" INTEGER,"startsAt" TIMESTAMP(3) NOT NULL,"endsAt" TIMESTAMP(3) NOT NULL,"maxUses" INTEGER,"uses" INTEGER NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT true,CONSTRAINT "Coupon_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "Coupon_code_key" ON "Coupon"("code");
CREATE TABLE "Notification" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"title" TEXT NOT NULL,"body" TEXT NOT NULL,"readAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SupportTicket" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"subject" TEXT NOT NULL,"body" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'OPEN',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "SupportTicket_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL,"actorId" TEXT,"action" TEXT NOT NULL,"entity" TEXT NOT NULL,"entityId" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));

ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PasswordResetToken" ADD CONSTRAINT "PasswordResetToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BranchUser" ADD CONSTRAINT "BranchUser_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "BranchUser" ADD CONSTRAINT "BranchUser_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "Course" ADD CONSTRAINT "Course_instructorId_fkey" FOREIGN KEY ("instructorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Module" ADD CONSTRAINT "Module_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Lesson" ADD CONSTRAINT "Lesson_moduleId_fkey" FOREIGN KEY ("moduleId") REFERENCES "Module"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Enrollment" ADD CONSTRAINT "Enrollment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Enrollment" ADD CONSTRAINT "Enrollment_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LessonProgress" ADD CONSTRAINT "LessonProgress_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "LessonProgress" ADD CONSTRAINT "LessonProgress_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lesson"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Batch" ADD CONSTRAINT "Batch_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Batch" ADD CONSTRAINT "Batch_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "StudentProfile" ADD CONSTRAINT "StudentProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "StudentProfile" ADD CONSTRAINT "StudentProfile_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "StudentProfile" ADD CONSTRAINT "StudentProfile_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "Batch"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Attendance" ADD CONSTRAINT "Attendance_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Attendance" ADD CONSTRAINT "Attendance_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "Batch"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Attendance" ADD CONSTRAINT "Attendance_markedById_fkey" FOREIGN KEY ("markedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Assignment" ADD CONSTRAINT "Assignment_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "AssignmentSubmission" ADD CONSTRAINT "AssignmentSubmission_assignmentId_fkey" FOREIGN KEY ("assignmentId") REFERENCES "Assignment"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "AssignmentSubmission" ADD CONSTRAINT "AssignmentSubmission_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Question" ADD CONSTRAINT "Question_examId_fkey" FOREIGN KEY ("examId") REFERENCES "Exam"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ExamAttempt" ADD CONSTRAINT "ExamAttempt_examId_fkey" FOREIGN KEY ("examId") REFERENCES "Exam"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "ExamAttempt" ADD CONSTRAINT "ExamAttempt_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Payment" ADD CONSTRAINT "Payment_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
END
$baseline$;
