DO $$ BEGIN
  CREATE TYPE "BatchStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'ARCHIVED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE "Batch"
  ADD COLUMN IF NOT EXISTS "academicSession" TEXT NOT NULL DEFAULT '2026-27',
  ADD COLUMN IF NOT EXISTS "capacity" INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS "timing" TEXT NOT NULL DEFAULT '09:00-10:00',
  ADD COLUMN IF NOT EXISTS "days" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "classroom" TEXT,
  ADD COLUMN IF NOT EXISTS "teacherId" TEXT,
  ADD COLUMN IF NOT EXISTS "feesPaise" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "status" "BatchStatus" NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS "remarks" TEXT,
  ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

DO $$ BEGIN
  ALTER TABLE "Batch" ADD CONSTRAINT "Batch_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "TeacherProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS "Batch_branchId_idx" ON "Batch"("branchId");
CREATE INDEX IF NOT EXISTS "Batch_courseId_idx" ON "Batch"("courseId");
CREATE INDEX IF NOT EXISTS "Batch_teacherId_idx" ON "Batch"("teacherId");
CREATE INDEX IF NOT EXISTS "Batch_status_idx" ON "Batch"("status");
