"use client";

import { FormEvent, useEffect, useState } from "react";
import { Save, School } from "lucide-react";
import { ProtectedAdminWorkspace } from "../../../components/admin-workspace";
import { errorMessage, getAccessToken } from "../../../components/auth-provider";
import ImageUploadField, { fileAsBase64 } from "../../../components/image-upload-field";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api/v1";
const headers = () => ({ "Content-Type": "application/json", Authorization: `Bearer ${getAccessToken()}` });
async function settingsApi(init?: RequestInit) { const response = await fetch(`${API}/organization/settings`, { ...init, headers: headers() }); const json = await response.json(); if (!response.ok) throw new Error(json?.error?.message ?? "Unable to save settings"); return json.data; }
async function uploadLogo(file: File) { const response = await fetch(`${API}/admin/image-uploads`, { method: "POST", headers: headers(), body: JSON.stringify({ kind: "organization-logo", fileName: file.name, mimeType: file.type, base64: await fileAsBase64(file) }) }); const json = await response.json().catch(() => null); if (!response.ok) throw new Error(json?.error?.message ?? "Unable to upload school logo"); return String(json.data.url); }
async function discardUpload(url: string) { await fetch(`${API}/admin/image-uploads`, { method: "DELETE", headers: headers(), body: JSON.stringify({ url }) }); }

export default function Page() {
  const [form, setForm] = useState<any>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [logoFile, setLogoFile] = useState<File | null>(null); const [logoError, setLogoError] = useState("");
  useEffect(() => { void settingsApi().then(setForm).catch(cause => setError(errorMessage(cause))); }, []);
  async function save(event: FormEvent) { event.preventDefault(); if (logoError) return; if (form.groupLabelType === "CUSTOM" && !form.customGroupLabel?.trim()) { setError("Enter the custom academic group label."); return; } setSaving(true); setMessage(""); setError(""); let uploadedUrl: string | null = null; try { if (logoFile) uploadedUrl = await uploadLogo(logoFile); const updated = await settingsApi({ method: "PATCH", body: JSON.stringify({ name: form.name, legalName: form.legalName, phone: form.phone, logoUrl: uploadedUrl ?? (form.logoUrl || null), primaryColor: form.primaryColor, secondaryColor: form.secondaryColor, timezone: form.timezone, locale: form.locale, currency: form.currency, academicYearStartMonth: Number(form.academicYearStartMonth), groupLabelType: form.groupLabelType, customGroupLabel: form.groupLabelType === "CUSTOM" ? form.customGroupLabel : null, settings: form.settings }) }); setForm(updated); setLogoFile(null); setMessage("Settings saved"); } catch (cause) { if (uploadedUrl) await discardUpload(uploadedUrl).catch(() => undefined); setError(errorMessage(cause)); } finally { setSaving(false); } }
  if (!form) return <ProtectedAdminWorkspace title="School Settings" description="Loading tenant configuration."><p className="mt-6">{error || "Loading…"}</p></ProtectedAdminWorkspace>;
  return <ProtectedAdminWorkspace title="School Branding & Settings" description="Tenant-specific identity, localization and academic configuration."><form onSubmit={save} className="card mt-6 grid max-w-3xl gap-4 p-6 md:grid-cols-2">{[["name", "School name"], ["legalName", "Legal name"], ["phone", "Phone"], ["timezone", "Timezone"], ["locale", "Locale"], ["currency", "Currency"], ["academicYearStartMonth", "Academic year start month"]].map(([key, label]) => <label className="text-sm font-semibold" key={key}>{label}<input className="mt-1 block w-full rounded-lg border p-2.5 dark:bg-slate-900" value={form[key] ?? ""} onChange={event => setForm({ ...form, [key]: event.target.value })} /></label>)}<label className="text-sm font-semibold">Academic group terminology<select className="mt-1 block w-full rounded-lg border p-2.5 dark:bg-slate-900" value={form.groupLabelType ?? "BATCH"} onChange={event => setForm({ ...form, groupLabelType: event.target.value })}><option value="SECTION">Section (school)</option><option value="BATCH">Batch (coaching / tuition)</option><option value="GROUP">Group</option><option value="CUSTOM">Custom label</option></select></label>{form.groupLabelType === "CUSTOM" && <label className="text-sm font-semibold">Custom group label<input required minLength={2} maxLength={40} className="mt-1 block w-full rounded-lg border p-2.5 dark:bg-slate-900" value={form.customGroupLabel ?? ""} onChange={event => setForm({ ...form, customGroupLabel: event.target.value })} placeholder="e.g. Learning Group"/></label>}<ImageUploadField label="School Logo" currentUrl={form.logoUrl || null} selectedFile={logoFile} disabled={saving} onFileChange={setLogoFile} onRemove={() => setForm({ ...form, logoUrl: null })} onError={setLogoError} error={logoError} />{[["primaryColor", "Primary color"], ["secondaryColor", "Secondary color"]].map(([key, label]) => <label className="text-sm font-semibold" key={key}>{label}<span className="mt-1 flex gap-2"><input type="color" value={form[key]} onChange={event => setForm({ ...form, [key]: event.target.value })} /><input className="flex-1 rounded-lg border p-2 dark:bg-slate-900" value={form[key]} onChange={event => setForm({ ...form, [key]: event.target.value })} /></span></label>)}<div className="rounded-xl p-5 text-white md:col-span-2" style={{ background: `linear-gradient(135deg,${form.primaryColor},${form.secondaryColor})` }}><School /><b className="mt-3 block text-xl">{form.name}</b><span>Brand preview</span></div>{message && <p className="text-sm text-emerald-700 md:col-span-2">{message}</p>}{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700 md:col-span-2">{error}</p>}<button disabled={saving || Boolean(logoError)} className="flex items-center justify-center gap-2 rounded-lg bg-brand-700 p-3 font-semibold text-white disabled:opacity-50 md:col-span-2"><Save size={17} />{saving ? "Saving…" : "Save settings"}</button></form></ProtectedAdminWorkspace>;
}
