"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CalendarClock, CheckCircle2, ListTodo, Plus, RefreshCw, Users, Video, X } from "lucide-react";
import { AuthGate, errorMessage, getAccessToken } from "../../../components/auth-provider";
import Sidebar from "../../../components/sidebar";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api/v1";
type Row = Record<string, any>;
type Options = { branches: Row[]; departments: Row[]; users: Row[]; teams: Row[] };

async function api(path:string,init?:RequestInit){
  const response=await fetch(API+path,{...init,headers:{Authorization:`Bearer ${getAccessToken()??""}`,...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers}});
  const json=await response.json().catch(()=>null);
  if(!response.ok) throw new Error(json?.error?.message??"Request failed");
  return json;
}
const dt=(value:Date)=>{const p=(n:number)=>String(n).padStart(2,"0");return `${value.getFullYear()}-${p(value.getMonth()+1)}-${p(value.getDate())}T${p(value.getHours())}:${p(value.getMinutes())}`;};
const blank=()=>{const start=new Date(Date.now()+60*60_000);start.setMinutes(Math.ceil(start.getMinutes()/15)*15,0,0);const end=new Date(start.getTime()+60*60_000);return {
  title:"",description:"",type:"STAFF",branchId:"",departmentId:"",startsAt:dt(start),endsAt:dt(end),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"Asia/Kolkata",
  hostUserId:"",coHostUserIds:[] as string[],audienceType:"INDIVIDUAL",teamId:"",audienceDepartmentId:"",selectedUsers:[] as string[],recording:false,recurring:false,recurrenceRule:"FREQ=WEEKLY;COUNT=4",
  joinBeforeMinutes:10,lockAfterStart:false,allowChat:true,allowWhiteboard:true,allowAnnotation:true,allowScreenShare:true,allowParticipantMic:true,allowParticipantCamera:true,
};};

function Content(){
  const [meetings,setMeetings]=useState<Row[]>([]),[actions,setActions]=useState<Row[]>([]),[options,setOptions]=useState<Options>({branches:[],departments:[],users:[],teams:[]});
  const [loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[show,setShow]=useState(false),[form,setForm]=useState(blank()),[saving,setSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const [m,a,o]=await Promise.all([api("/meetings"),api("/meeting-actions"),api("/meetings/options")]);setMeetings(m.data??[]);setActions(a.data??[]);setOptions(o.data??{branches:[],departments:[],users:[],teams:[]});setError("");}catch(e){setError(errorMessage(e))}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const now=Date.now(),upcoming=meetings.filter(x=>["OPEN_FOR_JOIN","LIVE"].includes(x.status)||(x.status==="SCHEDULED"&&new Date(x.endsAt).getTime()>=now)),past=meetings.filter(x=>!upcoming.includes(x));
  const overdue=actions.filter(x=>x.overdue),today=upcoming.filter(x=>new Date(x.startsAt).toDateString()===new Date().toDateString());
  const staff=useMemo(()=>options.users.filter(x=>["SUPER_ADMIN","BRANCH_ADMIN","ACCOUNTANT","TEACHER","EMPLOYEE"].includes(x.role)),[options.users]);
  const branchUsers=useMemo(()=>!form.branchId?staff:staff.filter(x=>x.teacherProfile?.branchId===form.branchId||x.employee?.branchId===form.branchId||(x.branchAssignments??[]).some((b:Row)=>b.branchId===form.branchId)),[staff,form.branchId]);
  function toggleUser(id:string){setForm(v=>({...v,selectedUsers:v.selectedUsers.includes(id)?v.selectedUsers.filter(x=>x!==id):[...v.selectedUsers,id]}))}
  function toggleCoHost(id:string){setForm(v=>({...v,coHostUserIds:v.coHostUserIds.includes(id)?v.coHostUserIds.filter(x=>x!==id):[...v.coHostUserIds,id]}))}
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");setNotice("");try{
    const audiences:Row[]=[];
    if(form.audienceType==="BRANCH"&&form.branchId)audiences.push({type:"BRANCH",branchId:form.branchId});
    if(form.audienceType==="DEPARTMENT"&&form.audienceDepartmentId)audiences.push({type:"DEPARTMENT",departmentId:form.audienceDepartmentId});
    if(form.audienceType==="TEAM"&&form.teamId)audiences.push({type:"TEAM",teamId:form.teamId});
    const participantIds=[...new Set([...form.selectedUsers,...form.coHostUserIds])].filter(id=>id!==form.hostUserId);
    const participants=participantIds.map(userId=>({userId,meetingRole:form.coHostUserIds.includes(userId)?"CO_HOST":"PARTICIPANT"}));
    const body={title:form.title,description:form.description||null,type:form.type,branchId:form.branchId||null,departmentId:form.departmentId||null,startsAt:new Date(form.startsAt).toISOString(),endsAt:new Date(form.endsAt).toISOString(),timezone:form.timezone,hostUserId:form.hostUserId,participants,audiences,agenda:[],allowRecording:form.recording,recordingRequired:false,allowChat:form.allowChat,allowWhiteboard:form.allowWhiteboard,allowAnnotation:form.allowAnnotation,allowScreenShare:form.allowScreenShare,allowParticipantMic:form.allowParticipantMic,allowParticipantCamera:form.allowParticipantCamera,joinBeforeMinutes:form.joinBeforeMinutes,lockAfterStart:form.lockAfterStart,visibility:"INVITE_ONLY"};
    await api(form.recurring?"/meeting-series":"/meetings",{method:"POST",body:JSON.stringify(form.recurring?{...body,recurrenceRule:form.recurrenceRule,maxOccurrences:52}:body)});
    setNotice(form.recurring?"Recurring meeting series scheduled.":"Meeting scheduled.");setShow(false);setForm(blank());await load();
  }catch(e){setError(errorMessage(e))}finally{setSaving(false)}}
  return <div className="min-h-screen bg-slate-50 dark:bg-slate-950"><Sidebar/><main className="p-5 md:ml-64 md:p-10"><div className="mx-auto max-w-7xl">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-brand-700">Enterprise collaboration</p><h1 className="mt-1 text-3xl font-black">Staff & Management Meetings</h1><p className="mt-2 text-sm text-slate-500">Schedule, conduct, document and track staff decisions independently of student Live Classes.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/meetings/teams" className="rounded-xl border bg-white px-4 py-3 text-sm font-bold dark:bg-slate-900">Meeting teams</Link><Link href="/meetings" className="rounded-xl border bg-white px-4 py-3 text-sm font-bold dark:bg-slate-900">My meeting view</Link><button onClick={()=>{const f=blank();f.hostUserId=staff[0]?.id??"";setForm(f);setShow(true)}} className="inline-flex items-center gap-2 rounded-xl bg-brand-700 px-4 py-3 text-sm font-bold text-white"><Plus size={17}/>Schedule meeting</button></div></header>
    {error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
    <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Today",today.length,CalendarClock],["Upcoming",upcoming.length,Video],["Open actions",actions.filter(x=>!["COMPLETED","CANCELLED"].includes(x.status)).length,ListTodo],["Overdue",overdue.length,RefreshCw]].map(([label,value,Icon]:any)=><article key={label} className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><Icon size={20} className="text-brand-700"/><p className="mt-3 text-3xl font-black">{value}</p><p className="text-sm text-slate-500">{label}</p></article>)}</section>
    <section className="mt-7 rounded-2xl border bg-white dark:bg-slate-900"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">Upcoming meetings</h2><p className="text-xs text-slate-500">Organization, branch, department and team meetings</p></div><button onClick={()=>void load()} className="rounded-lg border p-2" aria-label="Refresh"><RefreshCw size={16}/></button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-950"><tr><th className="p-4">Meeting</th><th className="p-4">Date / timezone</th><th className="p-4">Scope</th><th className="p-4">Participants</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody className="divide-y">{loading?<tr><td colSpan={6} className="p-10 text-center">Loading meetings…</td></tr>:upcoming.length?upcoming.map(m=><tr key={m.id}><td className="p-4"><b>{m.title}</b><br/><span className="text-xs text-slate-500">{m.type.replaceAll("_"," ")}</span></td><td className="p-4">{new Date(m.startsAt).toLocaleString("en-IN")}<br/><span className="text-xs text-slate-500">{m.timezone}</span></td><td className="p-4">{m.branchId?"Branch scoped":m.departmentId?"Department scoped":"Organization"}</td><td className="p-4">{m.participants?.length??0}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold dark:bg-slate-800">{m.status.replaceAll("_"," ")}</span></td><td className="p-4"><Link href={`/meetings/${m.id}`} className="font-bold text-brand-700">Open</Link></td></tr>):<tr><td colSpan={6} className="p-10 text-center text-slate-500">No upcoming meetings.</td></tr>}</tbody></table></div></section>
    <section className="mt-7 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><h2 className="font-bold">Action-item control</h2><div className="mt-4 space-y-3">{actions.slice(0,8).map(a=><div key={a.id} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><b className="text-sm">{a.title}</b><span className={`text-xs font-bold ${a.overdue?"text-red-600":"text-slate-500"}`}>{a.overdue?"OVERDUE":a.status}</span></div><p className="mt-1 text-xs text-slate-500">{a.meeting?.title}{a.dueAt?` · Due ${new Date(a.dueAt).toLocaleString("en-IN")}`:""}</p></div>)}{!actions.length&&<p className="text-sm text-slate-500">No action items yet.</p>}</div></article><article className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><h2 className="font-bold">Recent completed / past meetings</h2><div className="mt-4 space-y-3">{past.slice(-8).reverse().map(m=><Link key={m.id} href={`/meetings/${m.id}`} className="block rounded-xl border p-3"><b className="text-sm">{m.title}</b><p className="mt-1 text-xs text-slate-500">{new Date(m.startsAt).toLocaleString("en-IN")} · {m.status.replaceAll("_"," ")}</p></Link>)}{!past.length&&<p className="text-sm text-slate-500">No past meetings yet.</p>}</div></article></section>
  </div></main>
  {show&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/55 p-4"><form onSubmit={submit} className="mx-auto my-6 max-w-4xl rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Schedule staff meeting</h2><p className="text-sm text-slate-500">Participants are snapshotted when the meeting is scheduled.</p></div><button type="button" onClick={()=>setShow(false)}><X/></button></div><div className="mt-6 grid gap-4 md:grid-cols-2">
    <Field label="Meeting title"><input required className="field" value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></Field>
    <Field label="Meeting type"><select className="field" value={form.type} onChange={e=>setForm(v=>({...v,type:e.target.value}))}>{["MANAGEMENT","STAFF","DEPARTMENT","HOD","TEACHER_COORDINATION","TRAINING","INTERVIEW","COMMITTEE","GENERAL","CUSTOM"].map(x=><option key={x}>{x}</option>)}</select></Field>
    <div className="md:col-span-2"><Field label="Description (optional)"><textarea className="field min-h-20" value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/></Field></div>
    <Field label="Branch"><select className="field" value={form.branchId} onChange={e=>setForm(v=>({...v,branchId:e.target.value,selectedUsers:[],coHostUserIds:[]}))}><option value="">Organization-wide</option>{options.branches.map(x=><option key={x.id} value={x.id}>{x.branchName}</option>)}</select></Field>
    <Field label="Meeting department (optional)"><select className="field" value={form.departmentId} onChange={e=>setForm(v=>({...v,departmentId:e.target.value}))}><option value="">None</option>{options.departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>
    <Field label="Start"><input required type="datetime-local" className="field" value={form.startsAt} onChange={e=>setForm(v=>({...v,startsAt:e.target.value}))}/></Field>
    <Field label="End"><input required type="datetime-local" className="field" value={form.endsAt} onChange={e=>setForm(v=>({...v,endsAt:e.target.value}))}/></Field>
    <Field label="Timezone"><input required className="field" value={form.timezone} onChange={e=>setForm(v=>({...v,timezone:e.target.value}))}/></Field>
    <Field label="Host"><select required className="field" value={form.hostUserId} onChange={e=>setForm(v=>({...v,hostUserId:e.target.value,coHostUserIds:v.coHostUserIds.filter(id=>id!==e.target.value)}))}><option value="">Select host</option>{branchUsers.map(x=><option key={x.id} value={x.id}>{x.name} · {x.role}</option>)}</select></Field>
    <Field label="Audience"><select className="field" value={form.audienceType} onChange={e=>setForm(v=>({...v,audienceType:e.target.value}))}><option value="INDIVIDUAL">Selected individuals</option><option value="BRANCH">Whole branch</option><option value="DEPARTMENT">Department employees</option><option value="TEAM">Meeting team</option></select></Field>
    {form.audienceType==="DEPARTMENT"&&<Field label="Target department"><select required className="field" value={form.audienceDepartmentId} onChange={e=>setForm(v=>({...v,audienceDepartmentId:e.target.value}))}><option value="">Select department</option>{options.departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>}
    {form.audienceType==="TEAM"&&<Field label="Target team"><select required className="field" value={form.teamId} onChange={e=>setForm(v=>({...v,teamId:e.target.value}))}><option value="">Select team</option>{options.teams.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>}
    <Field label="Join window"><select className="field" value={form.joinBeforeMinutes} onChange={e=>setForm(v=>({...v,joinBeforeMinutes:Number(e.target.value)}))}>{[0,5,10,15,30,60].map(x=><option key={x} value={x}>{x===0?"At start time":`${x} min before`}</option>)}</select></Field>
    <label className="flex items-center gap-2 rounded-xl border p-3 text-sm font-semibold"><input type="checkbox" checked={form.lockAfterStart} onChange={e=>setForm(v=>({...v,lockAfterStart:e.target.checked}))}/>Block late joining after start</label>
    <label className="flex items-center gap-2 rounded-xl border p-3 text-sm font-semibold"><input type="checkbox" checked={form.recording} onChange={e=>setForm(v=>({...v,recording:e.target.checked}))}/>Allow cloud recording</label>
    <label className="flex items-center gap-2 rounded-xl border p-3 text-sm font-semibold"><input type="checkbox" checked={form.recurring} onChange={e=>setForm(v=>({...v,recurring:e.target.checked}))}/>Recurring meeting</label>
    {form.recurring&&<Field label="Recurrence rule"><input className="field font-mono text-xs" value={form.recurrenceRule} onChange={e=>setForm(v=>({...v,recurrenceRule:e.target.value}))}/></Field>}
  </div>
  <fieldset className="mt-5"><legend className="text-sm font-bold">Co-hosts (optional)</legend><p className="mt-1 text-xs text-slate-500">Co-hosts receive moderation permissions and are invited even when the audience is a branch, department or team.</p><div className="mt-2 grid max-h-44 gap-2 overflow-y-auto sm:grid-cols-2 lg:grid-cols-3">{branchUsers.filter(x=>x.id!==form.hostUserId).map(x=><label key={x.id} className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" checked={form.coHostUserIds.includes(x.id)} onChange={()=>toggleCoHost(x.id)}/><span>{x.name}<small className="block text-slate-500">{x.role}</small></span></label>)}</div></fieldset>
  <fieldset className="mt-5"><legend className="text-sm font-bold">Room capabilities</legend><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{[["allowChat","Chat"],["allowWhiteboard","Whiteboard"],["allowAnnotation","Annotation"],["allowScreenShare","Screen sharing"],["allowParticipantMic","Participant microphone"],["allowParticipantCamera","Participant camera"]].map(([key,label])=><label key={key} className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" checked={Boolean((form as any)[key])} onChange={e=>setForm(v=>({...v,[key]:e.target.checked}))}/>{label}</label>)}</div></fieldset>
  {form.audienceType==="INDIVIDUAL"&&<fieldset className="mt-5"><legend className="text-sm font-bold">Participants</legend><div className="mt-2 grid max-h-56 gap-2 overflow-y-auto sm:grid-cols-2 lg:grid-cols-3">{branchUsers.map(x=><label key={x.id} className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" checked={form.selectedUsers.includes(x.id)} onChange={()=>toggleUser(x.id)}/><span>{x.name}<small className="block text-slate-500">{x.role}</small></span></label>)}</div></fieldset>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setShow(false)} className="rounded-xl border px-4 py-3 font-bold">Cancel</button><button disabled={saving} className="rounded-xl bg-brand-700 px-5 py-3 font-bold text-white disabled:opacity-50">{saving?"Scheduling…":"Schedule meeting"}</button></div></form></div>}
  <style jsx global>{`.field{margin-top:.35rem;width:100%;min-height:44px;border:1px solid #d7dee8;border-radius:.75rem;padding:.65rem .8rem;background:transparent}.dark .field{border-color:#334155}`}</style></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm font-semibold">{label}{children}</label>}
export default function Page(){return <AuthGate roles={["SUPER_ADMIN","BRANCH_ADMIN"]}><Content/></AuthGate>}
