"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, ClipboardList, FileText, Play, RefreshCw, Users, Video } from "lucide-react";
import { AuthGate, errorMessage, getAccessToken, useAuth } from "../../../components/auth-provider";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api/v1";
type Row=Record<string,any>;
async function api(path:string,init?:RequestInit){const response=await fetch(API+path,{...init,headers:{Authorization:`Bearer ${getAccessToken()??""}`,...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers}});const json=await response.json().catch(()=>null);if(!response.ok)throw new Error(json?.error?.message??"Request failed");return json}
function Content(){
 const params=useParams<{id:string}>(),id=String(params?.id??"");const {user}=useAuth();const [meeting,setMeeting]=useState<Row|null>(null),[attendance,setAttendance]=useState<Row|null>(null),[audit,setAudit]=useState<Row[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[tab,setTab]=useState("overview");
 const [minutes,setMinutes]=useState({summary:"",notes:""}),[decision,setDecision]=useState(""),[action,setAction]=useState({title:"",assigneeUserId:"",dueAt:""}),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const m=(await api(`/meetings/${id}`)).data;setMeeting(m);setMinutes({summary:m.minutes?.summary??"",notes:m.minutes?.notes??""});const[aud,att]=await Promise.allSettled([api(`/meetings/${id}/audit`),api(`/meetings/${id}/attendance`)]);if(aud.status==="fulfilled")setAudit(aud.value.data??[]);if(att.status==="fulfilled")setAttendance(att.value.data??null);setError("")}catch(e){setError(errorMessage(e))}},[id]);
 useEffect(()=>{if(id)void load()},[id,load]);
 const self=meeting?.participants?.find((p:Row)=>p.userId===user?.id);const manager=Boolean(user?.role==="SUPER_ADMIN"||user?.role==="BRANCH_ADMIN"||self?.meetingRole==="HOST"||self?.meetingRole==="CO_HOST");
 const canJoin=meeting&&!["CANCELLED","ENDED","CLOSED"].includes(meeting.status);
 const users=useMemo(()=>meeting?.participants??[],[meeting]);
 async function respond(response:string){try{await api(`/meetings/${id}/respond`,{method:"POST",body:JSON.stringify({response})});setNotice(`Response updated: ${response}`);await load()}catch(e){setError(errorMessage(e))}}
 async function saveMinutes(e:FormEvent){e.preventDefault();setBusy(true);try{await api(`/meetings/${id}/minutes`,{method:"PUT",body:JSON.stringify(minutes)});setNotice("Minutes saved.");await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function addDecision(e:FormEvent){e.preventDefault();if(!decision.trim())return;setBusy(true);try{await api(`/meetings/${id}/decisions`,{method:"POST",body:JSON.stringify({decision})});setDecision("");setNotice("Decision recorded.");await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function addAction(e:FormEvent){e.preventDefault();setBusy(true);try{await api(`/meetings/${id}/actions`,{method:"POST",body:JSON.stringify({title:action.title,assigneeUserId:action.assigneeUserId,dueAt:action.dueAt?new Date(action.dueAt).toISOString():null})});setAction({title:"",assigneeUserId:"",dueAt:""});setNotice("Action item assigned.");await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function completeAction(actionId:string){try{await api(`/meeting-actions/${actionId}/complete`,{method:"POST",body:JSON.stringify({completionNote:"Completed from meeting workspace"})});setNotice("Action completed.");await load()}catch(e){setError(errorMessage(e))}}
 async function minuteAction(name:"submit"|"approve"|"publish"){try{await api(`/meetings/${id}/minutes/${name}`,{method:"POST",body:"{}"});setNotice(`Minutes ${name}ed.`);await load()}catch(e){setError(errorMessage(e))}}
 if(!meeting)return <main className="grid min-h-screen place-items-center bg-slate-50 dark:bg-slate-950"><div>{error||"Loading meeting…"}</div></main>;
 return <main className="min-h-screen bg-slate-50 p-4 dark:bg-slate-950 md:p-8"><div className="mx-auto max-w-6xl"><header className="rounded-3xl bg-slate-950 p-6 text-white"><Link href="/meetings" className="text-xs font-bold text-blue-300">← My Meetings</Link><div className="mt-3 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-300">{meeting.type.replaceAll("_"," ")}</p><h1 className="mt-1 text-3xl font-black">{meeting.title}</h1><p className="mt-2 text-sm text-slate-300">{new Date(meeting.startsAt).toLocaleString("en-IN")} – {new Date(meeting.endsAt).toLocaleTimeString("en-IN")} · {meeting.timezone}</p><p className="mt-1 text-xs text-slate-400">Your role: {self?.meetingRole?.replaceAll("_"," ")??user?.role} · Status: {meeting.status.replaceAll("_"," ")}</p></div><div className="flex flex-wrap gap-2">{self&&<><button onClick={()=>void respond("ACCEPTED")} className="rounded-xl border border-white/20 px-3 py-2 text-sm font-bold">Accept</button><button onClick={()=>void respond("DECLINED")} className="rounded-xl border border-white/20 px-3 py-2 text-sm font-bold">Decline</button></>}{canJoin&&<Link href={`/meeting/${encodeURIComponent(meeting.livekitRoomName)}`} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold"><Video size={17}/>Join Meeting</Link>}<button onClick={()=>void load()} className="rounded-xl border border-white/20 p-2"><RefreshCw size={17}/></button></div></div></header>
 {error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
 <nav className="mt-5 flex gap-2 overflow-x-auto">{["overview","participants","agenda","attendance","minutes","decisions","actions","recordings",...(manager?["audit"]:[])].map(x=><button key={x} onClick={()=>setTab(x)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-bold ${tab===x?"bg-brand-700 text-white":"border bg-white dark:bg-slate-900"}`}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav>
 <section className="mt-5 rounded-2xl border bg-white p-5 dark:bg-slate-900">
 {tab==="overview"&&<div className="grid gap-4 md:grid-cols-3"><Card icon={<Play/>} title="Meeting"><p className="text-sm">{meeting.description||"No description provided."}</p><p className="mt-3 text-xs text-slate-500">Room: Native LiveKit · {meeting.allowRecording?"Recording allowed":"Recording disabled"}</p></Card><Card icon={<Users/>} title="Participants"><p className="text-3xl font-black">{meeting.participants?.length??0}</p><p className="text-sm text-slate-500">Host, co-hosts and staff</p></Card><Card icon={<ClipboardList/>} title="Actions"><p className="text-3xl font-black">{meeting.actionItems?.filter((a:Row)=>!["COMPLETED","CANCELLED"].includes(a.status)).length??0}</p><p className="text-sm text-slate-500">Open action items</p></Card></div>}
 {tab==="participants"&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{users.map((p:Row)=><div key={p.id} className="rounded-xl border p-4"><b>{p.userId===user?.id?"You":p.userId}</b><p className="mt-1 text-xs text-slate-500">{p.meetingRole.replaceAll("_"," ")} · {p.responseStatus}</p></div>)}</div>}
 {tab==="agenda"&&<div className="space-y-3">{meeting.agendaItems?.map((a:Row)=><div key={a.id} className="rounded-xl border p-4"><b>{a.sequence}. {a.title}</b><p className="mt-1 text-sm text-slate-500">{a.description||"No notes"}{a.plannedMinutes?` · ${a.plannedMinutes} min`:""}</p></div>)}{!meeting.agendaItems?.length&&<p className="text-sm text-slate-500">No agenda items.</p>}</div>}
 {tab==="attendance"&&<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr className="text-left text-xs uppercase text-slate-500"><th className="p-3">Participant</th><th className="p-3">Status</th><th className="p-3">Joins</th><th className="p-3">Duration</th><th className="p-3">Attendance</th></tr></thead><tbody>{attendance?.participants?.map((a:Row)=><tr key={a.participantId} className="border-t"><td className="p-3">{a.user?.name??a.userId}</td><td className="p-3">{a.status}</td><td className="p-3">{a.joinCount}</td><td className="p-3">{Math.round(a.totalDurationSeconds/60)} min</td><td className="p-3">{a.attendancePercentage}%</td></tr>)}</tbody></table>{!attendance&&<p className="p-3 text-sm text-slate-500">Attendance is not available yet.</p>}</div>}
 {tab==="minutes"&&<div>{meeting.minutes?.status&&<p className="mb-3 text-xs font-bold text-brand-700">Status: {meeting.minutes.status.replaceAll("_"," ")}</p>}<form onSubmit={saveMinutes} className="space-y-3"><textarea disabled={!manager||meeting.minutes?.status==="PUBLISHED"} className="min-h-28 w-full rounded-xl border p-3" placeholder="Executive summary" value={minutes.summary} onChange={e=>setMinutes(v=>({...v,summary:e.target.value}))}/><textarea disabled={!manager||meeting.minutes?.status==="PUBLISHED"} className="min-h-48 w-full rounded-xl border p-3" placeholder="Detailed minutes" value={minutes.notes} onChange={e=>setMinutes(v=>({...v,notes:e.target.value}))}/>{manager&&<div className="flex flex-wrap gap-2"><button disabled={busy} className="rounded-xl bg-brand-700 px-4 py-2 font-bold text-white">Save minutes</button>{meeting.minutes&&meeting.minutes.status!=="PUBLISHED"&&<button type="button" onClick={()=>void minuteAction("submit")} className="rounded-xl border px-4 py-2 font-bold">Submit review</button>}{(user?.role==="SUPER_ADMIN"||user?.role==="BRANCH_ADMIN")&&meeting.minutes?.status==="UNDER_REVIEW"&&<button type="button" onClick={()=>void minuteAction("approve")} className="rounded-xl border px-4 py-2 font-bold">Approve</button>}{(user?.role==="SUPER_ADMIN"||user?.role==="BRANCH_ADMIN")&&meeting.minutes?.status==="APPROVED"&&<button type="button" onClick={()=>void minuteAction("publish")} className="rounded-xl border px-4 py-2 font-bold">Publish</button>}</div>}</form></div>}
 {tab==="decisions"&&<div className="space-y-3">{meeting.decisions?.map((d:Row)=><div key={d.id} className="rounded-xl border p-4"><b>{d.decision}</b>{d.rationale&&<p className="mt-1 text-sm text-slate-500">{d.rationale}</p>}</div>)}{manager&&<form onSubmit={addDecision} className="flex gap-2"><input className="flex-1 rounded-xl border p-3" placeholder="Record a decision" value={decision} onChange={e=>setDecision(e.target.value)}/><button className="rounded-xl bg-brand-700 px-4 font-bold text-white">Add</button></form>}</div>}
 {tab==="actions"&&<div className="space-y-3">{meeting.actionItems?.map((a:Row)=><div key={a.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><b>{a.title}</b><span className="text-xs font-bold">{a.status}</span></div><p className="mt-1 text-xs text-slate-500">{a.dueAt?`Due ${new Date(a.dueAt).toLocaleString("en-IN")}`:"No due date"}</p>{a.assigneeUserId===user?.id&&a.status!=="COMPLETED"&&<button onClick={()=>void completeAction(a.id)} className="mt-3 inline-flex items-center gap-1 rounded-lg border px-3 py-1.5 text-xs font-bold"><CheckCircle2 size={14}/>Mark complete</button>}</div>)}{manager&&<form onSubmit={addAction} className="grid gap-2 md:grid-cols-[1fr_240px_210px_auto]"><input required className="rounded-xl border p-3" placeholder="Action item" value={action.title} onChange={e=>setAction(v=>({...v,title:e.target.value}))}/><select required className="rounded-xl border p-3" value={action.assigneeUserId} onChange={e=>setAction(v=>({...v,assigneeUserId:e.target.value}))}><option value="">Assignee</option>{users.map((p:Row)=><option key={p.userId} value={p.userId}>{p.userId===user?.id?"You":p.userId}</option>)}</select><input type="datetime-local" className="rounded-xl border p-3" value={action.dueAt} onChange={e=>setAction(v=>({...v,dueAt:e.target.value}))}/><button className="rounded-xl bg-brand-700 px-4 font-bold text-white">Assign</button></form>}</div>}
 {tab==="recordings"&&<div className="space-y-3">{meeting.recordings?.map((r:Row)=><div key={r.id} className="flex items-center justify-between rounded-xl border p-4"><div><b>Meeting recording</b><p className="text-xs text-slate-500">{r.status} · {Math.round((r.durationSeconds??0)/60)} min</p></div>{r.storageKey&&<a href={`${API}/meetings/native/${encodeURIComponent(meeting.livekitRoomName)}/recordings/${r.id}`} className="text-sm font-bold text-brand-700">Available in room</a>}</div>)}{!meeting.recordings?.length&&<p className="text-sm text-slate-500">No recordings yet.</p>}</div>}
 {tab==="audit"&&manager&&<div className="space-y-2">{audit.map(a=><div key={a.id} className="rounded-xl border p-3 text-sm"><b>{a.action.replaceAll("_"," ")}</b><span className="ml-2 text-slate-500">{a.actor?.name??a.actorUserId} · {new Date(a.createdAt).toLocaleString("en-IN")}</span></div>)}</div>}
 </section></div></main>
}
function Card({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <article className="rounded-xl border p-4"><div className="flex items-center gap-2 text-brand-700">{icon}<b>{title}</b></div><div className="mt-3">{children}</div></article>}
export default function Page(){return <AuthGate roles={["SUPER_ADMIN","BRANCH_ADMIN","ACCOUNTANT","TEACHER","EMPLOYEE"]}><Content/></AuthGate>}
