"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Download, FileText, Loader2, Paperclip, Play, Plus, Radio, Square, Upload } from "lucide-react";
import { AuthGate, errorMessage, getAccessToken, useAuth } from "../../../components/auth-provider";
import { documentAsBase64, validateDocumentFile } from "../../../components/document-upload";
import { openAuthenticatedDocument } from "../../../components/authenticated-download";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api/v1";
type Person={id:string;name:string;email:string;role:string};
type Participant={id:string;userId:string;meetingRole:string;responseStatus:string;invitationStatus:string;removedAt:string|null;user:Person|null};
type Action={id:string;title:string;description:string|null;status:string;priority:string;dueAt:string|null;assigneeUserId:string;assignee?:Person|null;completionNote?:string|null};
type Meeting={id:string;title:string;description:string|null;type:string;startsAt:string;endsAt:string;timezone:string;status:string;visibility:string;branchId:string|null;departmentId:string|null;hostUserId:string;host:Person|null;roomLocked:boolean;allowRecording:boolean;recordingRequired:boolean;allowChat:boolean;allowWhiteboard:boolean;allowAnnotation:boolean;allowScreenShare:boolean;participants:Participant[];agendaItems:Array<{id:string;title:string;description:string|null;sequence:number;plannedMinutes:number|null;status:string}>;attachments:Array<{id:string;name:string;mimeType:string;size:number;visibility:string;createdAt:string}>;minutes:{id:string;summary:string;status:string;approvedAt:string|null;publishedAt:string|null}|null;decisions:Array<{id:string;decision:string;rationale:string|null;createdAt:string}>;actionItems:Action[];recordings:Array<{id:string;status:string;startedAt:string|null;stoppedAt:string|null;sizeBytes?:string|null;objectKey?:string|null;createdAt:string}>};
type Attendance={id:string;status:string;firstJoinedAt:string|null;lastLeftAt:string|null;totalDurationSeconds:number;joinCount:number;user:Person|null};
type Audit={id:string;action:string;entityType:string;entityId:string|null;createdAt:string;actorUserId:string;metadata:any};

async function api(path:string,init?:RequestInit){const response=await fetch(`${API}${path}`,{...init,headers:{Authorization:`Bearer ${getAccessToken()??""}`,...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers}});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message??"Request failed");return body}
const pretty=(v:string)=>v.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,x=>x.toUpperCase());
const dt=(v:string|null)=>v?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const duration=(seconds:number)=>seconds<60?`${seconds}s`:`${Math.floor(seconds/60)}m ${seconds%60}s`;

function Content(){
  const {id}=useParams<{id:string}>(); const router=useRouter(); const {user}=useAuth();
  const [meeting,setMeeting]=useState<Meeting|null>(null),[tab,setTab]=useState("overview"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const [attendance,setAttendance]=useState<Attendance[]>([]),[audit,setAudit]=useState<Audit[]>([]);
  const [minutes,setMinutes]=useState(""),[decision,setDecision]=useState(""),[action,setAction]=useState({title:"",assigneeUserId:"",dueAt:"",priority:"NORMAL"});
  const load=useCallback(async()=>{if(!id)return;setError("");try{const result=await api(`/meetings/${id}`);setMeeting(result.data);setMinutes(result.data.minutes?.summary??"")}catch(cause){setError(errorMessage(cause))}},[id]);
  useEffect(()=>{void load()},[load]);

  const me=meeting?.participants.find(p=>p.userId===user?.id&&!p.removedAt);
  const manager=Boolean(user?.role==="SUPER_ADMIN"||user?.role==="BRANCH_ADMIN"||me?.meetingRole==="HOST"||me?.meetingRole==="CO_HOST");
  const live=meeting?.status==="LIVE"||meeting?.status==="OPEN_FOR_JOIN";
  const closed=["CANCELLED","CLOSED","MINUTES_PUBLISHED"].includes(meeting?.status??"");
  const attendees=useMemo(()=>meeting?.participants.filter(p=>!p.removedAt)??[],[meeting]);

  useEffect(()=>{if(!meeting||!manager)return;if(tab==="attendance")api(`/meetings/${meeting.id}/attendance`).then(r=>setAttendance(r.data??[])).catch(c=>setError(errorMessage(c)));if(tab==="audit")api(`/meetings/${meeting.id}/audit`).then(r=>setAudit(r.data??[])).catch(c=>setError(errorMessage(c)))},[tab,meeting?.id,manager]);

  const mutate=async(path:string,body:any={})=>{setBusy(true);setError("");setNotice("");try{const result=await api(path,{method:"POST",body:JSON.stringify(body)});await load();return result}catch(cause){setError(errorMessage(cause));throw cause}finally{setBusy(false)}};
  const start=async()=>{try{await mutate(`/meetings/${id}/start`);router.push(`/meetings/${id}/live`)}catch{}};
  const end=async()=>{if(!confirm("End this meeting for all participants?"))return;try{await mutate(`/meetings/${id}/end`);setNotice("Meeting ended. Attendance has been finalized and minutes are now pending.")}catch{}};
  const cancel=async()=>{const reason=prompt("Cancellation reason (optional)")??"";if(!confirm("Cancel this meeting?"))return;try{await mutate(`/meetings/${id}/cancel`,{reason:reason||undefined});setNotice("Meeting cancelled.")}catch{}};
  const respond=async(response:string)=>{try{await mutate(`/meetings/${id}/respond`,{response});setNotice(`Response saved: ${pretty(response)}`)}catch{}};
  const saveMinutes=async()=>{setBusy(true);try{await api(`/meetings/${id}/minutes`,{method:"PUT",body:JSON.stringify({summary:minutes})});await load();setNotice("Minutes saved as draft.")}catch(c){setError(errorMessage(c))}finally{setBusy(false)}};
  const submitMinutes=async()=>{try{await mutate(`/meetings/${id}/minutes/submit`);setNotice("Minutes submitted for approval.")}catch{}};
  const approveMinutes=async()=>{try{await mutate(`/meetings/${id}/minutes/approve`);setNotice("Minutes approved.")}catch{}};
  const publishMinutes=async()=>{try{await mutate(`/meetings/${id}/minutes/publish`);setNotice("Minutes published to participants.")}catch{}};
  const addDecision=async()=>{if(!decision.trim())return;try{await mutate(`/meetings/${id}/decisions`,{decision});setDecision("");setNotice("Decision recorded.")}catch{}};
  const addAction=async()=>{if(!action.title.trim()||!action.assigneeUserId)return;try{await mutate(`/meetings/${id}/actions`,{...action,dueAt:action.dueAt?new Date(action.dueAt).toISOString():null});setAction({title:"",assigneeUserId:"",dueAt:"",priority:"NORMAL"});setNotice("Action assigned.")}catch{}};
  const completeAction=async(actionId:string)=>{try{await mutate(`/meeting-actions/${actionId}/complete`,{completionNote:"Completed from meeting workspace"});setNotice("Action completed.")}catch{}};
  const downloadRecording=async(row:{id:string})=>{try{await openAuthenticatedDocument({url:`${API}/meetings/${id}/recordings/${row.id}/download`,token:getAccessToken()??"",fileName:`${meeting?.title??"meeting"}-recording.mp4`,fallbackError:"Recording is not available yet"})}catch(c){setError(errorMessage(c))}};
  const downloadAttachment=async(row:{id:string;name:string})=>{try{await openAuthenticatedDocument({url:`${API}/meetings/${id}/attachments/${row.id}/download`,token:getAccessToken()??"",fileName:row.name,fallbackError:"Unable to download attachment"})}catch(c){setError(errorMessage(c))}};
  const uploadAttachment=async(file:File|null)=>{if(!file)return;setBusy(true);try{validateDocumentFile(file,10*1024*1024);const base64=await documentAsBase64(file);await api(`/meetings/${id}/attachments`,{method:"POST",body:JSON.stringify({name:file.name,mimeType:file.type,base64,visibility:"PARTICIPANTS"})});await load();setNotice("Attachment uploaded.")}catch(c){setError(errorMessage(c))}finally{setBusy(false)}};

  if(!meeting)return <main className="grid min-h-screen place-items-center bg-slate-50 dark:bg-slate-950">{error?<div className="max-w-xl rounded-xl bg-red-50 p-5 text-red-700">{error}</div>:<Loader2 className="animate-spin text-brand-700"/>}</main>;
  return <main className="min-h-screen bg-slate-50 dark:bg-slate-950"><div className="container-page py-7">
    <Link href="/meetings" className="text-sm font-bold text-brand-700">← All meetings</Link>
    <header className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wide text-brand-700">{pretty(meeting.type)}</p><h1 className="mt-1 text-3xl font-black">{meeting.title}</h1><p className="mt-2 text-sm text-slate-500">{dt(meeting.startsAt)} — {dt(meeting.endsAt)} · {meeting.timezone}</p><p className="mt-1 text-sm text-slate-500">Host: {meeting.host?.name??"—"} · {attendees.length} participants</p></div><span className={`rounded-full px-3 py-1.5 text-sm font-black ${meeting.status==="LIVE"?"bg-red-100 text-red-700":"bg-blue-50 text-blue-700"}`}>{pretty(meeting.status)}</span></header>
    {error&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{notice}</p>}
    <div className="mt-5 flex flex-wrap gap-2">
      {manager&&!live&&!closed&&meeting.status!=="CANCELLED"&&<button disabled={busy} onClick={()=>void start()} className="inline-flex items-center gap-2 rounded-xl bg-brand-700 px-4 py-2.5 font-bold text-white"><Play size={16}/>Start meeting</button>}
      {live&&<Link href={`/meetings/${meeting.id}/live`} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 font-bold text-white"><Radio size={16}/>Join live meeting</Link>}
      {manager&&meeting.status==="LIVE"&&<button disabled={busy} onClick={()=>void end()} className="inline-flex items-center gap-2 rounded-xl bg-red-700 px-4 py-2.5 font-bold text-white"><Square size={15}/>End meeting</button>}
      {manager&&!["LIVE","CANCELLED","CLOSED"].includes(meeting.status)&&<button disabled={busy} onClick={()=>void cancel()} className="rounded-xl border px-4 py-2.5 font-bold text-red-700">Cancel</button>}
      {me&&me.responseStatus==="PENDING"&&<><button onClick={()=>void respond("ACCEPTED")} className="rounded-xl border px-4 py-2.5 font-bold">Accept</button><button onClick={()=>void respond("DECLINED")} className="rounded-xl border px-4 py-2.5 font-bold">Decline</button></>}
    </div>

    <nav className="mt-7 flex gap-2 overflow-x-auto pb-2">{["overview","agenda","participants","files","attendance","minutes","decisions","actions","recordings","audit"].filter(x=>manager||!["attendance","audit"].includes(x)).map(x=><button key={x} onClick={()=>setTab(x)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${tab===x?"bg-brand-700 text-white":"border bg-white dark:bg-slate-900"}`}>{pretty(x)}</button>)}</nav>

    <section className="mt-5 rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900">
      {tab==="overview"&&<div className="grid gap-5 lg:grid-cols-2"><div><h2 className="text-lg font-black">Meeting brief</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600 dark:text-slate-300">{meeting.description||"No description provided."}</p></div><div className="grid grid-cols-2 gap-3 text-sm">{[["Scope",pretty(meeting.visibility)],["Chat",meeting.allowChat?"Enabled":"Disabled"],["Whiteboard",meeting.allowWhiteboard?"Enabled":"Disabled"],["Annotation",meeting.allowAnnotation?"Enabled":"Disabled"],["Screen share",meeting.allowScreenShare?"Enabled":"Disabled"],["Recording",meeting.allowRecording?(meeting.recordingRequired?"Required":"Allowed"):"Disabled"]].map(([k,v])=><div key={String(k)} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><small className="uppercase text-slate-400">{k}</small><p className="font-bold">{v}</p></div>)}</div></div>}
      {tab==="agenda"&&<div><h2 className="text-lg font-black">Agenda</h2><div className="mt-4 space-y-3">{meeting.agendaItems.map(item=><div key={item.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><b>{item.sequence}. {item.title}</b><span className="text-xs text-slate-500">{item.plannedMinutes?item.plannedMinutes+" min":""} {pretty(item.status)}</span></div>{item.description&&<p className="mt-2 text-sm text-slate-500">{item.description}</p>}</div>)}{!meeting.agendaItems.length&&<p className="text-sm text-slate-500">No agenda items.</p>}</div></div>}
      {tab==="participants"&&<div><h2 className="text-lg font-black">Participants</h2><div className="mt-4 grid gap-3 lg:grid-cols-2">{attendees.map(p=><div key={p.id} className="rounded-xl border p-4"><div className="flex justify-between gap-2"><div><b>{p.user?.name??p.userId}</b><p className="text-xs text-slate-500">{p.user?.email} · {p.user?.role}</p></div><span className="text-xs font-bold">{pretty(p.meetingRole)}</span></div><p className="mt-2 text-xs text-slate-500">RSVP: {pretty(p.responseStatus)}</p></div>)}</div></div>}
      {tab==="files"&&<div><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black">Meeting attachments</h2><p className="text-sm text-slate-500">Private to authorized meeting participants.</p></div><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border px-4 py-2 font-bold"><Upload size={16}/>Upload<input type="file" className="hidden" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" onChange={e=>void uploadAttachment(e.target.files?.[0]??null)}/></label></div><div className="mt-4 space-y-2">{meeting.attachments.map(row=><button key={row.id} onClick={()=>void downloadAttachment(row)} className="flex w-full items-center justify-between rounded-xl border p-4 text-left"><span className="inline-flex items-center gap-2"><Paperclip size={16}/><span><b>{row.name}</b><small className="block text-slate-500">{Math.ceil(row.size/1024)} KB</small></span></span><Download size={16}/></button>)}{!meeting.attachments.length&&<p className="text-sm text-slate-500">No attachments.</p>}</div></div>}
      {tab==="attendance"&&manager&&<div><h2 className="text-lg font-black">Join / leave attendance</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-400"><th className="p-3">Participant</th><th>Status</th><th>First join</th><th>Last leave</th><th>Duration</th><th>Joins</th></tr></thead><tbody>{attendance.map(row=><tr key={row.id} className="border-b last:border-0"><td className="p-3 font-bold">{row.user?.name??"Unknown"}</td><td>{pretty(row.status)}</td><td>{dt(row.firstJoinedAt)}</td><td>{dt(row.lastLeftAt)}</td><td>{duration(row.totalDurationSeconds)}</td><td>{row.joinCount}</td></tr>)}</tbody></table></div></div>}
      {tab==="minutes"&&<div><div className="flex justify-between gap-3"><div><h2 className="text-lg font-black">Minutes of Meeting</h2><p className="text-sm text-slate-500">Status: {pretty(meeting.minutes?.status??"DRAFT")}</p></div></div><textarea disabled={!manager} rows={12} className="field mt-4" value={minutes} onChange={e=>setMinutes(e.target.value)} placeholder="Summary, discussion notes, conclusions…"/>{manager&&<div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>void saveMinutes()} className="rounded-xl bg-brand-700 px-4 py-2 font-bold text-white">Save draft</button>{meeting.minutes?.status==="DRAFT"&&<button onClick={()=>void submitMinutes()} className="rounded-xl border px-4 py-2 font-bold">Submit</button>}{["SUPER_ADMIN","BRANCH_ADMIN"].includes(user?.role??"")&&meeting.minutes?.status==="UNDER_REVIEW"&&<button onClick={()=>void approveMinutes()} className="rounded-xl border px-4 py-2 font-bold">Approve</button>}{meeting.minutes?.status==="APPROVED"&&<button onClick={()=>void publishMinutes()} className="rounded-xl border px-4 py-2 font-bold">Publish</button>}</div>}</div>}
      {tab==="decisions"&&<div><h2 className="text-lg font-black">Decisions</h2>{manager&&<div className="mt-4 flex gap-2"><input className="field" placeholder="Record a formal decision" value={decision} onChange={e=>setDecision(e.target.value)}/><button onClick={()=>void addDecision()} className="rounded-xl bg-brand-700 px-4 font-bold text-white">Add</button></div>}<div className="mt-4 space-y-3">{meeting.decisions.map(row=><div key={row.id} className="rounded-xl border p-4"><p className="font-semibold">{row.decision}</p>{row.rationale&&<p className="mt-2 text-sm text-slate-500">{row.rationale}</p>}<small className="mt-2 block text-slate-400">{dt(row.createdAt)}</small></div>)}{!meeting.decisions.length&&<p className="text-sm text-slate-500">No formal decisions recorded.</p>}</div></div>}
      {tab==="actions"&&<div><h2 className="text-lg font-black">Action items</h2>{manager&&<div className="mt-4 grid gap-2 lg:grid-cols-[1.5fr_1fr_180px_130px_auto]"><input className="field" placeholder="Action item" value={action.title} onChange={e=>setAction({...action,title:e.target.value})}/><select className="field" value={action.assigneeUserId} onChange={e=>setAction({...action,assigneeUserId:e.target.value})}><option value="">Assignee</option>{attendees.map(p=><option key={p.userId} value={p.userId}>{p.user?.name??p.userId}</option>)}</select><input type="datetime-local" className="field" value={action.dueAt} onChange={e=>setAction({...action,dueAt:e.target.value})}/><select className="field" value={action.priority} onChange={e=>setAction({...action,priority:e.target.value})}>{["LOW","NORMAL","HIGH","URGENT"].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>void addAction()} className="rounded-xl bg-brand-700 px-4 font-bold text-white"><Plus size={16}/></button></div>}<div className="mt-4 space-y-3">{meeting.actionItems.map(row=><div key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div><b>{row.title}</b><p className="text-xs text-slate-500">{row.assignee?.name??row.assigneeUserId} · {pretty(row.priority)} {row.dueAt?"· Due "+dt(row.dueAt):""}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{pretty(row.status)}</span>{row.status!=="COMPLETED"&&(row.assigneeUserId===user?.id||manager)&&<button onClick={()=>void completeAction(row.id)} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Complete</button>}</div></div>)}</div></div>}
      {tab==="recordings"&&<div><h2 className="text-lg font-black">Recording archive</h2><p className="mt-1 text-sm text-slate-500">Recordings are stored privately and require authorized access.</p><div className="mt-4 space-y-3">{meeting.recordings.filter(x=>x.status!=="DELETED").map(row=><div key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div><span className="inline-flex items-center gap-2 font-bold"><FileText size={16}/>Meeting recording</span><p className="text-xs text-slate-500">{pretty(row.status)} · {dt(row.startedAt??row.createdAt)}</p></div><button disabled={!row.objectKey} onClick={()=>void downloadRecording(row)} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-bold disabled:opacity-50"><Download size={15}/>Download</button></div>)}{!meeting.recordings.length&&<p className="text-sm text-slate-500">No recordings.</p>}</div></div>}
      {tab==="audit"&&manager&&<div><h2 className="text-lg font-black">Meeting audit log</h2><div className="mt-4 space-y-2">{audit.map(row=><div key={row.id} className="rounded-xl border p-3 text-sm"><b>{pretty(row.action)}</b><span className="ml-2 text-slate-500">{row.entityType}{row.entityId?" · "+row.entityId:""} · {dt(row.createdAt)}</span></div>)}{!audit.length&&<p className="text-sm text-slate-500">No audit entries loaded.</p>}</div></div>}
    </section>
  </div><style jsx global>{`.field{width:100%;border:1px solid #dbe1ea;border-radius:.75rem;padding:.65rem .8rem;background:transparent}`}</style></main>
}

export default function Page(){return <AuthGate roles={["SUPER_ADMIN","BRANCH_ADMIN","ACCOUNTANT","TEACHER","EMPLOYEE"]}><Content/></AuthGate>}
