"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { CheckCircle2, Pencil, Plus, Search } from "lucide-react";
import { AuthGate, getAccessToken } from "../../../components/auth-provider";
import Sidebar from "../../../components/sidebar";
const api=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api/v1";
type Course={id:string;title:string;courseCode:string;courseType:string;categoryType:string|null;taxonomyReviewStatus:string;regularPricePaise:number;salePricePaise:number|null;status:string;branch:{branchName:string}|null};
function Content(){const [data,setData]=useState<Course[]>([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");const params=useSearchParams(),created=params.get("created")==="1",updated=params.get("updated")==="1";useEffect(()=>{setLoading(true);setError("");fetch(`${api}/admin/courses?search=${encodeURIComponent(q)}`,{headers:{Authorization:`Bearer ${getAccessToken()??""}`}}).then(async response=>{const json=await response.json();if(!response.ok)throw Error(json?.error?.message??"Unable to load courses");setData(json.data)}).catch(cause=>setError(cause instanceof Error?cause.message:"Unable to load courses")).finally(()=>setLoading(false))},[q]);return <div className="min-h-screen bg-slate-50 dark:bg-slate-950"><Sidebar/><main className="p-5 md:ml-64 md:p-10"><div className="flex items-center justify-between gap-4"><h1 className="text-3xl font-bold">Courses</h1><Link href="/admin/courses/new" className="inline-flex items-center gap-2 rounded-xl bg-brand-700 px-4 py-3 text-sm font-bold text-white"><Plus size={18}/>Add Course</Link></div>{(created||updated)&&<p role="status" className="mt-5 flex items-center gap-2 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700"><CheckCircle2 size={18}/>Course {updated?"updated":"created"} successfully.</p>}<label className="relative mt-6 block max-w-lg"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input className="w-full rounded-xl border p-3 pl-10" placeholder="Search courses" value={q} onChange={event=>setQ(event.target.value)}/></label>{error?<p role="alert" className="mt-4 text-red-600">{error}</p>:<div className="mt-6 overflow-x-auto rounded-xl border bg-white dark:bg-slate-900"><table className="w-full min-w-[900px] text-sm"><thead><tr><th>Course</th><th>Code</th><th>Category</th><th>Branch</th><th>Price</th><th>Status</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="p-8 text-center">Loading courses…</td></tr>:data.length?data.map(course=><tr key={course.id} className="border-t"><td className="p-3 font-semibold">{course.title}</td><td>{course.courseCode}</td><td>{course.categoryType?.replaceAll("_"," ")??<span className="text-amber-700">Review required ({course.courseType})</span>}</td><td>{course.branch?.branchName??"All branches"}</td><td>₹{((course.salePricePaise??course.regularPricePaise)/100).toLocaleString("en-IN")}</td><td>{course.status}</td><td><Link href={`/admin/courses/${course.id}/edit`} className="inline-flex items-center gap-1 rounded-lg p-2 text-brand-700 hover:bg-brand-50"><Pencil size={15}/>Edit</Link></td></tr>):<tr><td colSpan={7} className="p-8 text-center">No courses found</td></tr>}</tbody></table></div>}</main></div>}
export default function Courses(){return <AuthGate roles={["SUPER_ADMIN","BRANCH_ADMIN"]}><Content/></AuthGate>}
