import { ClassLevel, CourseMode, CourseStatus, CourseType, Role } from "@prisma/client";
import { Router } from "express";
import { z } from "zod";
import { ensureDefaultCourseCategories } from "../lib/default-course-categories.js";
import { AppError } from "../lib/http.js";
import { prisma } from "../lib/prisma.js";
import { allow, requireAuth, type AuthRequest } from "../middleware/auth.js";

const router = Router(); router.use(requireAuth, allow(Role.SUPER_ADMIN, Role.BRANCH_ADMIN));
const input = z.object({ title:z.string().trim().min(3), slug:z.string().trim().toLowerCase().regex(/^[a-z0-9-]+$/), courseCode:z.string().trim().min(2).max(30), shortDescription:z.string().trim().max(300).nullable().optional(), fullDescription:z.string().trim().min(10), courseType:z.nativeEnum(CourseType), classLevel:z.nativeEnum(ClassLevel), stream:z.string().trim().max(80).nullable().optional(), durationDays:z.number().int().positive(), regularPricePaise:z.number().int().min(0), salePricePaise:z.number().int().min(0).nullable().optional(), registrationFeePaise:z.number().int().min(0).default(0), admissionFeePaise:z.number().int().min(0).default(0), thumbnailUrl:z.string().url().nullable().optional(), brochureUrl:z.string().url().nullable().optional(), eligibility:z.string().max(5000).nullable().optional(), learningOutcomes:z.string().max(5000).nullable().optional(), language:z.string().trim().min(2), mode:z.nativeEnum(CourseMode), status:z.nativeEnum(CourseStatus).default(CourseStatus.DRAFT), isFeatured:z.boolean().default(false), enrollmentOpen:z.boolean().default(true), startDate:z.coerce.date().nullable().optional(), endDate:z.coerce.date().nullable().optional(), branchId:z.string().cuid().nullable().optional(), categoryId:z.string().cuid() });
const select = { id:true,title:true,slug:true,courseCode:true,shortDescription:true,fullDescription:true,courseType:true,classLevel:true,stream:true,durationDays:true,regularPricePaise:true,salePricePaise:true,registrationFeePaise:true,admissionFeePaise:true,thumbnailUrl:true,brochureUrl:true,eligibility:true,learningOutcomes:true,language:true,mode:true,status:true,isFeatured:true,enrollmentOpen:true,startDate:true,endDate:true,branchId:true,createdAt:true,updatedAt:true,category:{select:{id:true,name:true}},branch:{select:{id:true,branchName:true}},instructor:{select:{id:true,name:true}},subjects:{include:{subject:true,teacher:{select:{id:true,name:true}}}},_count:{select:{enrollments:true,batches:true,modules:true}} } as const;
async function scope(req:AuthRequest, branchId?:string|null){ if(req.auth!.role!==Role.BRANCH_ADMIN)return; const assigned=await prisma.branchUser.findMany({where:{userId:req.auth!.userId},select:{branchId:true}}); const ids=assigned.map(x=>x.branchId); if(branchId&&!ids.includes(branchId)) throw new AppError(403,"BRANCH_FORBIDDEN","Branch access denied"); return ids; }
router.get("/course-categories",async(req:AuthRequest,res)=>{if(!await prisma.category.count())await ensureDefaultCourseCategories(prisma,req.auth!.organizationId);res.json({data:await prisma.category.findMany({orderBy:{name:"asc"}})})});
router.get("/course-subjects",async(_q,res)=>res.json({data:await prisma.subject.findMany({orderBy:{name:"asc"}})}));
router.get("/courses",async(req:AuthRequest,res)=>{const q=z.object({page:z.coerce.number().positive().default(1),limit:z.coerce.number().min(1).max(100).default(10),search:z.string().optional(),status:z.nativeEnum(CourseStatus).optional(),courseType:z.nativeEnum(CourseType).optional(),branchId:z.string().cuid().optional(),sortBy:z.enum(["title","courseCode","regularPricePaise","durationDays","startDate","createdAt"]).default("createdAt"),sortOrder:z.enum(["asc","desc"]).default("desc")}).parse(req.query); const ids=await scope(req,q.branchId); const where={...(ids?{OR:[{branchId:{in:ids}},{branchId:null}]}:{}),...(q.branchId?{branchId:q.branchId}:{}),...(q.status?{status:q.status}:{}),...(q.courseType?{courseType:q.courseType}:{}),...(q.search?{OR:[{title:{contains:q.search,mode:"insensitive" as const}},{courseCode:{contains:q.search,mode:"insensitive" as const}},{slug:{contains:q.search,mode:"insensitive" as const}},{fullDescription:{contains:q.search,mode:"insensitive" as const}}]}:{})};const [total,data]=await prisma.$transaction([prisma.course.count({where}),prisma.course.findMany({where,select,skip:(q.page-1)*q.limit,take:q.limit,orderBy:{[q.sortBy]:q.sortOrder}})]);res.json({data,meta:{total,page:q.page,limit:q.limit,totalPages:Math.max(1,Math.ceil(total/q.limit))}})});
router.get("/courses/:id",async(req:AuthRequest,res)=>{const data=await prisma.course.findUnique({where:{id:String(req.params.id)},select});if(!data)throw new AppError(404,"COURSE_NOT_FOUND","Course not found");await scope(req,data.branchId);res.json({data})});
router.post("/courses",async(req:AuthRequest,res)=>{const data=input.parse(req.body);if(data.salePricePaise!==null&&data.salePricePaise!==undefined&&data.salePricePaise>data.regularPricePaise)throw new AppError(422,"INVALID_PRICE","Sale price cannot exceed regular price");if(data.startDate&&data.endDate&&data.endDate<data.startDate)throw new AppError(422,"INVALID_DATES","End date must follow start date");await scope(req,data.branchId);const [duplicate,category]=await prisma.$transaction([prisma.course.findFirst({where:{OR:[{slug:data.slug},{courseCode:data.courseCode}]},select:{slug:true,courseCode:true}}),prisma.category.findUnique({where:{id:data.categoryId},select:{id:true}})]);if(duplicate)throw new AppError(409,duplicate.slug===data.slug?"COURSE_SLUG_EXISTS":"COURSE_CODE_EXISTS",duplicate.slug===data.slug?"A course already uses this slug":"A course already uses this course code");if(!category)throw new AppError(422,"CATEGORY_NOT_FOUND","Select a valid course category");res.status(201).json({data:await prisma.course.create({data:{...data,createdById:req.auth!.userId},select})})});
router.patch("/courses/:id",async(req:AuthRequest,res)=>{const old=await prisma.course.findUnique({where:{id:String(req.params.id)}});if(!old)throw new AppError(404,"COURSE_NOT_FOUND","Course not found");await scope(req,old.branchId);const data=input.partial().parse(req.body);if(data.branchId!==undefined)await scope(req,data.branchId);res.json({data:await prisma.course.update({where:{id:old.id},data,select})})});
router.patch("/courses/:id/status",async(req,res)=>res.json({data:await prisma.course.update({where:{id:req.params.id},data:{status:z.object({status:z.nativeEnum(CourseStatus)}).parse(req.body).status},select})}));
router.patch("/courses/:id/featured",async(req,res)=>res.json({data:await prisma.course.update({where:{id:req.params.id},data:{isFeatured:z.object({isFeatured:z.boolean()}).parse(req.body).isFeatured},select})}));
router.delete("/courses/:id",async(req,res)=>{const c=await prisma.course.findUnique({where:{id:String(req.params.id)},include:{_count:{select:{enrollments:true,batches:true,modules:true}}}});if(!c)throw new AppError(404,"COURSE_NOT_FOUND","Course not found");if(c._count.enrollments||c._count.batches||c._count.modules)throw new AppError(409,"COURSE_IN_USE","Archive this course; it has active dependencies");await prisma.course.delete({where:{id:c.id}});res.status(204).send()});
router.post("/courses/:id/subjects",async(req,res)=>{const d=z.object({subjectId:z.string().cuid(),teacherId:z.string().cuid().nullable().optional(),position:z.number().int().min(0).default(0),isActive:z.boolean().default(true)}).parse(req.body);res.status(201).json({data:await prisma.courseSubject.upsert({where:{courseId_subjectId:{courseId:req.params.id,subjectId:d.subjectId}},update:d,create:{...d,courseId:req.params.id}})})});router.delete("/courses/:id/subjects/:subjectId",async(req,res)=>{await prisma.courseSubject.delete({where:{courseId_subjectId:{courseId:req.params.id,subjectId:req.params.subjectId}}});res.status(204).send()});
export default router;
