import { BatchStatus, Role } from "@prisma/client";
import { Router } from "express";
import { z } from "zod";
import { AppError } from "../lib/http.js";
import { prisma } from "../lib/prisma.js";
import { allow, requireAuth, type AuthRequest } from "../middleware/auth.js";

const router=Router();router.use(requireAuth,allow(Role.SUPER_ADMIN,Role.BRANCH_ADMIN));
const input=z.object({name:z.string().trim().min(2).max(120),code:z.string().trim().toUpperCase().min(2).max(40).regex(/^[A-Z0-9-]+$/),branchId:z.string().cuid(),courseId:z.string().cuid().nullable().optional(),academicSession:z.string().trim().min(4).max(30),startsAt:z.coerce.date(),endsAt:z.coerce.date().nullable().optional(),capacity:z.number().int().positive().max(10000),timing:z.string().trim().min(3).max(80),days:z.array(z.enum(["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY"])).min(1),classroom:z.string().trim().max(80).nullable().optional(),teacherId:z.string().cuid().nullable().optional(),feesPaise:z.number().int().min(0),status:z.nativeEnum(BatchStatus).default(BatchStatus.ACTIVE),remarks:z.string().trim().max(2000).nullable().optional()});
const select={id:true,name:true,code:true,academicSession:true,startsAt:true,endsAt:true,capacity:true,timing:true,days:true,classroom:true,feesPaise:true,status:true,remarks:true,createdAt:true,updatedAt:true,branch:{select:{id:true,branchName:true,branchCode:true}},course:{select:{id:true,title:true,courseCode:true}},teacher:{select:{id:true,employeeNo:true,user:{select:{id:true,name:true}}}},_count:{select:{students:true,attendances:true}}} as const;
async function allowed(req:AuthRequest){if(req.auth!.role!==Role.BRANCH_ADMIN)return null;return(await prisma.branchUser.findMany({where:{userId:req.auth!.userId},select:{branchId:true}})).map(item=>item.branchId)}
async function access(req:AuthRequest,branchId:string){const ids=await allowed(req);if(ids&&!ids.includes(branchId))throw new AppError(403,"BRANCH_FORBIDDEN","Branch access denied")}
async function relations(data:{branchId:string;courseId?:string|null;teacherId?:string|null}){const [branch,course,teacher]=await prisma.$transaction([prisma.branch.findUnique({where:{id:data.branchId},select:{id:true}}),data.courseId?prisma.course.findUnique({where:{id:data.courseId},select:{id:true,branchId:true}}):prisma.course.findFirst({where:{id:"__none__"},select:{id:true,branchId:true}}),data.teacherId?prisma.teacherProfile.findUnique({where:{id:data.teacherId},select:{id:true,branchId:true}}):prisma.teacherProfile.findFirst({where:{id:"__none__"},select:{id:true,branchId:true}})]);if(!branch)throw new AppError(422,"BRANCH_NOT_FOUND","Select a valid branch");if(data.courseId&&(!course||(course.branchId&&course.branchId!==data.branchId)))throw new AppError(422,"INVALID_COURSE","Select a course available to this branch");if(data.teacherId&&(!teacher||teacher.branchId!==data.branchId))throw new AppError(422,"INVALID_TEACHER","Select a teacher from this branch")}
router.get("/batches",async(req:AuthRequest,res)=>{const q=z.object({page:z.coerce.number().int().positive().default(1),limit:z.coerce.number().int().min(1).max(100).default(100),search:z.string().trim().optional(),branchId:z.string().cuid().optional(),courseId:z.string().cuid().optional(),status:z.nativeEnum(BatchStatus).optional(),academicSession:z.string().trim().optional(),sortBy:z.enum(["name","code","academicSession","startsAt","capacity","feesPaise","status","createdAt"]).default("createdAt"),sortOrder:z.enum(["asc","desc"]).default("desc")}).parse(req.query);const ids=await allowed(req);if(q.branchId)await access(req,q.branchId);const where={...(ids?{branchId:{in:ids}}:{}),...(q.branchId?{branchId:q.branchId}:{}),...(q.courseId?{courseId:q.courseId}:{}),...(q.status?{status:q.status}:{}),...(q.academicSession?{academicSession:q.academicSession}:{}),...(q.search?{OR:[{name:{contains:q.search,mode:"insensitive" as const}},{code:{contains:q.search,mode:"insensitive" as const}},{academicSession:{contains:q.search,mode:"insensitive" as const}},{classroom:{contains:q.search,mode:"insensitive" as const}}]}:{})};const [total,data]=await prisma.$transaction([prisma.batch.count({where}),prisma.batch.findMany({where,select,skip:(q.page-1)*q.limit,take:q.limit,orderBy:{[q.sortBy]:q.sortOrder}})]);res.json({data,meta:{total,page:q.page,limit:q.limit,totalPages:Math.max(1,Math.ceil(total/q.limit))}})});
router.get("/batches/:id",async(req:AuthRequest,res)=>{const data=await prisma.batch.findUnique({where:{id:String(req.params.id)},select});if(!data)throw new AppError(404,"BATCH_NOT_FOUND","Batch not found");await access(req,data.branch.id);res.json({data})});
router.post("/batches",async(req:AuthRequest,res)=>{const data=input.parse(req.body);if(data.endsAt&&data.endsAt<data.startsAt)throw new AppError(422,"INVALID_DATES","End date must follow start date");await access(req,data.branchId);await relations(data);if(await prisma.batch.findUnique({where:{code:data.code},select:{id:true}}))throw new AppError(409,"BATCH_CODE_EXISTS","A batch already uses this code");res.status(201).json({data:await prisma.batch.create({data,select})})});
router.patch("/batches/:id",async(req:AuthRequest,res)=>{const old=await prisma.batch.findUnique({where:{id:String(req.params.id)},select:{id:true,branchId:true,courseId:true,teacherId:true,startsAt:true,endsAt:true,_count:{select:{students:true}}}});if(!old)throw new AppError(404,"BATCH_NOT_FOUND","Batch not found");await access(req,old.branchId);const data=input.partial().parse(req.body);const branchId=data.branchId??old.branchId;if(data.branchId)await access(req,data.branchId);if(data.capacity!==undefined&&data.capacity<old._count.students)throw new AppError(422,"CAPACITY_BELOW_STRENGTH","Capacity cannot be less than current strength");const startsAt=data.startsAt??old.startsAt,endsAt=data.endsAt===undefined?old.endsAt:data.endsAt;if(endsAt&&endsAt<startsAt)throw new AppError(422,"INVALID_DATES","End date must follow start date");await relations({branchId,courseId:data.courseId===undefined?old.courseId:data.courseId,teacherId:data.teacherId===undefined?old.teacherId:data.teacherId});if(data.code&&await prisma.batch.findFirst({where:{code:data.code,id:{not:old.id}},select:{id:true}}))throw new AppError(409,"BATCH_CODE_EXISTS","A batch already uses this code");res.json({data:await prisma.batch.update({where:{id:old.id},data,select})})});
router.patch("/batches/:id/status",async(req:AuthRequest,res)=>{const {status}=z.object({status:z.nativeEnum(BatchStatus)}).parse(req.body);const old=await prisma.batch.findUnique({where:{id:String(req.params.id)},select:{id:true,branchId:true}});if(!old)throw new AppError(404,"BATCH_NOT_FOUND","Batch not found");await access(req,old.branchId);res.json({data:await prisma.batch.update({where:{id:old.id},data:{status},select})})});
router.delete("/batches/:id",async(req:AuthRequest,res)=>{const old=await prisma.batch.findUnique({where:{id:String(req.params.id)},select:{id:true,branchId:true,_count:{select:{students:true,attendances:true}}}});if(!old)throw new AppError(404,"BATCH_NOT_FOUND","Batch not found");await access(req,old.branchId);if(old._count.students)throw new AppError(409,"BATCH_HAS_STUDENTS","Archive this batch; enrolled students prevent deletion");if(old._count.attendances)throw new AppError(409,"BATCH_HAS_ATTENDANCE","Archive this batch; attendance records prevent deletion");await prisma.batch.delete({where:{id:old.id}});res.status(204).send()});
export default router;
