import { Role } from "@prisma/client";
import { Router } from "express";
import { z } from "zod";
import { AppError } from "../lib/http.js";
import { prisma } from "../lib/prisma.js";
import { allocatedSubjects, effectiveDateForSession } from "../lib/subject-resolution.js";
import { allow, requireAuth, type AuthRequest } from "../middleware/auth.js";

const router=Router();router.use(requireAuth,allow(Role.SUPER_ADMIN,Role.BRANCH_ADMIN,Role.TEACHER));const id=z.string().cuid();
router.get("/subject-options",async(req:AuthRequest,res)=>{const q=z.object({branchId:id,courseId:id,batchId:id,teacherId:id.optional(),academicSessionId:id.optional(),academicSession:z.string().trim().optional(),effectiveAt:z.coerce.date().optional()}).parse(req.query);let teacherId=q.teacherId;if(req.auth!.role===Role.BRANCH_ADMIN){const access=await prisma.branchUser.findFirst({where:{userId:req.auth!.userId,branchId:q.branchId},select:{branchId:true}});if(!access)throw new AppError(403,"BRANCH_FORBIDDEN","Branch access denied")}if(req.auth!.role===Role.TEACHER){const teacher=await prisma.teacherProfile.findUnique({where:{userId:req.auth!.userId},select:{id:true,branchId:true}});if(!teacher||teacher.branchId!==q.branchId)throw new AppError(403,"TEACHER_SCOPE_FORBIDDEN","Teachers can only load their own allocated subjects");teacherId=teacher.id}else if(!teacherId)throw new AppError(422,"TEACHER_REQUIRED","Select a teacher to load allocated subjects");const session=q.academicSessionId?await prisma.academicSession.findUnique({where:{id:q.academicSessionId},select:{id:true,startsAt:true,endsAt:true}}):q.academicSession?await prisma.academicSession.findFirst({where:{name:{equals:q.academicSession,mode:"insensitive"}},select:{id:true,startsAt:true,endsAt:true}}):null;if(!session)throw new AppError(422,"ACADEMIC_SESSION_REQUIRED","Select a valid academic session");const batch=await prisma.batch.findUnique({where:{id:q.batchId},select:{branchId:true,courseId:true,academicSessionId:true}});if(!batch||batch.branchId!==q.branchId||batch.courseId!==q.courseId||batch.academicSessionId!==session.id)throw new AppError(422,"INVALID_BATCH_CONTEXT","Batch must match the selected branch, course and academic session");const data=await allocatedSubjects({branchId:q.branchId,courseId:q.courseId,batchId:q.batchId,teacherId:teacherId!,academicSessionId:session.id,effectiveAt:q.effectiveAt??effectiveDateForSession(session.startsAt,session.endsAt)});res.json({data,meta:{reason:data.length?null:"NO_EFFECTIVE_TEACHER_ALLOCATION"}})});
export default router;
