import { Prisma, Role, SubstitutionStatus, TeacherDutyType, TimetableDay, TimetablePeriodType, TimetableStatus } from "@prisma/client";
import { Router } from "express";
import { z } from "zod";
import { dailyWorkload, rankSubstituteCandidates, teacherOnApprovedLeave, timetableDay, utcDay, weeklyWorkload, workloadWarnings } from "../lib/academic-workload.js";
import { AppError } from "../lib/http.js";
import { prisma } from "../lib/prisma.js";
import { allow, requireAuth, type AuthRequest } from "../middleware/auth.js";

const router = Router(); router.use(requireAuth, allow(Role.SUPER_ADMIN, Role.BRANCH_ADMIN)); const id = z.string().cuid();
const substitutionSelect = { id: true, date: true, reason: true, status: true, createdAt: true, updatedAt: true, timetable: { select: { id: true, day: true, periodNumber: true, startMinute: true, endMinute: true } }, originalTeacher: { select: { id: true, employeeNo: true, user: { select: { name: true } } } }, substituteTeacher: { select: { id: true, employeeNo: true, user: { select: { name: true } } } }, course: { select: { id: true, title: true } }, batch: { select: { id: true, name: true } }, subject: { select: { id: true, name: true } }, approvedBy: { select: { id: true, name: true } } } as const;

async function access(req: AuthRequest, branchId: string) { const branch = await prisma.branch.findUnique({ where: { id: branchId }, select: { id: true } }); if (!branch) throw new AppError(422, "INVALID_BRANCH", "Select a branch in this organization"); if (req.auth!.role === Role.BRANCH_ADMIN && !await prisma.branchUser.findFirst({ where: { userId: req.auth!.userId, branchId }, select: { branchId: true } })) throw new AppError(403, "BRANCH_FORBIDDEN", "Branch access denied"); }
function audit(req: AuthRequest, action: string, entity: string, entityId: string, metadata?: object) { return prisma.auditLog.create({ data: { actorId: req.auth!.userId, action, entity, entityId, metadata } }); }
function clock(value: string) { const [hour, minute] = value.split(":").map(Number); return hour * 60 + minute; }

router.get("/timetable-periods", async (req: AuthRequest, res) => { const query = z.object({ branchId: id, academicSessionId: id, day: z.nativeEnum(TimetableDay).optional() }).parse(req.query); await access(req, query.branchId); const data = await prisma.timetablePeriod.findMany({ where: { branchId: query.branchId, academicSessionId: query.academicSessionId, ...(query.day ? { day: query.day } : {}) }, orderBy: [{ day: "asc" }, { periodNumber: "asc" }] }); res.json({ data }); });
router.put("/timetable-periods", async (req: AuthRequest, res) => {
  const time = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), input = z.object({ branchId: id, academicSessionId: id, day: z.nativeEnum(TimetableDay), periods: z.array(z.object({ periodNumber: z.number().int().min(1).max(50), startTime: time, endTime: time, type: z.nativeEnum(TimetablePeriodType).default(TimetablePeriodType.TEACHING), label: z.string().trim().max(80).nullable().optional(), isActive: z.boolean().default(true) })).max(50) }).parse(req.body);
  await access(req, input.branchId); const session = await prisma.academicSession.findUnique({ where: { id: input.academicSessionId }, select: { isArchived: true } }); if (!session) throw new AppError(422, "INVALID_ACADEMIC_SESSION", "Select an academic session in this organization"); if (session.isArchived) throw new AppError(409, "ACADEMIC_SESSION_ARCHIVED", "Archived academic session configuration cannot be changed");
  const normalized = input.periods.map(row => ({ ...row, startMinute: clock(row.startTime), endMinute: clock(row.endTime) })).sort((a, b) => a.startMinute - b.startMinute); if (new Set(normalized.map(row => row.periodNumber)).size !== normalized.length) throw new AppError(422, "DUPLICATE_PERIOD", "Period numbers must be unique for the day"); for (let index = 0; index < normalized.length; index++) { if (normalized[index].endMinute <= normalized[index].startMinute) throw new AppError(422, "INVALID_TIME_RANGE", "Every period must end after it starts"); if (index && normalized[index].startMinute < normalized[index - 1].endMinute) throw new AppError(409, "PERIOD_OVERLAP", "Configured periods cannot overlap"); }
  const scheduled = await prisma.timetable.findMany({ where: { branchId: input.branchId, academicSessionId: input.academicSessionId, day: input.day, status: { not: TimetableStatus.ARCHIVED } }, select: { periodNumber: true, startMinute: true, endMinute: true } });
  if (scheduled.some(row => { const period = normalized.find(candidate => candidate.periodNumber === row.periodNumber); return !period || !period.isActive || period.type !== TimetablePeriodType.TEACHING || period.startMinute !== row.startMinute || period.endMinute !== row.endMinute; })) throw new AppError(409, "PERIOD_CONFIGURATION_IN_USE", "Archive or update scheduled timetable entries before changing their configured teaching periods");
  await prisma.$transaction(async tx => { await tx.timetablePeriod.deleteMany({ where: { branchId: input.branchId, academicSessionId: input.academicSessionId, day: input.day } }); if (normalized.length) await tx.timetablePeriod.createMany({ data: normalized.map(({ startTime: _start, endTime: _end, ...row }) => ({ ...row, organizationId: req.auth!.organizationId, branchId: input.branchId, academicSessionId: input.academicSessionId, day: input.day, label: row.label ?? null })) }); });
  await audit(req, "CONFIGURE", "TimetablePeriod", `${input.branchId}:${input.academicSessionId}:${input.day}`, { periods: normalized.length }); res.json({ data: await prisma.timetablePeriod.findMany({ where: { branchId: input.branchId, academicSessionId: input.academicSessionId, day: input.day }, orderBy: { periodNumber: "asc" } }) });
});

router.get("/teacher-workload", async (req: AuthRequest, res) => { const query = z.object({ branchId: id, academicSessionId: id, teacherId: id, date: z.coerce.date() }).parse(req.query); await access(req, query.branchId); const teacher = await prisma.teacherProfile.findUnique({ where: { id: query.teacherId }, select: { branchId: true } }); if (!teacher || teacher.branchId !== query.branchId) throw new AppError(422, "INVALID_TEACHER", "Teacher must belong to the selected branch"); const [daily, weekly] = await Promise.all([dailyWorkload(query.teacherId, query.branchId, query.academicSessionId, query.date), weeklyWorkload(query.teacherId, query.branchId, query.academicSessionId, query.date)]); res.json({ data: { daily, weekly, warnings: await workloadWarnings(query.teacherId, daily, weekly.totals.totalOccupied) } }); });

async function target(idValue: string, date: Date) { const timetable = await prisma.timetable.findUnique({ where: { id: idValue }, select: { id: true, branchId: true, academicSessionId: true, courseId: true, batchId: true, subjectId: true, teacherId: true, day: true, startMinute: true, endMinute: true, periodNumber: true, status: true, session: { select: { startsAt: true, endsAt: true } } } }); if (!timetable) throw new AppError(404, "TIMETABLE_NOT_FOUND", "Timetable entry not found"); const normalized = utcDay(date); if (timetable.status !== TimetableStatus.ACTIVE || timetableDay(normalized) !== timetable.day || normalized < utcDay(timetable.session.startsAt) || normalized > utcDay(timetable.session.endsAt)) throw new AppError(422, "INVALID_SUBSTITUTION_DATE", "Date must be an active occurrence of the selected timetable entry"); return { timetable, date: normalized }; }
async function eligibleCandidate(timetable: Awaited<ReturnType<typeof target>>["timetable"], date: Date, teacherId: string) {
  const teacher = await prisma.teacherProfile.findUnique({ where: { id: teacherId }, select: { id: true, branchId: true, userId: true, maxPeriodsPerDay: true, user: { select: { isActive: true, name: true } }, subjects: { where: { subjectId: timetable.subjectId }, select: { subjectId: true } }, allocations: { where: { courseId: timetable.courseId, status: "ACTIVE" }, select: { id: true }, take: 1 } } });
  if (!teacher || teacher.id === timetable.teacherId || teacher.branchId !== timetable.branchId || !teacher.user.isActive || await teacherOnApprovedLeave(teacherId, date)) return null;
  const overlap = { startMinute: { lt: timetable.endMinute }, endMinute: { gt: timetable.startMinute } };
  const [regular, duty, substitution] = await Promise.all([
    prisma.timetable.findFirst({ where: { teacherId, day: timetable.day, status: TimetableStatus.ACTIVE, ...overlap }, select: { id: true } }),
    prisma.teacherDuty.findFirst({ where: { teacherId, date, ...overlap }, select: { id: true } }),
    prisma.teacherSubstitution.findFirst({ where: { substituteTeacherId: teacherId, date, status: { in: [SubstitutionStatus.ASSIGNED, SubstitutionStatus.COMPLETED] }, timetable: overlap }, select: { id: true } }),
  ]);
  if (regular || duty || substitution) return null;
  const load = await dailyWorkload(teacherId, timetable.branchId, timetable.academicSessionId, date), subjectQualified = Boolean(teacher.subjects.length), courseFamiliar = Boolean(teacher.allocations.length);
  return { id: teacher.id, name: teacher.user.name, subjectQualified, courseFamiliar, todayLoad: load.totalOccupied, freePeriods: load.freePeriods, warning: teacher.maxPeriodsPerDay && load.totalOccupied + 1 > teacher.maxPeriodsPerDay ? `Would exceed recommended daily maximum of ${teacher.maxPeriodsPerDay}` : null, score: (subjectQualified ? 100 : 0) + (courseFamiliar ? 20 : 0) - load.totalOccupied };
}

router.get("/substitutions/candidates", async (req: AuthRequest, res) => { const query = z.object({ timetableId: id, date: z.coerce.date() }).parse(req.query), occurrence = await target(query.timetableId, query.date); await access(req, occurrence.timetable.branchId); const teachers = await prisma.teacherProfile.findMany({ where: { branchId: occurrence.timetable.branchId, user: { isActive: true } }, select: { id: true } }), candidates = rankSubstituteCandidates((await Promise.all(teachers.map(row => eligibleCandidate(occurrence.timetable, occurrence.date, row.id)))).filter((row): row is NonNullable<typeof row> => Boolean(row))); res.json({ data: candidates }); });
router.get("/leaves/:id/affected-timetables", async (req: AuthRequest, res) => { const leave = await prisma.leaveRequest.findUnique({ where: { id: id.parse(req.params.id) }, select: { id: true, branchId: true, fromDate: true, toDate: true, status: true, user: { select: { teacherProfile: { select: { id: true } } } } } }); if (!leave) throw new AppError(404, "LEAVE_NOT_FOUND", "Leave request not found"); await access(req, leave.branchId); if (!leave.user.teacherProfile) return res.json({ data: [] }); const dates: Date[] = []; for (let date = utcDay(leave.fromDate); date <= utcDay(leave.toDate); date = new Date(date.getTime() + 86_400_000)) dates.push(date); const rows = (await Promise.all(dates.map(async date => (await prisma.timetable.findMany({ where: { branchId: leave.branchId, teacherId: leave.user.teacherProfile!.id, day: timetableDay(date), status: TimetableStatus.ACTIVE, session: { startsAt: { lte: date }, endsAt: { gte: date } } }, select: { id: true, day: true, periodNumber: true, startMinute: true, endMinute: true, course: { select: { title: true } }, batch: { select: { name: true } }, subject: { select: { name: true } }, substitutions: { where: { date, status: { in: [SubstitutionStatus.ASSIGNED, SubstitutionStatus.COMPLETED] } }, select: { id: true, status: true, substituteTeacher: { select: { user: { select: { name: true } } } } } } } })).map(row => ({ ...row, date: date.toISOString().slice(0, 10) }))))).flat(); res.json({ data: rows, meta: { leaveStatus: leave.status, affectedPeriods: rows.length, assignedSubstitutions: rows.filter(row => row.substitutions.length).length } }); });
router.get("/substitutions", async (req: AuthRequest, res) => { const query = z.object({ page: z.coerce.number().int().positive().default(1), limit: z.coerce.number().int().min(1).max(100).default(20), branchId: id.optional(), teacherId: id.optional(), status: z.nativeEnum(SubstitutionStatus).optional(), from: z.coerce.date().optional(), to: z.coerce.date().optional() }).parse(req.query); if (query.branchId) await access(req, query.branchId); const branches = req.auth!.role === Role.BRANCH_ADMIN ? (await prisma.branchUser.findMany({ where: { userId: req.auth!.userId }, select: { branchId: true } })).map(row => row.branchId) : undefined, where = { ...(branches ? { branchId: { in: branches } } : {}), ...(query.branchId ? { branchId: query.branchId } : {}), ...(query.teacherId ? { OR: [{ originalTeacherId: query.teacherId }, { substituteTeacherId: query.teacherId }] } : {}), ...(query.status ? { status: query.status } : {}), ...(query.from || query.to ? { date: { ...(query.from ? { gte: utcDay(query.from) } : {}), ...(query.to ? { lte: utcDay(query.to) } : {}) } } : {}) }; const [total, data] = await prisma.$transaction([prisma.teacherSubstitution.count({ where }), prisma.teacherSubstitution.findMany({ where, select: substitutionSelect, skip: (query.page - 1) * query.limit, take: query.limit, orderBy: { date: "desc" } })]); res.json({ data, meta: { total, page: query.page, limit: query.limit, totalPages: Math.max(1, Math.ceil(total / query.limit)) } }); });
router.post("/substitutions", async (req: AuthRequest, res) => { const input = z.object({ timetableId: id, date: z.coerce.date(), substituteTeacherId: id, reason: z.string().trim().max(2000).nullable().optional() }).parse(req.body), occurrence = await target(input.timetableId, input.date); await access(req, occurrence.timetable.branchId); if (!await teacherOnApprovedLeave(occurrence.timetable.teacherId, occurrence.date)) throw new AppError(409, "ORIGINAL_TEACHER_NOT_ON_LEAVE", "A substitution requires an approved leave for the original teacher"); const candidate = await eligibleCandidate(occurrence.timetable, occurrence.date, input.substituteTeacherId); if (!candidate) throw new AppError(409, "SUBSTITUTE_NOT_AVAILABLE", "The selected substitute is unavailable, on leave, inactive or outside the branch"); let data; try { data = await prisma.teacherSubstitution.create({ data: { branchId: occurrence.timetable.branchId, academicSessionId: occurrence.timetable.academicSessionId, timetableId: occurrence.timetable.id, date: occurrence.date, originalTeacherId: occurrence.timetable.teacherId, substituteTeacherId: input.substituteTeacherId, courseId: occurrence.timetable.courseId, batchId: occurrence.timetable.batchId, subjectId: occurrence.timetable.subjectId, reason: input.reason ?? null, approvedById: req.auth!.userId }, select: substitutionSelect }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") throw new AppError(409, "SUBSTITUTION_ALREADY_ASSIGNED", "This timetable occurrence already has an active substitution"); throw error; } await audit(req, "ASSIGN", "TeacherSubstitution", data.id, { timetableId: input.timetableId, substituteTeacherId: input.substituteTeacherId }); res.status(201).json({ data, meta: { warning: candidate.warning } }); });
router.patch("/substitutions/:id/status", async (req: AuthRequest, res) => { const substitutionId = id.parse(req.params.id), { status } = z.object({ status: z.enum([SubstitutionStatus.COMPLETED, SubstitutionStatus.CANCELLED]) }).parse(req.body), old = await prisma.teacherSubstitution.findUnique({ where: { id: substitutionId }, select: { id: true, branchId: true, status: true } }); if (!old) throw new AppError(404, "SUBSTITUTION_NOT_FOUND", "Substitution not found"); await access(req, old.branchId); if (old.status !== SubstitutionStatus.ASSIGNED) throw new AppError(409, "SUBSTITUTION_FINALIZED", "Only assigned substitutions can be completed or cancelled"); const data = await prisma.teacherSubstitution.update({ where: { id: substitutionId }, data: { status }, select: substitutionSelect }); await audit(req, status === SubstitutionStatus.CANCELLED ? "CANCEL" : "COMPLETE", "TeacherSubstitution", data.id); res.json({ data }); });

router.get("/teacher-duties", async (req: AuthRequest, res) => { const query = z.object({ branchId: id, teacherId: id.optional(), date: z.coerce.date().optional() }).parse(req.query); await access(req, query.branchId); const data = await prisma.teacherDuty.findMany({ where: { branchId: query.branchId, ...(query.teacherId ? { teacherId: query.teacherId } : {}), ...(query.date ? { date: utcDay(query.date) } : {}) }, include: { teacher: { select: { employeeNo: true, user: { select: { name: true } } } } }, orderBy: [{ date: "desc" }, { periodNumber: "asc" }] }); res.json({ data }); });
router.post("/teacher-duties", async (req: AuthRequest, res) => { const input = z.object({ branchId: id, academicSessionId: id, teacherId: id, date: z.coerce.date(), periodNumber: z.number().int().min(1).max(50), type: z.nativeEnum(TeacherDutyType), remarks: z.string().trim().max(2000).nullable().optional() }).parse(req.body); await access(req, input.branchId); const date = utcDay(input.date), day = timetableDay(date), [teacher, period] = await Promise.all([prisma.teacherProfile.findUnique({ where: { id: input.teacherId }, select: { branchId: true } }), prisma.timetablePeriod.findUnique({ where: { branchId_academicSessionId_day_periodNumber: { branchId: input.branchId, academicSessionId: input.academicSessionId, day, periodNumber: input.periodNumber } } })]); if (!teacher || teacher.branchId !== input.branchId || !period || !period.isActive || period.type !== TimetablePeriodType.TEACHING) throw new AppError(422, "INVALID_DUTY_CONTEXT", "Teacher and teaching period must match the selected branch and session"); if (await teacherOnApprovedLeave(input.teacherId, date)) throw new AppError(409, "TEACHER_ON_LEAVE", "Teacher is on approved leave"); const overlap = { startMinute: { lt: period.endMinute }, endMinute: { gt: period.startMinute } }, conflict = await Promise.all([prisma.timetable.findFirst({ where: { teacherId: input.teacherId, day, status: TimetableStatus.ACTIVE, ...overlap }, select: { id: true } }), prisma.teacherDuty.findFirst({ where: { teacherId: input.teacherId, date, ...overlap }, select: { id: true } }), prisma.teacherSubstitution.findFirst({ where: { substituteTeacherId: input.teacherId, date, status: { in: [SubstitutionStatus.ASSIGNED, SubstitutionStatus.COMPLETED] }, timetable: overlap }, select: { id: true } })]); if (conflict.some(Boolean)) throw new AppError(409, "TEACHER_SCHEDULE_CONFLICT", "Teacher already has an occupied timetable slot"); const data = await prisma.teacherDuty.create({ data: { ...input, date, startMinute: period.startMinute, endMinute: period.endMinute, remarks: input.remarks ?? null } }); await audit(req, "CREATE", "TeacherDuty", data.id, { teacherId: input.teacherId, type: input.type }); res.status(201).json({ data }); });
router.delete("/teacher-duties/:id", async (req: AuthRequest, res) => { const duty = await prisma.teacherDuty.findUnique({ where: { id: id.parse(req.params.id) }, select: { id: true, branchId: true } }); if (!duty) throw new AppError(404, "DUTY_NOT_FOUND", "Teacher duty not found"); await access(req, duty.branchId); await prisma.teacherDuty.delete({ where: { id: duty.id } }); await audit(req, "DELETE", "TeacherDuty", duty.id); res.status(204).send(); });

router.get("/academic-reports/workload", async (req: AuthRequest, res) => { const query = z.object({ branchId: id, academicSessionId: id, date: z.coerce.date() }).parse(req.query); await access(req, query.branchId); const teachers = await prisma.teacherProfile.findMany({ where: { branchId: query.branchId, user: { isActive: true } }, select: { id: true, employeeNo: true, user: { select: { name: true } }, maxPeriodsPerWeek: true } }), data = await Promise.all(teachers.map(async teacher => { const workload = await weeklyWorkload(teacher.id, query.branchId, query.academicSessionId, query.date); return { ...teacher, ...workload.totals, utilizationPercent: workload.totals.availablePeriods ? Math.round(workload.totals.totalOccupied * 100 / workload.totals.availablePeriods) : 0, overloaded: Boolean(teacher.maxPeriodsPerWeek && workload.totals.totalOccupied > teacher.maxPeriodsPerWeek) }; })); res.json({ data }); });
router.get("/academic-reports/summary", async (req: AuthRequest, res) => { const query = z.object({ branchId: id, academicSessionId: id }).parse(req.query); await access(req, query.branchId); const [subject, course, group, classroom, substitutions] = await Promise.all([prisma.teacherAllocation.groupBy({ by: ["subjectId"], where: { branchId: query.branchId, academicSessionId: query.academicSessionId, status: "ACTIVE" }, _sum: { weeklyPeriods: true }, _count: true }), prisma.teacherAllocation.groupBy({ by: ["courseId"], where: { branchId: query.branchId, academicSessionId: query.academicSessionId, status: "ACTIVE" }, _sum: { weeklyPeriods: true }, _count: true }), prisma.teacherAllocation.groupBy({ by: ["batchId"], where: { branchId: query.branchId, academicSessionId: query.academicSessionId, status: "ACTIVE" }, _sum: { weeklyPeriods: true }, _count: true }), prisma.timetable.groupBy({ by: ["classroomId"], where: { branchId: query.branchId, academicSessionId: query.academicSessionId, status: "ACTIVE" }, _count: true }), prisma.teacherSubstitution.groupBy({ by: ["substituteTeacherId"], where: { branchId: query.branchId, academicSessionId: query.academicSessionId, status: { in: [SubstitutionStatus.ASSIGNED, SubstitutionStatus.COMPLETED] } }, _count: true })]); res.json({ data: { subjectWorkload: subject, courseWorkload: course, groupWorkload: group, classroomUtilization: classroom, substitutionFrequency: substitutions } }); });

export default router;
