import { Gender, Role, StudentStatus } from "@prisma/client";
import bcrypt from "bcryptjs";
import { Router } from "express";
import { z } from "zod";
import { AppError } from "../lib/http.js";
import { prisma } from "../lib/prisma.js";
import { allow, requireAuth, type AuthRequest } from "../middleware/auth.js";

const router=Router();router.use(requireAuth,allow(Role.SUPER_ADMIN,Role.BRANCH_ADMIN));
const phone=z.string().trim().regex(/^\+?[0-9][0-9 -]{6,19}$/,"Enter a valid mobile number");
const input=z.object({admissionNo:z.string().trim().toUpperCase().min(3).max(40),rollNo:z.string().trim().toUpperCase().min(1).max(30),name:z.string().trim().min(2).max(100),gender:z.nativeEnum(Gender),dateOfBirth:z.coerce.date(),fatherName:z.string().trim().min(2).max(100),motherName:z.string().trim().min(2).max(100),mobile:phone,parentMobile:phone,email:z.string().trim().toLowerCase().email(),password:z.string().min(8).max(128).optional(),address:z.string().trim().min(5).max(1000),branchId:z.string().cuid(),batchId:z.string().cuid(),academicSession:z.string().trim().min(4).max(30),admissionDate:z.coerce.date(),bloodGroup:z.string().trim().max(10).nullable().optional(),category:z.string().trim().max(50).nullable().optional(),aadhaarNo:z.string().trim().regex(/^\d{12}$/,"Aadhaar number must contain 12 digits").nullable().optional(),photoUrl:z.string().url().nullable().optional(),status:z.nativeEnum(StudentStatus).default(StudentStatus.ACTIVE),remarks:z.string().trim().max(2000).nullable().optional()});
const select={id:true,admissionNo:true,rollNo:true,gender:true,dateOfBirth:true,fatherName:true,motherName:true,className:true,parentMobile:true,address:true,academicSession:true,admissionDate:true,bloodGroup:true,category:true,aadhaarNo:true,status:true,remarks:true,createdAt:true,updatedAt:true,user:{select:{id:true,name:true,email:true,phone:true,avatarUrl:true,isActive:true}},branch:{select:{id:true,branchName:true,branchCode:true}},batch:{select:{id:true,name:true,code:true,academicSession:true,capacity:true,course:{select:{id:true,title:true,courseCode:true}},_count:{select:{students:true}}}},_count:{select:{fees:true,testAttempts:true,certificates:true}}}as const;
async function branches(req:AuthRequest){if(req.auth!.role!==Role.BRANCH_ADMIN)return null;return(await prisma.branchUser.findMany({where:{userId:req.auth!.userId},select:{branchId:true}})).map(x=>x.branchId)}async function access(req:AuthRequest,id:string){const ids=await branches(req);if(ids&&!ids.includes(id))throw new AppError(403,"BRANCH_FORBIDDEN","Branch access denied")}
async function validateRelations(branchId:string,batchId:string,excludeId?:string){const batch=await prisma.batch.findUnique({where:{id:batchId},select:{id:true,branchId:true,capacity:true,_count:{select:{students:true}}}});if(!batch||batch.branchId!==branchId)throw new AppError(422,"INVALID_BATCH","Select a batch belonging to the selected branch");const already=excludeId?await prisma.studentProfile.count({where:{id:excludeId,batchId}}):0;if(batch._count.students-already>=batch.capacity)throw new AppError(409,"BATCH_CAPACITY_REACHED","The selected batch is at full capacity");return batch}
function duplicateError(error:any){const target=error?.meta?.target as string[]|undefined;if(error?.code!=="P2002")return null;if(target?.includes("admissionNo"))return new AppError(409,"ADMISSION_NO_EXISTS","Admission number already exists");if(target?.includes("rollNo"))return new AppError(409,"ROLL_NO_EXISTS","Roll number already exists in this batch");if(target?.includes("email"))return new AppError(409,"EMAIL_EXISTS","Email already exists");if(target?.includes("aadhaarNo"))return new AppError(409,"AADHAAR_EXISTS","Aadhaar number already exists");return new AppError(409,"DUPLICATE_STUDENT","A unique student value already exists")}
const shaped=(x:any)=>({...x,branch:{...x.branch,name:x.branch.branchName,code:x.branch.branchCode},course:x.batch.course,currentStrength:x.batch._count.students});
router.get("/students",async(req:AuthRequest,res)=>{const q=z.object({page:z.coerce.number().int().positive().default(1),limit:z.coerce.number().int().min(1).max(100).default(10),search:z.string().trim().optional(),branchId:z.string().cuid().optional(),courseId:z.string().cuid().optional(),batchId:z.string().cuid().optional(),academicSession:z.string().trim().optional(),gender:z.nativeEnum(Gender).optional(),category:z.string().trim().optional(),status:z.nativeEnum(StudentStatus).optional(),sortBy:z.enum(["admissionNo","rollNo","name","admissionDate","dateOfBirth","status","createdAt"]).default("createdAt"),sortOrder:z.enum(["asc","desc"]).default("desc")}).parse(req.query),ids=await branches(req);if(q.branchId)await access(req,q.branchId);const where={...(ids?{branchId:{in:ids}}:{}),...(q.branchId?{branchId:q.branchId}:{}),...(q.batchId?{batchId:q.batchId}:{}),...(q.courseId?{batch:{courseId:q.courseId}}:{}),...(q.academicSession?{academicSession:q.academicSession}:{}),...(q.gender?{gender:q.gender}:{}),...(q.category?{category:q.category}:{}),...(q.status?{status:q.status}:{}),...(q.search?{OR:[{admissionNo:{contains:q.search,mode:"insensitive"as const}},{rollNo:{contains:q.search,mode:"insensitive"as const}},{fatherName:{contains:q.search,mode:"insensitive"as const}},{parentMobile:{contains:q.search,mode:"insensitive"as const}},{user:{name:{contains:q.search,mode:"insensitive"as const}}},{user:{email:{contains:q.search,mode:"insensitive"as const}}},{user:{phone:{contains:q.search,mode:"insensitive"as const}}}]}:{})};const orderBy=q.sortBy==="name"?{user:{name:q.sortOrder}}:{[q.sortBy]:q.sortOrder};const[total,data]=await prisma.$transaction([prisma.studentProfile.count({where}),prisma.studentProfile.findMany({where,select,skip:(q.page-1)*q.limit,take:q.limit,orderBy})]);res.json({data:data.map(shaped),meta:{total,page:q.page,limit:q.limit,totalPages:Math.max(1,Math.ceil(total/q.limit))}})});
router.get("/students/export",async(req:AuthRequest,res)=>{const format=z.enum(["excel","pdf"]).default("excel").parse(req.query.format),ids=await branches(req),data=await prisma.studentProfile.findMany({where:ids?{branchId:{in:ids}}:{},select,orderBy:{admissionNo:"asc"}});if(format==="pdf")return studentPdf(res,data.map(shaped));const rows=[["Admission No","Roll No","Name","Gender","Branch","Course","Batch","Session","Mobile","Parent Mobile","Email","Status"],...data.map((s:any)=>[s.admissionNo,s.rollNo,s.user.name,s.gender,s.branch.branchName,s.batch.course?.title??"",s.batch.name,s.academicSession,s.user.phone,s.parentMobile,s.user.email,s.status])];const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Students"><Table>${rows.map(r=>`<Row>${r.map(v=>`<Cell><Data ss:Type="String">${escapeXml(String(v??""))}</Data></Cell>`).join("")}</Row>`).join("")}</Table></Worksheet></Workbook>`;res.set({"Content-Type":"application/vnd.ms-excel","Content-Disposition":"attachment; filename=students.xls"}).send(xml)});
router.post("/students/import",async(req:AuthRequest,res)=>{const rows=z.array(input.extend({password:z.string().min(8).max(128).default("Student@123")})).min(1).max(500).parse(req.body.rows),created=[] as any[],errors=[] as any[];for(let i=0;i<rows.length;i++){try{await access(req,rows[i].branchId);created.push(await create(rows[i]))}catch(e:any){errors.push({row:i+2,message:e instanceof AppError?e.message:duplicateError(e)?.message??e.message})}}res.status(errors.length?207:201).json({data:{created:created.map(shaped),createdCount:created.length,errorCount:errors.length,errors}})});
router.get("/students/:id",async(req:AuthRequest,res)=>{const data=await prisma.studentProfile.findUnique({where:{id:String(req.params.id)},select});if(!data)throw new AppError(404,"STUDENT_NOT_FOUND","Student not found");await access(req,data.branch.id);res.json({data:shaped(data)})});
async function create(data:z.infer<typeof input>&{password?:string}){await validateRelations(data.branchId,data.batchId);if(!data.password)throw new AppError(422,"PASSWORD_REQUIRED","Password is required");try{return await prisma.$transaction(async tx=>{const user=await tx.user.create({data:{name:data.name,email:data.email,phone:data.mobile,avatarUrl:data.photoUrl??null,passwordHash:await bcrypt.hash(data.password!,12),role:Role.STUDENT,isActive:data.status===StudentStatus.ACTIVE}});return tx.studentProfile.create({data:{userId:user.id,admissionNo:data.admissionNo,rollNo:data.rollNo,gender:data.gender,dateOfBirth:data.dateOfBirth,fatherName:data.fatherName,motherName:data.motherName,className:data.batchId,parentMobile:data.parentMobile,address:data.address,branchId:data.branchId,batchId:data.batchId,academicSession:data.academicSession,admissionDate:data.admissionDate,bloodGroup:data.bloodGroup??null,category:data.category??null,aadhaarNo:data.aadhaarNo??null,status:data.status,remarks:data.remarks??null},select})})}catch(e){throw duplicateError(e)??e}}
router.post("/students",async(req:AuthRequest,res)=>{const data=input.extend({password:z.string().min(8).max(128)}).parse(req.body);await access(req,data.branchId);res.status(201).json({data:shaped(await create(data))})});
router.patch("/students/:id",async(req:AuthRequest,res)=>{const old=await prisma.studentProfile.findUnique({where:{id:String(req.params.id)},select:{id:true,userId:true,branchId:true,batchId:true,status:true}});if(!old)throw new AppError(404,"STUDENT_NOT_FOUND","Student not found");await access(req,old.branchId);const data=input.partial().parse(req.body),branchId=data.branchId??old.branchId,batchId=data.batchId??old.batchId;if(data.branchId)await access(req,data.branchId);if(data.batchId||data.branchId)await validateRelations(branchId,batchId,old.id);try{const result=await prisma.$transaction(async tx=>{await tx.user.update({where:{id:old.userId},data:{...(data.name?{name:data.name}:{}),...(data.email?{email:data.email}:{}),...(data.mobile?{phone:data.mobile}:{}),...(data.photoUrl!==undefined?{avatarUrl:data.photoUrl}:{}),...(data.password?{passwordHash:await bcrypt.hash(data.password,12)}:{}),...(data.status?{isActive:data.status===StudentStatus.ACTIVE}:{})}});const profile:any={...data};delete profile.name;delete profile.email;delete profile.mobile;delete profile.photoUrl;delete profile.password;if(data.batchId)profile.className=data.batchId;return tx.studentProfile.update({where:{id:old.id},data:profile,select})});res.json({data:shaped(result)})}catch(e){throw duplicateError(e)??e}});
router.patch("/students/:id/status",async(req:AuthRequest,res)=>{const{status}=z.object({status:z.nativeEnum(StudentStatus)}).parse(req.body),old=await prisma.studentProfile.findUnique({where:{id:String(req.params.id)},select:{id:true,userId:true,branchId:true}});if(!old)throw new AppError(404,"STUDENT_NOT_FOUND","Student not found");await access(req,old.branchId);const data=await prisma.$transaction(async tx=>{await tx.user.update({where:{id:old.userId},data:{isActive:status===StudentStatus.ACTIVE}});return tx.studentProfile.update({where:{id:old.id},data:{status},select})});res.json({data:shaped(data)})});
router.delete("/students/:id",async(req:AuthRequest,res)=>{const s=await prisma.studentProfile.findUnique({where:{id:String(req.params.id)},select:{id:true,userId:true,branchId:true,_count:{select:{fees:true,testAttempts:true,certificates:true}}}});if(!s)throw new AppError(404,"STUDENT_NOT_FOUND","Student not found");await access(req,s.branchId);const[attendance,exam,assignment]=await Promise.all([prisma.attendance.count({where:{studentId:s.userId}}),prisma.examAttempt.count({where:{studentId:s.userId}}),prisma.assignmentSubmission.count({where:{studentId:s.userId}})]);if(attendance||s._count.fees||s._count.certificates||s._count.testAttempts||exam||assignment)throw new AppError(409,"STUDENT_HAS_ACADEMIC_RECORDS","Archive this student; attendance, fee, certificate or exam data prevents deletion");await prisma.$transaction([prisma.studentProfile.delete({where:{id:s.id}}),prisma.user.delete({where:{id:s.userId}})]);res.status(204).send()});
function escapeXml(s:string){return s.replace(/[<>&'\"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"}[c]!))}function studentPdf(res:any,data:any[]){const lines=["BEING BRILLIANT ACADEMY - STUDENT DIRECTORY",...data.slice(0,45).map(s=>`${s.admissionNo} | ${s.rollNo} | ${s.user.name} | ${s.branch.name} | ${s.batch.name} | ${s.status}`)],content=lines.map((x,i)=>`BT /F1 ${i?9:16} Tf 35 ${800-i*16} Td (${x.replace(/[()\\]/g,"\\$&")}) Tj ET`).join("\n"),o=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`,"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"];let p="%PDF-1.4\n",a=[0];o.forEach((x,i)=>{a.push(Buffer.byteLength(p));p+=`${i+1} 0 obj\n${x}\nendobj\n`});const r=Buffer.byteLength(p);p+=`xref\n0 6\n0000000000 65535 f \n${a.slice(1).map(x=>String(x).padStart(10,"0")+" 00000 n ").join("\n")}\ntrailer << /Size 6 /Root 1 0 R >>\nstartxref\n${r}\n%%EOF`;res.set({"Content-Type":"application/pdf","Content-Disposition":"attachment; filename=students.pdf"}).send(Buffer.from(p))}export default router;
