import { Role } from "@prisma/client";
import bcrypt from "bcryptjs";
import crypto from "node:crypto";
import { Router } from "express";
import jwt from "jsonwebtoken";
import { z } from "zod";
import { env } from "../config.js";
import { AppError } from "../lib/http.js";
import { sendEmail } from "../lib/notifications.js";
import { prisma, systemPrisma } from "../lib/prisma.js";
import { requireAuth, type AuthRequest } from "../middleware/auth.js";
import { securePasswordSchema } from "../lib/password-policy.js";
import { tenantBrandFromOrganization } from "../lib/tenant-brand.js";
import { customDomainFromSettings, normalizeTenantHost, platformWebHost, tenantSlugFromHost } from "../lib/tenant-domain.js";

const router = Router();
const credentials = z.object({ email: z.string().trim().toLowerCase().email(), password: z.string().min(8).max(128), organization: z.string().trim().toLowerCase().min(2).max(100).optional() });
const signAccess = (user: { id: string; role: Role; organizationId: string }) => jwt.sign({ userId: user.id, role: user.role, organizationId: user.organizationId }, env.JWT_ACCESS_SECRET, { expiresIn: "15m" });
async function issueSession(user: { id: string; role: Role; organizationId: string }, rememberMe = false, absoluteExpiry?: Date) { const raw = crypto.randomBytes(48).toString("base64url"), expiresAt = absoluteExpiry ?? new Date(Date.now() + (rememberMe ? 30 : 7) * 864e5); await systemPrisma.session.create({ data: { organizationId: user.organizationId, userId: user.id, tokenHash: crypto.createHash("sha256").update(raw).digest("hex"), expiresAt } }); return { accessToken: signAccess(user), refreshToken: raw }; }
const publicUser = (user: { id: string; name: string; email: string; role: Role; organizationId: string }, billingRecovery = false) => ({ id: user.id, name: user.name, email: user.email, role: user.role, organizationId: user.organizationId, billingRecovery });
async function organization(slug?: string) { return slug ? systemPrisma.organization.findUnique({ where: { slug } }) : systemPrisma.organization.findUnique({ where: { id: "org_default" } }); }
function organizationBrandName(org:Awaited<ReturnType<typeof organization>>){if(!org)return "Your institution";const settings=org.settings&&typeof org.settings==="object"&&!Array.isArray(org.settings)?org.settings as Record<string,unknown>:{},whiteLabel=settings.whiteLabel&&typeof settings.whiteLabel==="object"&&!Array.isArray(settings.whiteLabel)?settings.whiteLabel as Record<string,unknown>:{};return typeof whiteLabel.appName==="string"&&whiteLabel.appName.trim()?whiteLabel.appName.trim():org.name}
function valid(org: Awaited<ReturnType<typeof organization>>) { const now = new Date(); return Boolean(org && org.isActive && !org.deletedAt && (org.subscriptionStatus === "ACTIVE" || org.subscriptionStatus === "TRIAL" && (!org.trialEndsAt || org.trialEndsAt > now)) && (!org.subscriptionEndsAt || org.subscriptionEndsAt > now)); }
function billingRecoveryEligible(org: Awaited<ReturnType<typeof organization>>, role: Role) { const now = new Date(); if (!org || !org.isActive || org.deletedAt || role !== Role.SUPER_ADMIN) return false; if (org.subscriptionStatus === "PAST_DUE") return true; if (org.subscriptionStatus === "ACTIVE" && org.subscriptionEndsAt && org.subscriptionEndsAt <= now) return true; return org.subscriptionStatus === "TRIAL" && Boolean(org.trialEndsAt && org.trialEndsAt <= now); }

async function assertRequestHostMatchesOrganization(req: { get(name: string): string | undefined }, org: NonNullable<Awaited<ReturnType<typeof organization>>>) {
  const host = normalizeTenantHost(req.get("origin") ?? req.get("host"));
  const platformHost = platformWebHost();
  if (!host || !platformHost || host === platformHost || host === `www.${platformHost}`) return;

  const subdomainSlug = tenantSlugFromHost(host);
  if (subdomainSlug) {
    if (subdomainSlug !== org.slug) throw new AppError(403, "WORKSPACE_HOST_MISMATCH", "This organization URL is assigned to a different workspace");
    return;
  }

  const configuredDomain = customDomainFromSettings(org.settings);
  if (configuredDomain === host) return;

  const owner = await systemPrisma.organization.findFirst({
    where: { isActive: true, deletedAt: null, settings: { path: ["whiteLabel", "customDomain"], equals: host } },
    select: { id: true },
  });
  if (owner && owner.id !== org.id) throw new AppError(403, "WORKSPACE_HOST_MISMATCH", "This organization URL is assigned to a different workspace");
}

router.post("/register", async () => { throw new AppError(403, "SELF_REGISTRATION_DISABLED", "Accounts are created by your institution. Use your account setup link or contact your administrator."); });
router.post("/login", async (req, res) => { const data = credentials.extend({ rememberMe: z.boolean().optional().default(false), portal: z.enum(["student", "parent", "teacher", "employee", "admin"]).optional() }).parse(req.body); const org = await organization(data.organization); if (!org || !org.isActive || org.deletedAt) throw new AppError(402, "SUBSCRIPTION_INACTIVE", "Organization is unavailable"); await assertRequestHostMatchesOrganization(req, org); const user = await systemPrisma.user.findFirst({ where: { organizationId: org.id, email: data.email } }); if (!user || !user.isActive || !await bcrypt.compare(data.password, user.passwordHash)) throw new AppError(401, "INVALID_CREDENTIALS", "Email or password is incorrect"); const billingRecovery = !valid(org) && billingRecoveryEligible(org, user.role); if (!valid(org) && !billingRecovery) throw new AppError(402, "SUBSCRIPTION_INACTIVE", "Organization is unavailable"); if (billingRecovery && data.portal && data.portal !== "admin") throw new AppError(402, "SUBSCRIPTION_INACTIVE", "Subscription renewal is required. Use the Admin Portal to access billing."); const portalRoles = { student: [Role.STUDENT], parent: [Role.PARENT], teacher: [Role.TEACHER], employee: [Role.EMPLOYEE], admin: [Role.SUPER_ADMIN, Role.BRANCH_ADMIN, Role.ACCOUNTANT] } as const; if (data.portal && !portalRoles[data.portal].includes(user.role as never)) throw new AppError(403, "WRONG_PORTAL", `This account cannot access the ${data.portal} portal`); if (user.role === Role.STUDENT && !await systemPrisma.studentProfile.findFirst({ where: { organizationId: org!.id, userId: user.id, status: "ACTIVE" } })) throw new AppError(403, "STUDENT_INACTIVE", "An active student enrollment is required"); if (user.role === Role.TEACHER && !await systemPrisma.teacherProfile.findFirst({ where: { organizationId: org!.id, userId: user.id } })) throw new AppError(403, "TEACHER_PROFILE_REQUIRED", "An active teacher profile is required"); if (user.role === Role.PARENT && !await systemPrisma.parentStudent.findFirst({ where: { organizationId: org!.id, parentId: user.id, student: { status: "ACTIVE", user: { isActive: true } } } })) throw new AppError(403, "CHILD_LINK_REQUIRED", "An active linked student is required"); if (user.role === Role.EMPLOYEE && !await systemPrisma.employee.findFirst({ where: { organizationId: org!.id, userId: user.id, status: { not: "ARCHIVED" } } })) throw new AppError(403, "EMPLOYEE_PROFILE_REQUIRED", "An active employee profile is required"); res.json({ data: { user: publicUser(user, billingRecovery), organization: { id: org.id, slug: org.slug, name: org.name, logoUrl: org.logoUrl, primaryColor: org.primaryColor }, ...await issueSession(user, data.rememberMe) } }); });
router.post("/change-password", requireAuth, async (req: AuthRequest, res) => { const data = z.object({ currentPassword: z.string().min(1), newPassword: securePasswordSchema }).parse(req.body); const user = await systemPrisma.user.findFirst({ where: { id: req.auth!.userId, organizationId: req.auth!.organizationId } }); if (!user || !await bcrypt.compare(data.currentPassword, user.passwordHash)) throw new AppError(400, "INVALID_PASSWORD", "Current password is incorrect"); await systemPrisma.$transaction([systemPrisma.user.update({ where: { id: user.id }, data: { passwordHash: await bcrypt.hash(data.newPassword, 12) } }), systemPrisma.session.deleteMany({ where: { userId: user.id, organizationId: user.organizationId } })]); res.status(204).end(); });
router.post("/refresh", async (req, res) => { const token = z.object({ refreshToken: z.string().min(20) }).parse(req.body).refreshToken; const hash = crypto.createHash("sha256").update(token).digest("hex"); const session = await systemPrisma.session.findUnique({ where: { tokenHash: hash }, include: { user: { include: { organization: true } } } }); const recovery = Boolean(session && billingRecoveryEligible(session.user.organization, session.user.role)); if (!session || session.expiresAt < new Date() || !session.user.isActive || session.organizationId !== session.user.organizationId || !valid(session.user.organization) && !recovery) throw new AppError(401, "INVALID_REFRESH", "Refresh token is invalid"); await systemPrisma.session.delete({ where: { id: session.id } }); res.json({ data: await issueSession(session.user, false, session.expiresAt) }); });
router.post("/logout", async (req, res) => { const token = z.object({ refreshToken: z.string() }).parse(req.body).refreshToken; await systemPrisma.session.deleteMany({ where: { tokenHash: crypto.createHash("sha256").update(token).digest("hex") } }); res.status(204).send(); });
router.post("/forgot-password", async (req, res) => { const { email, organization: slug } = z.object({ email: z.string().trim().toLowerCase().email(), organization: z.string().optional() }).parse(req.body); const org = await organization(slug); if (org) await assertRequestHostMatchesOrganization(req, org); const user = org ? await systemPrisma.user.findFirst({ where: { organizationId: org.id, email } }) : null; if (user) { const raw = crypto.randomBytes(32).toString("base64url"); await systemPrisma.passwordResetToken.deleteMany({ where: { userId: user.id, usedAt: null } }); await systemPrisma.passwordResetToken.create({ data: { organizationId: user.organizationId, userId: user.id, tokenHash: crypto.createHash("sha256").update(raw).digest("hex"), expiresAt: new Date(Date.now() + 3_600_000) } }); const portalBaseUrl = org ? tenantBrandFromOrganization(org).portalBaseUrl : env.WEB_URL.replace(/\/$/, ""); const sharedBaseUrl = env.WEB_URL.replace(/\/$/, ""); const primaryLink = `${portalBaseUrl}/reset-password?token=${encodeURIComponent(raw)}&workspace=${encodeURIComponent(org?.slug ?? "")}`; const fallbackLink = `${sharedBaseUrl}/reset-password?token=${encodeURIComponent(raw)}&workspace=${encodeURIComponent(org?.slug ?? "")}`; await sendEmail(user.email, `Reset your ${organizationBrandName(org)} password`, `Use this secure link within one hour to reset your password:\n\n${primaryLink}${primaryLink !== fallbackLink ? `\n\nIf your custom domain is still being activated, use this fallback link:\n\n${fallbackLink}` : ""}`).catch(() => undefined); } res.status(202).json({ data: { message: "If that account exists, a reset link has been sent." } }); });
router.post("/reset-password", async (req, res) => { const data = z.object({ token: z.string().min(20), password: securePasswordSchema }).parse(req.body); const tokenHash = crypto.createHash("sha256").update(data.token).digest("hex"); const reset = await systemPrisma.passwordResetToken.findUnique({ where: { tokenHash }, include: { user: true } }); if (!reset || reset.usedAt || reset.expiresAt < new Date() || reset.organizationId !== reset.user.organizationId) throw new AppError(400, "INVALID_RESET_TOKEN", "This reset link is invalid or expired"); await systemPrisma.$transaction([systemPrisma.user.update({ where: { id: reset.userId }, data: { passwordHash: await bcrypt.hash(data.password, 12), emailVerifiedAt: reset.user.emailVerifiedAt ?? new Date() } }), systemPrisma.passwordResetToken.update({ where: { id: reset.id }, data: { usedAt: new Date() } }), systemPrisma.session.deleteMany({ where: { userId: reset.userId, organizationId: reset.organizationId } })]); res.status(204).send(); });
router.get("/me", requireAuth, async (req: AuthRequest, res) => { const user = await prisma.user.findUniqueOrThrow({ where: { id: req.auth!.userId }, select: { id: true, name: true, email: true, phone: true, role: true, avatarUrl: true, organizationId: true, organization: { select: { id: true, slug: true, name: true, logoUrl: true, primaryColor: true, secondaryColor: true, subscriptionStatus: true } } } }); res.json({ data: { ...user, billingRecovery: Boolean(req.auth!.billingRecovery) } }); });
export default router;
