import { Role } from "@prisma/client";
import bcrypt from "bcryptjs";
import crypto from "node:crypto";
import { Router } from "express";
import jwt from "jsonwebtoken";
import { z } from "zod";
import { env } from "../config.js";
import { AppError } from "../lib/http.js";
import { sendEmail } from "../lib/notifications.js";
import { prisma, systemPrisma } from "../lib/prisma.js";
import { requireAuth, type AuthRequest } from "../middleware/auth.js";

const router = Router();
const credentials = z.object({ email: z.string().trim().toLowerCase().email(), password: z.string().min(8).max(128), organization: z.string().trim().toLowerCase().min(2).max(100).optional() });
const signAccess = (user: { id: string; role: Role; organizationId: string }) => jwt.sign({ userId: user.id, role: user.role, organizationId: user.organizationId }, env.JWT_ACCESS_SECRET, { expiresIn: "15m" });
async function issueSession(user: { id: string; role: Role; organizationId: string }, rememberMe = false) { const raw = crypto.randomBytes(48).toString("base64url"); await systemPrisma.session.create({ data: { organizationId: user.organizationId, userId: user.id, tokenHash: crypto.createHash("sha256").update(raw).digest("hex"), expiresAt: new Date(Date.now() + (rememberMe ? 30 : 7) * 864e5) } }); return { accessToken: signAccess(user), refreshToken: raw }; }
const publicUser = (user: { id: string; name: string; email: string; role: Role; organizationId: string }) => ({ id: user.id, name: user.name, email: user.email, role: user.role, organizationId: user.organizationId });
async function organization(slug?: string) { return slug ? systemPrisma.organization.findUnique({ where: { slug } }) : systemPrisma.organization.findUnique({ where: { id: "org_default" } }); }
function valid(org: Awaited<ReturnType<typeof organization>>) { const now = new Date(); return Boolean(org && org.isActive && !org.deletedAt && (org.subscriptionStatus === "ACTIVE" || org.subscriptionStatus === "TRIAL" && (!org.trialEndsAt || org.trialEndsAt > now)) && (!org.subscriptionEndsAt || org.subscriptionEndsAt > now)); }

router.post("/register", async (req, res) => { const data = credentials.extend({ name: z.string().trim().min(2).max(100), rememberMe: z.boolean().optional().default(false) }).parse(req.body); const org = await organization(data.organization); if (!valid(org)) throw new AppError(402, "SUBSCRIPTION_INACTIVE", "Organization is unavailable"); if (await systemPrisma.user.findFirst({ where: { organizationId: org!.id, email: data.email } })) throw new AppError(409, "EMAIL_EXISTS", "An account already uses this email"); const user = await systemPrisma.user.create({ data: { organizationId: org!.id, name: data.name, email: data.email, passwordHash: await bcrypt.hash(data.password, 12) } }); res.status(201).json({ data: { user: publicUser(user), organization: { id: org!.id, slug: org!.slug, name: org!.name }, ...await issueSession(user, data.rememberMe) } }); });
router.post("/login", async (req, res) => { const data = credentials.extend({ rememberMe: z.boolean().optional().default(false), portal: z.enum(["student", "parent", "teacher", "admin"]).optional() }).parse(req.body); const org = await organization(data.organization); if (!valid(org)) throw new AppError(402, "SUBSCRIPTION_INACTIVE", "Organization is unavailable"); const user = await systemPrisma.user.findFirst({ where: { organizationId: org!.id, email: data.email } }); if (!user || !user.isActive || !await bcrypt.compare(data.password, user.passwordHash)) throw new AppError(401, "INVALID_CREDENTIALS", "Email or password is incorrect"); const portalRoles = { student: [Role.STUDENT], parent: [Role.PARENT], teacher: [Role.TEACHER], admin: [Role.SUPER_ADMIN, Role.BRANCH_ADMIN] } as const; if (data.portal && !portalRoles[data.portal].includes(user.role as never)) throw new AppError(403, "WRONG_PORTAL", `This account cannot access the ${data.portal} portal`); res.json({ data: { user: publicUser(user), organization: { id: org!.id, slug: org!.slug, name: org!.name, logoUrl: org!.logoUrl, primaryColor: org!.primaryColor }, ...await issueSession(user, data.rememberMe) } }); });
router.post("/refresh", async (req, res) => { const token = z.object({ refreshToken: z.string().min(20) }).parse(req.body).refreshToken; const hash = crypto.createHash("sha256").update(token).digest("hex"); const session = await systemPrisma.session.findUnique({ where: { tokenHash: hash }, include: { user: { include: { organization: true } } } }); if (!session || session.expiresAt < new Date() || !session.user.isActive || session.organizationId !== session.user.organizationId || !valid(session.user.organization)) throw new AppError(401, "INVALID_REFRESH", "Refresh token is invalid"); await systemPrisma.session.delete({ where: { id: session.id } }); res.json({ data: await issueSession(session.user) }); });
router.post("/logout", async (req, res) => { const token = z.object({ refreshToken: z.string() }).parse(req.body).refreshToken; await systemPrisma.session.deleteMany({ where: { tokenHash: crypto.createHash("sha256").update(token).digest("hex") } }); res.status(204).send(); });
router.post("/forgot-password", async (req, res) => { const { email, organization: slug } = z.object({ email: z.string().trim().toLowerCase().email(), organization: z.string().optional() }).parse(req.body); const org = await organization(slug); const user = org ? await systemPrisma.user.findFirst({ where: { organizationId: org.id, email } }) : null; if (user) { const raw = crypto.randomBytes(32).toString("base64url"); await systemPrisma.passwordResetToken.deleteMany({ where: { userId: user.id, usedAt: null } }); await systemPrisma.passwordResetToken.create({ data: { organizationId: user.organizationId, userId: user.id, tokenHash: crypto.createHash("sha256").update(raw).digest("hex"), expiresAt: new Date(Date.now() + 3_600_000) } }); await sendEmail(user.email, "Reset your Being Brilliant Academy password", `Use this secure link within one hour to reset your password:\n\n${env.WEB_URL}/reset-password?token=${encodeURIComponent(raw)}`).catch(() => undefined); } res.status(202).json({ data: { message: "If that account exists, a reset link has been sent." } }); });
router.post("/reset-password", async (req, res) => { const data = z.object({ token: z.string().min(20), password: z.string().min(8).max(128) }).parse(req.body); const tokenHash = crypto.createHash("sha256").update(data.token).digest("hex"); const reset = await systemPrisma.passwordResetToken.findUnique({ where: { tokenHash }, include: { user: true } }); if (!reset || reset.usedAt || reset.expiresAt < new Date() || reset.organizationId !== reset.user.organizationId) throw new AppError(400, "INVALID_RESET_TOKEN", "This reset link is invalid or expired"); await systemPrisma.$transaction([systemPrisma.user.update({ where: { id: reset.userId }, data: { passwordHash: await bcrypt.hash(data.password, 12) } }), systemPrisma.passwordResetToken.update({ where: { id: reset.id }, data: { usedAt: new Date() } }), systemPrisma.session.deleteMany({ where: { userId: reset.userId } })]); res.status(204).send(); });
router.get("/me", requireAuth, async (req: AuthRequest, res) => { const user = await prisma.user.findUniqueOrThrow({ where: { id: req.auth!.userId }, select: { id: true, name: true, email: true, phone: true, role: true, avatarUrl: true, organizationId: true, organization: { select: { id: true, slug: true, name: true, logoUrl: true, primaryColor: true, secondaryColor: true, subscriptionStatus: true } } } }); res.json({ data: user }); });
export default router;
