import { AnswerSheetStatus, Role } from "@prisma/client";
import { Router } from "express";
import { z } from "zod";
import { AppError } from "../lib/http.js";
import { assertAnswerSheetAccess, assertEvaluationOpen, assertExaminationManager, assertStudentExaminationEligible, assertStudentExaminationPublished, evaluationStatus, examinationResultFor } from "../lib/examination-policy.js";
import { prisma } from "../lib/prisma.js";
import { allowedAnswerSheetTypes, allowedDocumentTypes, assertDocumentFileExtension, decodeVerifiedUpload, type AllowedDocumentType } from "../lib/secure-upload.js";
import { requireAuth, type AuthRequest } from "../middleware/auth.js";

const router = Router();
router.use(requireAuth);
const id = z.string().cuid();
const uploadFields = { fileName: z.string().trim().min(1).max(180), base64: z.string().min(1), remarks: z.string().trim().max(2000).optional() } as const;
const questionPaperUpload = z.object({ ...uploadFields, mimeType: z.enum(allowedDocumentTypes) });
const answerSheetUpload = z.object({ ...uploadFields, mimeType: z.enum(allowedAnswerSheetTypes) });
const adminRoles: Role[] = [Role.SUPER_ADMIN, Role.BRANCH_ADMIN];
const managementRoles: Role[] = [...adminRoles, Role.TEACHER];
function bytes(data: { fileName: string; mimeType: AllowedDocumentType; base64: string }) { assertDocumentFileExtension(data.fileName, data.mimeType); const fileData = decodeVerifiedUpload(data.base64, data.mimeType); return { fileName: data.fileName, mimeType: data.mimeType, fileSize: fileData.length, fileData }; }
async function branchAccess(req: AuthRequest, branchId: string) { if (req.auth!.role !== Role.BRANCH_ADMIN) return; const found = await prisma.branchUser.findFirst({ where: { userId: req.auth!.userId, branchId }, select: { branchId: true } }); if (!found) throw new AppError(403, "BRANCH_FORBIDDEN", "Branch access denied"); }
async function examination(req: AuthRequest, examinationId: string) { const exam = await prisma.examination.findUnique({ where: { id: examinationId }, include: { teacher: { select: { userId: true } }, questionPaper: { select: { id: true, publishedAt: true, _count: { select: { answerSheets: true } } } } } }); if (!exam) throw new AppError(404, "EXAMINATION_NOT_FOUND", "Examination not found"); await branchAccess(req, exam.branchId); return exam; }
function mayManage(req: AuthRequest, exam: { teacher: { userId: string } }) { assertExaminationManager(req.auth!.role, req.auth!.userId, exam.teacher.userId); }
async function audit(req: AuthRequest, action: string, entity: string, entityId: string) { await prisma.auditLog.create({ data: { actorId: req.auth!.userId, action, entity, entityId } }); }
function examEnd(exam: { examDate: Date; endMinute: number }) { const value = new Date(exam.examDate); value.setUTCHours(Math.floor(exam.endMinute / 60), exam.endMinute % 60, 0, 0); return value; }

router.put("/examinations/:examinationId/question-paper", async (req: AuthRequest, res) => { const exam = await examination(req, id.parse(req.params.examinationId)); mayManage(req, exam); if (exam.questionPaper?._count.answerSheets) throw new AppError(409, "QUESTION_PAPER_IN_USE", "Question papers with submitted answer sheets cannot be replaced"); const data = questionPaperUpload.extend({ publishedAt: z.coerce.date().nullable().optional() }).parse(req.body); const paper = await prisma.examinationQuestionPaper.upsert({ where: { examinationId: exam.id }, update: { ...bytes(data), uploadedById: req.auth!.userId, publishedAt: data.publishedAt }, create: { organizationId: req.auth!.organizationId, examinationId: exam.id, uploadedById: req.auth!.userId, ...bytes(data), publishedAt: data.publishedAt } }); await audit(req, exam.questionPaper ? "REPLACE" : "UPLOAD", "ExaminationQuestionPaper", paper.id); res.status(exam.questionPaper ? 200 : 201).json({ data: { ...paper, fileData: undefined } }); });
router.get("/examinations/:examinationId/question-paper", async (req: AuthRequest, res) => { const exam = await examination(req, id.parse(req.params.examinationId)); if (req.auth!.role === Role.STUDENT) { const student = await prisma.studentProfile.findUnique({ where: { userId: req.auth!.userId }, select: { batchId: true, academicSessionId: true } }); assertStudentExaminationEligible(student, exam); assertStudentExaminationPublished(exam.status); if (!exam.questionPaper?.publishedAt || exam.questionPaper.publishedAt > new Date()) throw new AppError(403, "QUESTION_PAPER_UNPUBLISHED", "Question paper is not available yet"); } else mayManage(req, exam); const paper = await prisma.examinationQuestionPaper.findUnique({ where: { examinationId: exam.id } }); if (!paper) throw new AppError(404, "QUESTION_PAPER_NOT_FOUND", "Question paper not found"); res.set({ "Content-Type": paper.mimeType, "Content-Length": String(paper.fileSize), "Content-Disposition": `inline; filename="${paper.fileName.replace(/["\r\n]/g, "")}"` }).send(paper.fileData); });
router.delete("/examinations/:examinationId/question-paper", async (req: AuthRequest, res) => { const exam = await examination(req, id.parse(req.params.examinationId)); mayManage(req, exam); if (!exam.questionPaper) throw new AppError(404, "QUESTION_PAPER_NOT_FOUND", "Question paper not found"); if (exam.questionPaper._count.answerSheets) throw new AppError(409, "QUESTION_PAPER_IN_USE", "Question papers with submitted answer sheets cannot be removed"); await prisma.$transaction(async tx => { await tx.examinationQuestionPaper.delete({ where: { id: exam.questionPaper!.id } }); await tx.auditLog.create({ data: { organizationId: req.auth!.organizationId, actorId: req.auth!.userId, action: "REMOVE", entity: "ExaminationQuestionPaper", entityId: exam.questionPaper!.id } }); }); res.status(204).send(); });

router.put("/examinations/:examinationId/answer-sheet", async (req: AuthRequest, res) => { if (req.auth!.role !== Role.STUDENT) throw new AppError(403, "STUDENT_REQUIRED", "Student access is required"); const exam = await examination(req, id.parse(req.params.examinationId)); const student = await prisma.studentProfile.findUnique({ where: { userId: req.auth!.userId }, select: { id: true, batchId: true, academicSessionId: true } }); assertStudentExaminationEligible(student, exam); const now = new Date(); if (!["SCHEDULED", "COMPLETED"].includes(exam.status) || !exam.questionPaper?.publishedAt || exam.questionPaper.publishedAt > now) throw new AppError(409, "SUBMISSION_UNAVAILABLE", "Answer submission is not available for this examination"); const old = await prisma.examinationAnswerSheet.findUnique({ where: { examinationId_studentId: { examinationId: exam.id, studentId: student.id } } }); if (old?.finalizedAt) throw new AppError(409, "SUBMISSION_FINALIZED", "A finalized answer sheet cannot be replaced"); const data = answerSheetUpload.parse(req.body), isLate = now > examEnd(exam), status = isLate ? AnswerSheetStatus.LATE_SUBMITTED : AnswerSheetStatus.SUBMITTED; const sheet = await prisma.examinationAnswerSheet.upsert({ where: { examinationId_studentId: { examinationId: exam.id, studentId: student.id } }, update: { ...bytes(data), studentRemarks: data.remarks, status, isLate, submittedAt: now }, create: { organizationId: req.auth!.organizationId, examinationId: exam.id, questionPaperId: exam.questionPaper.id, studentId: student.id, ...bytes(data), studentRemarks: data.remarks, status, isLate, submittedAt: now } }); await audit(req, old ? "REPLACE" : "SUBMIT", "ExaminationAnswerSheet", sheet.id); res.status(old ? 200 : 201).json({ data: { ...sheet, fileData: undefined } }); });
router.get("/examinations/:examinationId/answer-sheets", async (req: AuthRequest, res) => { const exam = await examination(req, id.parse(req.params.examinationId)); mayManage(req, exam); const data = await prisma.examinationAnswerSheet.findMany({ where: { examinationId: exam.id }, select: { id: true, fileName: true, mimeType: true, fileSize: true, studentRemarks: true, status: true, isLate: true, marksObtained: true, teacherRemarks: true, internalNotes: true, evaluatedAt: true, finalizedAt: true, submittedAt: true, student: { select: { id: true, admissionNo: true, rollNo: true, user: { select: { name: true } } } } }, orderBy: { submittedAt: "asc" } }); res.json({ data }); });
router.get("/answer-sheets/:answerSheetId/file", async (req: AuthRequest, res) => { const sheet = await prisma.examinationAnswerSheet.findUnique({ where: { id: id.parse(req.params.answerSheetId) }, include: { examination: { include: { teacher: { select: { userId: true } } } }, student: { select: { userId: true } } } }); if (!sheet) throw new AppError(404, "ANSWER_SHEET_NOT_FOUND", "Answer sheet not found"); await branchAccess(req, sheet.examination.branchId); assertAnswerSheetAccess(req.auth!.role, req.auth!.userId, sheet.student.userId, sheet.examination.teacher.userId); res.set({ "Content-Type": sheet.mimeType, "Content-Length": String(sheet.fileSize), "Content-Disposition": `inline; filename="${sheet.fileName.replace(/["\r\n]/g, "")}"` }).send(sheet.fileData); });
router.patch("/answer-sheets/:answerSheetId/evaluation", async (req: AuthRequest, res) => { const sheet = await prisma.examinationAnswerSheet.findUnique({ where: { id: id.parse(req.params.answerSheetId) }, include: { examination: { include: { teacher: { select: { userId: true } } } } } }); if (!sheet) throw new AppError(404, "ANSWER_SHEET_NOT_FOUND", "Answer sheet not found"); await branchAccess(req, sheet.examination.branchId); mayManage(req, sheet.examination); assertEvaluationOpen(sheet.finalizedAt); const data = z.object({ marksObtained: z.coerce.number().min(0), teacherRemarks: z.string().trim().max(5000).nullable().optional(), internalNotes: z.string().trim().max(5000).nullable().optional(), finalize: z.boolean().default(false) }).parse(req.body); if (data.marksObtained > sheet.examination.maximumMarks) throw new AppError(422, "MARKS_EXCEED_MAXIMUM", "Marks cannot exceed examination maximum marks"); const now = new Date(), updated = await prisma.$transaction(async tx => { const answer = await tx.examinationAnswerSheet.updateMany({ where: { id: sheet.id, finalizedAt: null }, data: { marksObtained: data.marksObtained, teacherRemarks: data.teacherRemarks, internalNotes: data.internalNotes, evaluatedById: req.auth!.userId, evaluatedAt: now, status: evaluationStatus(data.finalize), ...(data.finalize ? { finalizedAt: now } : {}) } }); if (answer.count !== 1) throw new AppError(409, "EVALUATION_FINALIZED", "A finalized evaluation cannot be modified"); if (data.finalize) { const result = examinationResultFor(data.marksObtained, sheet.examination.maximumMarks, sheet.examination.passingMarks, now); await tx.examinationResult.upsert({ where: { examinationId_studentId: { examinationId: sheet.examinationId, studentId: sheet.studentId } }, update: { ...result, remarks: data.teacherRemarks }, create: { examinationId: sheet.examinationId, studentId: sheet.studentId, ...result, remarks: data.teacherRemarks } }); } return tx.examinationAnswerSheet.findUniqueOrThrow({ where: { id: sheet.id } }); }); await audit(req, data.finalize ? "FINALIZE" : "EVALUATE", "ExaminationAnswerSheet", updated.id); res.json({ data: { ...updated, fileData: undefined } }); });

router.get("/examinations", async (req: AuthRequest, res) => {
  if (req.auth!.role === Role.STUDENT) {
    const student = await prisma.studentProfile.findUnique({ where: { userId: req.auth!.userId }, select: { id: true, batchId: true, academicSessionId: true } });
    if (!student) throw new AppError(404, "STUDENT_PROFILE_NOT_FOUND", "Student profile not found");
    const data = await prisma.examination.findMany({ where: { batchId: student.batchId, academicSessionId: student.academicSessionId, status: { in: ["SCHEDULED", "COMPLETED", "RESULTS_PUBLISHED"] } }, select: { id: true, name: true, examDate: true, startMinute: true, endMinute: true, maximumMarks: true, subject: { select: { name: true } }, questionPaper: { select: { id: true, fileName: true, publishedAt: true } }, answerSheets: { where: { studentId: student.id }, select: { id: true, fileName: true, status: true, isLate: true, marksObtained: true, teacherRemarks: true, submittedAt: true, finalizedAt: true } } }, orderBy: { examDate: "desc" } });
    return res.json({ data: data.map(row => ({ ...row, questionPaper: row.questionPaper?.publishedAt && row.questionPaper.publishedAt <= new Date() ? row.questionPaper : null, answerSheet: row.answerSheets[0] ?? null, answerSheets: undefined })) });
  }
  if (!managementRoles.includes(req.auth!.role)) throw new AppError(403, "FORBIDDEN", "Examination access denied");
  const teacher = req.auth!.role === Role.TEACHER ? await prisma.teacherProfile.findUnique({ where: { userId: req.auth!.userId }, select: { id: true } }) : null;
  const branchIds = req.auth!.role === Role.BRANCH_ADMIN ? (await prisma.branchUser.findMany({ where: { userId: req.auth!.userId }, select: { branchId: true } })).map(row => row.branchId) : null;
  const data = await prisma.examination.findMany({ where: { ...(teacher ? { teacherId: teacher.id } : {}), ...(branchIds ? { branchId: { in: branchIds } } : {}) }, select: { id: true, name: true, examDate: true, maximumMarks: true, batch: { select: { name: true } }, subject: { select: { name: true } }, questionPaper: { select: { id: true, fileName: true, publishedAt: true } }, _count: { select: { answerSheets: true } } }, orderBy: { examDate: "desc" }, take: 100 });
  res.json({ data });
});

export default router;
