import { Role } from "@prisma/client";
import { Router } from "express";
import { z } from "zod";
import { AppError } from "../lib/http.js";
import { requireRequestedBranch } from "../lib/branch-policy.js";
import { prisma } from "../lib/prisma.js";
import { requireAuth, type AuthRequest } from "../middleware/auth.js";
const router=Router();router.use(requireAuth);const admins:Role[]=[Role.SUPER_ADMIN,Role.BRANCH_ADMIN];const id=z.string().cuid();const day=(date:Date)=>new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()));async function allowed(req:AuthRequest,branchId:string){if(!admins.includes(req.auth!.role))throw new AppError(403,"ADMIN_REQUIRED","Administrator access is required");if(req.auth!.role===Role.BRANCH_ADMIN&&!await prisma.branchUser.findFirst({where:{userId:req.auth!.userId,branchId}}))throw new AppError(403,"BRANCH_FORBIDDEN","Branch access denied")}
router.get("/admin/fee-defaulters",async(req:AuthRequest,res)=>{if(!admins.includes(req.auth!.role))throw new AppError(403,"ADMIN_REQUIRED","Administrator access is required");const q=z.object({page:z.coerce.number().int().positive().default(1),limit:z.coerce.number().int().min(1).max(100).default(20),branchId:id.optional(),batchId:id.optional(),search:z.string().trim().optional()}).parse(req.query),branchIds=req.auth!.role===Role.BRANCH_ADMIN?(await prisma.branchUser.findMany({where:{userId:req.auth!.userId},select:{branchId:true}})).map(x=>x.branchId):[],branchFilter=requireRequestedBranch(req.auth!.role,branchIds,q.branchId),where={dueDate:{lt:day(new Date())},status:{in:["PENDING"as const,"PARTIAL"as const,"OVERDUE"as const]},...branchFilter,...(q.batchId?{batchId:q.batchId}:{}),...(q.search?{OR:[{student:{user:{name:{contains:q.search,mode:"insensitive"as const}}}},{student:{admissionNo:{contains:q.search,mode:"insensitive"as const}}}]}:{})};const[rows]=await prisma.$transaction([prisma.fee.findMany({where,include:{student:{include:{user:{select:{id:true,name:true,email:true,phone:true}},parents:{include:{parent:{select:{id:true,name:true,email:true,phone:true}}}}}},branch:{select:{branchName:true}},batch:{select:{name:true}},course:{select:{title:true}}},orderBy:{dueDate:"asc"}})]);const eligible=rows.filter(fee=>fee.totalPaise-fee.discountPaise+fee.finePaise-fee.amountPaidPaise>0),total=eligible.length,data=eligible.slice((q.page-1)*q.limit,q.page*q.limit),ids=data.map(x=>x.id),last=await prisma.notification.findMany({where:{sourceModule:"FEE_REMINDER",sourceEntityId:{in:ids}},select:{sourceEntityId:true,createdAt:true},orderBy:{createdAt:"desc"}}),lastBy=new Map<string,Date>();for(const row of last)if(row.sourceEntityId&&!lastBy.has(row.sourceEntityId))lastBy.set(row.sourceEntityId,row.createdAt);res.json({data:data.map(fee=>({...fee,balancePaise:fee.totalPaise-fee.discountPaise+fee.finePaise-fee.amountPaidPaise,daysOverdue:Math.floor((day(new Date()).getTime()-day(fee.dueDate).getTime())/86400000),lastReminderAt:lastBy.get(fee.id)??null})),meta:{total,page:q.page,limit:q.limit,totalPages:Math.max(1,Math.ceil(total/q.limit))}})});
router.post("/admin/fee-defaulters/:feeId/remind",async(req:AuthRequest,res)=>{const fee=await prisma.fee.findUnique({where:{id:id.parse(req.params.feeId)},include:{student:{include:{user:true,parents:{include:{parent:true}}}}}});if(!fee)throw new AppError(404,"FEE_NOT_FOUND","Fee record not found");await allowed(req,fee.branchId);const balance=fee.totalPaise-fee.discountPaise+fee.finePaise-fee.amountPaidPaise;if(balance<=0||day(fee.dueDate)>=day(new Date()))throw new AppError(409,"FEE_NOT_OVERDUE","This fee has no overdue balance");const recent=await prisma.notification.findFirst({where:{sourceModule:"FEE_REMINDER",sourceEntityId:fee.id,createdAt:{gte:new Date(Date.now()-7*86400000)}}});if(recent)throw new AppError(429,"REMINDER_COOLDOWN","A reminder was already sent for this fee within seven days");const recipients=[fee.student.user,...fee.student.parents.map(x=>x.parent)].filter((user,index,all)=>all.findIndex(x=>x.id===user.id)===index),title=`Fee payment overdue: ${fee.feeHead}`,message=`An outstanding balance of ₹${(balance/100).toLocaleString("en-IN")} was due on ${fee.dueDate.toISOString().slice(0,10)}. Please contact the institution if payment has already been made.`;const notifications=await prisma.$transaction(recipients.map(user=>prisma.notification.create({data:{userId:user.id,title,body:message,category:"FEES",sourceModule:"FEE_REMINDER",sourceEntityId:fee.id,actionUrl:"/portal",priority:"HIGH",channels:["IN_APP"]}})));await prisma.auditLog.create({data:{actorId:req.auth!.userId,action:"FEE_REMINDER_SENT",entity:"Fee",entityId:fee.id,metadata:{recipientCount:recipients.length,balancePaise:balance}}});res.status(201).json({data:{notifications:notifications.length,channels:["IN_APP"]}})});export default router;
