import { AccountType, FinanceApprovalStatus, JournalStatus, Prisma, Role, VoucherType } from "@prisma/client";
import { Router } from "express";
import { z } from "zod";
import { requireRequestedBranch } from "../lib/branch-policy.js";
import { assertFinanceBranchAccess, assertRelatedBranch, assertSystemAccountCreationAllowed, assertVoucherCanTransition, assertVoucherTransitionApplied, canReadFinanceMasterData, isSerializableConflict, safeFinanceAuditMetadata } from "../lib/finance-integrity.js";
import { AppError } from "../lib/http.js";
import { prisma } from "../lib/prisma.js";
import { allow, requireAuth, type AuthRequest } from "../middleware/auth.js";

const router = Router();
router.use(requireAuth, allow(Role.SUPER_ADMIN, Role.BRANCH_ADMIN));
const id = (req: AuthRequest) => req.auth!.userId;
const date = (value: Date) => new Date(Date.UTC(value.getUTCFullYear(), value.getUTCMonth(), value.getUTCDate()));
const page = z.object({ page: z.coerce.number().int().positive().default(1), limit: z.coerce.number().int().min(1).max(100).default(20), search: z.string().trim().optional(), sortOrder: z.enum(["asc", "desc"]).default("desc") });
async function scope(req: AuthRequest) { return req.auth!.role === Role.BRANCH_ADMIN ? (await prisma.branchUser.findMany({ where: { userId: id(req) }, select: { branchId: true } })).map(item => item.branchId) : null; }
async function branchWhere(req: AuthRequest, requested?: string) { return requireRequestedBranch(req.auth!.role, (await scope(req)) ?? [], requested); }
async function access(req: AuthRequest, branchId: string) { assertFinanceBranchAccess(req.auth!.role, (await scope(req)) ?? [], branchId); }
const auditData = (req: AuthRequest, action: string, entity: string, entityId?: string, metadata?: object) => ({ organizationId: req.auth!.organizationId, actorId: id(req), action, entity, entityId, metadata: metadata ? safeFinanceAuditMetadata(metadata) : undefined });
async function audit(db: Prisma.TransactionClient | typeof prisma, req: AuthRequest, action: string, entity: string, entityId?: string, metadata?: object) { await db.auditLog.create({ data: auditData(req, action, entity, entityId, metadata) }); }
async function serializable<T>(work: (tx: Prisma.TransactionClient) => Promise<T>) { try { return await prisma.$transaction(work, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); } catch (error) { if (isSerializableConflict(error)) throw new AppError(409, "FINANCE_CONFLICT", "The finance record changed; reload and try again"); throw error; } }
const json = (value: any): any => typeof value === "bigint" ? Number(value) : Array.isArray(value) ? value.map(json) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).map(([key, item]) => [key, json(item)])) : value;
const entryInclude = { branch: { select: { id: true, branchName: true, branchCode: true } }, financialYear: true, createdBy: { select: { id: true, name: true, email: true } }, lines: { include: { account: { select: { id: true, code: true, name: true, type: true } } } } } as const;
const lines = z.array(z.object({ accountId: z.string().cuid(), debitPaise: z.number().int().min(0).default(0), creditPaise: z.number().int().min(0).default(0), description: z.string().max(500).optional() })).min(2);
const entryInput = z.object({ branchId: z.string().cuid(), financialYearId: z.string().cuid(), voucherNumber: z.string().trim().min(2).max(50), type: z.nativeEnum(VoucherType), date: z.coerce.date(), narration: z.string().trim().min(2).max(5000), reference: z.string().max(100).optional(), sourceType: z.string().max(50).optional(), sourceId: z.string().max(100).optional(), status: z.enum([JournalStatus.DRAFT, JournalStatus.POSTED]).default(JournalStatus.DRAFT), lines });
function balanced(items: z.infer<typeof lines>) { for (const item of items) if ((item.debitPaise > 0) === (item.creditPaise > 0)) throw new AppError(422, "INVALID_JOURNAL_LINE", "Each line must contain either a debit or a credit"); const debit = items.reduce((sum, item) => sum + item.debitPaise, 0), credit = items.reduce((sum, item) => sum + item.creditPaise, 0); if (!debit || debit !== credit) throw new AppError(422, "UNBALANCED_ENTRY", "Total debit must equal total credit"); return debit; }
async function yearCheck(db: Prisma.TransactionClient | typeof prisma, input: { branchId: string; financialYearId: string; date: Date }) { const year = await db.financialYear.findFirst({ where: { id: input.financialYearId, branchId: input.branchId } }); if (!year || input.date < year.startsAt || input.date > year.endsAt) throw new AppError(422, "INVALID_FINANCIAL_YEAR", "Voucher date must fall within its financial year"); if (year.isLocked) throw new AppError(409, "FINANCIAL_YEAR_LOCKED", "Financial year is locked"); return year; }
async function activeAccounts(db: Prisma.TransactionClient | typeof prisma, branchId: string, accountIds: string[]) { const uniqueIds = [...new Set(accountIds)]; const accounts = await db.ledgerAccount.findMany({ where: { id: { in: uniqueIds }, branchId, isArchived: false }, select: { id: true, branchId: true, type: true } }); if (accounts.length !== uniqueIds.length) throw new AppError(422, "INVALID_ACCOUNT", "Every account must be active and belong to the transaction branch"); return accounts; }
async function transitionVoucher(req: AuthRequest, entryId: string, nextStatus: "POSTED" | "ARCHIVED") {
  const permittedBranchIds = (await scope(req)) ?? [];
  return serializable(async tx => {
    const entry = await tx.journalEntry.findUnique({ where: { id: entryId }, include: { financialYear: true, lines: true } });
    if (!entry) throw new AppError(404, "NOT_FOUND", "Voucher not found");
    assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, entry.branchId);
    assertVoucherCanTransition(entry.status, entry.financialYear.isLocked);
    const totalPaise = nextStatus === JournalStatus.POSTED
      ? balanced(entry.lines.map(line => ({ accountId: line.accountId, debitPaise: Number(line.debitPaise), creditPaise: Number(line.creditPaise), description: line.description ?? undefined })))
      : undefined;
    if (nextStatus === JournalStatus.POSTED) await activeAccounts(tx, entry.branchId, entry.lines.map(line => line.accountId));
    const transition = await tx.journalEntry.updateMany({ where: { id: entry.id, status: JournalStatus.DRAFT }, data: { status: nextStatus, ...(nextStatus === JournalStatus.POSTED ? { postedAt: new Date() } : {}) } });
    assertVoucherTransitionApplied(transition.count);
    const result = await tx.journalEntry.findUnique({ where: { id: entry.id }, include: entryInclude });
    if (!result) throw new AppError(409, "VOUCHER_TRANSITION_CONFLICT", "The voucher changed; reload and try again");
    const action = nextStatus === JournalStatus.POSTED ? "POST" : "ARCHIVE";
    await audit(tx, req, action, `${entry.type}Voucher`, entry.id, { branchId: entry.branchId, voucherNumber: entry.voucherNumber, ...(totalPaise === undefined ? {} : { totalPaise }) });
    return result;
  });
}

router.get("/finance/dashboard",async(r:AuthRequest,res)=>{const ids=await scope(r),w=ids?{branchId:{in:ids}}:{},[accounts,entries,banks,expenses,fees]=await Promise.all([prisma.ledgerAccount.count({where:{...w,isArchived:false}}),prisma.journalEntry.count({where:{...w,status:JournalStatus.POSTED}}),prisma.financeBankAccount.count({where:{...w,isArchived:false}}),prisma.expenseBill.aggregate({_sum:{totalPaise:true},where:{...w,status:{in:[FinanceApprovalStatus.APPROVED,FinanceApprovalStatus.PAID]}}}),prisma.fee.aggregate({_sum:{totalPaise:true,amountPaidPaise:true},where:w})]);res.json({data:json({accounts,postedEntries:entries,bankAccounts:banks,expensesPaise:expenses._sum.totalPaise??0,feesRaisedPaise:fees._sum.totalPaise??0,feesCollectedPaise:fees._sum.amountPaidPaise??0})})});

router.get("/finance/years",async(r:AuthRequest,res)=>{const ids=await scope(r);res.json({data:await prisma.financialYear.findMany({where:ids?{branchId:{in:ids}}:{},include:{branch:true,_count:{select:{entries:true}}},orderBy:{startsAt:"desc"}})})});
router.post("/finance/years", async (req: AuthRequest, res) => { const data = z.object({ branchId: z.string().cuid(), name: z.string().min(2), startsAt: z.coerce.date(), endsAt: z.coerce.date() }).parse(req.body); await access(req, data.branchId); if (data.endsAt <= data.startsAt) throw new AppError(422, "INVALID_DATES", "Financial year end must follow start"); const created = await prisma.$transaction(async tx => { const year = await tx.financialYear.create({ data: { ...data, startsAt: date(data.startsAt), endsAt: date(data.endsAt) } }); await audit(tx, req, "CREATE", "FinancialYear", year.id, { branchId: data.branchId, name: data.name }); return year; }); res.status(201).json({ data: created }); });
router.patch("/finance/years/:yearId/lock", async (req: AuthRequest, res) => { const year = await prisma.financialYear.findUnique({ where: { id: String(req.params.yearId) } }); if (!year) throw new AppError(404, "NOT_FOUND", "Financial year not found"); await access(req, year.branchId); const isLocked = z.boolean().parse(req.body.isLocked); if (!isLocked && year.isLocked && req.auth!.role !== Role.SUPER_ADMIN) throw new AppError(403, "UNLOCK_FORBIDDEN", "Only super administrators may unlock a year"); const updated = await prisma.$transaction(async tx => { const result = await tx.financialYear.update({ where: { id: year.id }, data: { isLocked, lockedAt: isLocked ? new Date() : null } }); await audit(tx, req, isLocked ? "LOCK" : "UNLOCK", "FinancialYear", year.id, { branchId: year.branchId }); return result; }); res.json({ data: updated }); });

router.get("/finance/account-groups", async (req: AuthRequest, res) => { const assigned = (await scope(req)) ?? []; if (!canReadFinanceMasterData(req.auth!.role, assigned)) return res.json({ data: [] }); res.json({ data: await prisma.accountGroup.findMany({ include: { parent: true, children: true, _count: { select: { accounts: true } } }, orderBy: { code: "asc" } }) }); });
router.post("/finance/account-groups", allow(Role.SUPER_ADMIN), async (req: AuthRequest, res) => { const data = z.object({ name: z.string().min(2), code: z.string().min(2), type: z.nativeEnum(AccountType), parentId: z.string().cuid().nullable().optional() }).parse(req.body); const created = await prisma.$transaction(async tx => { if (data.parentId) { const parent = await tx.accountGroup.findUnique({ where: { id: data.parentId }, select: { type: true, isArchived: true } }); if (!parent || parent.isArchived || parent.type !== data.type) throw new AppError(422, "INVALID_PARENT_GROUP", "Parent group must be active and have the same account type"); } const group = await tx.accountGroup.create({ data }); await audit(tx, req, "CREATE", "AccountGroup", group.id, { code: group.code, type: group.type }); return group; }); res.status(201).json({ data: created }); });
router.patch("/finance/account-groups/:id", allow(Role.SUPER_ADMIN), async (req: AuthRequest, res) => { const data = z.object({ name: z.string().min(2).optional(), isArchived: z.boolean().optional() }).parse(req.body); const updated = await prisma.$transaction(async tx => { const group = await tx.accountGroup.findUnique({ where: { id: String(req.params.id) }, select: { id: true } }); if (!group) throw new AppError(404, "NOT_FOUND", "Account group not found"); const result = await tx.accountGroup.update({ where: { id: group.id }, data }); await audit(tx, req, "UPDATE", "AccountGroup", group.id, { changedFields: Object.keys(data) }); return result; }); res.json({ data: updated }); });
router.delete("/finance/account-groups/:id", allow(Role.SUPER_ADMIN), async (req: AuthRequest, res) => { await prisma.$transaction(async tx => { const group = await tx.accountGroup.findUnique({ where: { id: String(req.params.id) }, include: { _count: { select: { accounts: true, children: true } } } }); if (!group || !group.isArchived || group._count.accounts || group._count.children) throw new AppError(409, "GROUP_REFERENCED", "Archive an unused group before deleting"); await tx.accountGroup.delete({ where: { id: group.id } }); await audit(tx, req, "DELETE", "AccountGroup", group.id, { code: group.code }); }); res.status(204).end(); });
const account=z.object({branchId:z.string().cuid(),groupId:z.string().cuid(),code:z.string().min(2).max(30),name:z.string().min(2).max(150),type:z.nativeEnum(AccountType),openingDebitPaise:z.number().int().min(0).default(0),openingCreditPaise:z.number().int().min(0).default(0),gstin:z.string().max(20).nullable().optional(),pan:z.string().max(20).nullable().optional(),isSystem:z.boolean().default(false)});
router.get("/finance/accounts", async (req: AuthRequest, res) => { const query = page.extend({ branchId: z.string().cuid().optional(), type: z.nativeEnum(AccountType).optional(), archived: z.enum(["true", "false"]).optional() }).parse(req.query), where = { ...await branchWhere(req, query.branchId), ...(query.type ? { type: query.type } : {}), ...(query.archived ? { isArchived: query.archived === "true" } : {}), ...(query.search ? { OR: [{ name: { contains: query.search, mode: "insensitive" as const } }, { code: { contains: query.search, mode: "insensitive" as const } }] } : {}) }; const [data, total] = await Promise.all([prisma.ledgerAccount.findMany({ where, include: { group: true, branch: true, _count: { select: { lines: true } } }, skip: (query.page - 1) * query.limit, take: query.limit, orderBy: { code: query.sortOrder } }), prisma.ledgerAccount.count({ where })]); res.json({ data: json(data), meta: { total, page: query.page, limit: query.limit, totalPages: Math.max(1, Math.ceil(total / query.limit)) } }); });
router.post("/finance/accounts", async (req: AuthRequest, res) => { const data = account.parse(req.body), permittedBranchIds = (await scope(req)) ?? []; assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, data.branchId); assertSystemAccountCreationAllowed(req.auth!.role, data.isSystem); if (data.openingDebitPaise && data.openingCreditPaise) throw new AppError(422, "INVALID_OPENING_BALANCE", "Opening balance cannot be both debit and credit"); const created = await serializable(async tx => { assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, data.branchId); if (await tx.ledgerAccount.findFirst({ where: { branchId: data.branchId, OR: [{ code: { equals: data.code, mode: "insensitive" } }, { name: { equals: data.name, mode: "insensitive" } }] } })) throw new AppError(409, "ACCOUNT_EXISTS", "Account code or name already exists"); const group = await tx.accountGroup.findUnique({ where: { id: data.groupId } }); if (!group || group.isArchived || group.type !== data.type) throw new AppError(422, "ACCOUNT_GROUP_TYPE_MISMATCH", "Account type must match an active group"); const result = await tx.ledgerAccount.create({ data }); await audit(tx, req, "CREATE", "LedgerAccount", result.id, { branchId: data.branchId, code: data.code, type: data.type, openingDebitPaise: data.openingDebitPaise, openingCreditPaise: data.openingCreditPaise, isSystem: data.isSystem }); return result; }); res.status(201).json({ data: json(created) }); });
router.patch("/finance/accounts/:id", async (req: AuthRequest, res) => { const accountRecord = await prisma.ledgerAccount.findUnique({ where: { id: String(req.params.id) } }); if (!accountRecord) throw new AppError(404, "NOT_FOUND", "Account not found"); await access(req, accountRecord.branchId); const data = z.object({ name: z.string().min(2).optional(), gstin: z.string().nullable().optional(), pan: z.string().nullable().optional(), isArchived: z.boolean().optional() }).parse(req.body); const updated = await prisma.$transaction(async tx => { const result = await tx.ledgerAccount.update({ where: { id: accountRecord.id }, data }); await audit(tx, req, "UPDATE", "LedgerAccount", accountRecord.id, { branchId: accountRecord.branchId, changedFields: Object.keys(data) }); return result; }); res.json({ data: json(updated) }); });
router.delete("/finance/accounts/:id", async (req: AuthRequest, res) => { const accountRecord = await prisma.ledgerAccount.findUnique({ where: { id: String(req.params.id) }, include: { _count: { select: { lines: true, vendors: true, expenseBills: true } }, bankAccount: true } }); if (!accountRecord) throw new AppError(404, "NOT_FOUND", "Account not found"); await access(req, accountRecord.branchId); if (accountRecord.isSystem || !accountRecord.isArchived || Object.values(accountRecord._count).some(Boolean) || accountRecord.bankAccount) throw new AppError(409, "ACCOUNT_REFERENCED", "System, active or referenced accounts cannot be deleted"); await prisma.$transaction(async tx => { await tx.ledgerAccount.delete({ where: { id: accountRecord.id } }); await audit(tx, req, "DELETE", "LedgerAccount", accountRecord.id, { branchId: accountRecord.branchId, code: accountRecord.code }); }); res.status(204).end(); });

router.get("/finance/entries", async (req: AuthRequest, res) => { const query = page.extend({ branchId: z.string().cuid().optional(), type: z.nativeEnum(VoucherType).optional(), status: z.nativeEnum(JournalStatus).optional(), from: z.coerce.date().optional(), to: z.coerce.date().optional() }).parse(req.query), where = { ...await branchWhere(req, query.branchId), ...(query.type ? { type: query.type } : {}), ...(query.status ? { status: query.status } : {}), ...(query.from || query.to ? { date: { gte: query.from, lte: query.to } } : {}), ...(query.search ? { OR: [{ voucherNumber: { contains: query.search, mode: "insensitive" as const } }, { narration: { contains: query.search, mode: "insensitive" as const } }, { reference: { contains: query.search, mode: "insensitive" as const } }] } : {}) }; const [data, total] = await Promise.all([prisma.journalEntry.findMany({ where, include: entryInclude, skip: (query.page - 1) * query.limit, take: query.limit, orderBy: [{ date: query.sortOrder }, { voucherNumber: query.sortOrder }] }), prisma.journalEntry.count({ where })]); res.json({ data: json(data), meta: { total, page: query.page, limit: query.limit, totalPages: Math.max(1, Math.ceil(total / query.limit)) } }); });
router.post("/finance/entries", async (req: AuthRequest, res) => { const data = entryInput.parse(req.body); await access(req, data.branchId); const totalPaise = balanced(data.lines); const created = await prisma.$transaction(async tx => { await yearCheck(tx, data); if (await tx.journalEntry.findFirst({ where: { branchId: data.branchId, financialYearId: data.financialYearId, voucherNumber: { equals: data.voucherNumber, mode: "insensitive" } } })) throw new AppError(409, "VOUCHER_EXISTS", "Voucher number already exists"); await activeAccounts(tx, data.branchId, data.lines.map(item => item.accountId)); const { lines: journalLines, ...head } = data; const entry = await tx.journalEntry.create({ data: { ...head, date: date(data.date), createdById: id(req), postedAt: data.status === JournalStatus.POSTED ? new Date() : null, lines: { create: journalLines } }, include: entryInclude }); await audit(tx, req, "CREATE", `${data.type}Voucher`, entry.id, { branchId: data.branchId, voucherNumber: data.voucherNumber, totalPaise, status: data.status }); return entry; }); res.status(201).json({ data: json(created) }); });
router.patch("/finance/entries/:id/post", async (req: AuthRequest, res) => { res.json({ data: json(await transitionVoucher(req, String(req.params.id), JournalStatus.POSTED)) }); });
router.patch("/finance/entries/:id/archive", async (req: AuthRequest, res) => { res.json({ data: json(await transitionVoucher(req, String(req.params.id), JournalStatus.ARCHIVED)) }); });
router.delete("/finance/entries/:id", async (req: AuthRequest, res) => { const entry = await prisma.journalEntry.findUnique({ where: { id: String(req.params.id) }, include: { financialYear: true, _count: { select: { expenseBills: true, bankTransactions: true, feeAdjustments: true } } } }); if (!entry) throw new AppError(404, "NOT_FOUND", "Voucher not found"); await access(req, entry.branchId); if (entry.status !== JournalStatus.ARCHIVED || entry.financialYear.isLocked || Object.values(entry._count).some(Boolean)) throw new AppError(409, "VOUCHER_PROTECTED", "Only unreferenced archived vouchers in open years can be deleted"); await prisma.$transaction(async tx => { await tx.journalEntry.delete({ where: { id: entry.id } }); await audit(tx, req, "DELETE", `${entry.type}Voucher`, entry.id, { branchId: entry.branchId, voucherNumber: entry.voucherNumber }); }); res.status(204).end(); });

router.get("/finance/ledger/:accountId",async(r:AuthRequest,res)=>{const q=z.object({from:z.coerce.date(),to:z.coerce.date()}).parse(r.query),a=await prisma.ledgerAccount.findUnique({where:{id:String(r.params.accountId)},include:{branch:true}});if(!a)throw new AppError(404,"NOT_FOUND","Account not found");await access(r,a.branchId);const lines=await prisma.journalLine.findMany({where:{accountId:a.id,entry:{status:JournalStatus.POSTED,date:{gte:q.from,lte:q.to}}},include:{entry:true},orderBy:{entry:{date:"asc"}}});let balance=Number(a.openingDebitPaise)-Number(a.openingCreditPaise);res.json({data:{account:json(a),openingBalancePaise:balance,lines:lines.map(x=>{balance+=Number(x.debitPaise)-Number(x.creditPaise);return json({...x,balancePaise:balance})}),closingBalancePaise:balance}})});
async function balances(req: AuthRequest, from: Date, to: Date, branchId?: string) { const branch = await branchWhere(req, branchId), accounts = await prisma.ledgerAccount.findMany({ where: { ...branch, isArchived: false }, include: { lines: { where: { entry: { status: JournalStatus.POSTED, date: { gte: from, lte: to } } } } }, orderBy: { code: "asc" } }); return accounts.map(accountRecord => { const debit = Number(accountRecord.openingDebitPaise) + accountRecord.lines.reduce((sum, line) => sum + Number(line.debitPaise), 0), credit = Number(accountRecord.openingCreditPaise) + accountRecord.lines.reduce((sum, line) => sum + Number(line.creditPaise), 0); return { id: accountRecord.id, code: accountRecord.code, name: accountRecord.name, type: accountRecord.type, debitPaise: debit, creditPaise: credit, balancePaise: debit - credit }; }); }
router.get("/finance/reports/:report", async (req: AuthRequest, res) => { const query = z.object({ from: z.coerce.date(), to: z.coerce.date(), branchId: z.string().cuid().optional(), format: z.enum(["json", "pdf", "excel"]).default("json") }).parse(req.query), branch = await branchWhere(req, query.branchId); const all = await balances(req, query.from, query.to, query.branchId), report = String(req.params.report); let rows: any[] = all; if (report === "profit-loss" || report === "income-statement") rows = all.filter(item => item.type === AccountType.INCOME || item.type === AccountType.EXPENSE); else if (report === "balance-sheet") rows = all.filter(item => ([AccountType.ASSET, AccountType.LIABILITY, AccountType.EQUITY] as AccountType[]).includes(item.type)); else if (report === "cash-flow" || report === "cash-book" || report === "bank-book") rows = all.filter(item => /cash|bank/i.test(item.name)); else if (report === "outstanding") return res.json({ data: json(await prisma.fee.findMany({ where: { ...branch, status: { in: ["PENDING", "PARTIAL", "OVERDUE"] } }, include: { student: { include: { user: true } }, branch: true, course: true, batch: true } })) }); else if (report === "day-book") { const entries = await prisma.journalEntry.findMany({ where: { ...branch, date: { gte: query.from, lte: query.to }, status: JournalStatus.POSTED }, include: entryInclude, orderBy: { date: "asc" } }); if (query.format === "json") return res.json({ data: json(entries) }); rows = entries.map(entry => ({ voucher: entry.voucherNumber, date: entry.date, type: entry.type, narration: entry.narration, total: entry.lines.reduce((sum, line) => sum + Number(line.debitPaise), 0) })); } const totals = { debitPaise: rows.reduce((sum, item) => sum + Number(item.debitPaise ?? item.total ?? 0), 0), creditPaise: rows.reduce((sum, item) => sum + Number(item.creditPaise ?? 0), 0), netPaise: rows.reduce((sum, item) => sum + Number(item.balancePaise ?? 0), 0) }; if (query.format === "pdf") return pdf(res, report.toUpperCase(), rows.map(item => Object.values(item).join(" | ")), `${report}.pdf`); if (query.format === "excel") return xls(res, [Object.keys(rows[0] ?? {}), ...rows.map(Object.values)], `${report}.xls`); res.json({ data: { rows: json(rows), totals } }); });
const vendor=z.object({branchId:z.string().cuid(),code:z.string().min(2),name:z.string().min(2),email:z.string().email().nullable().optional(),phone:z.string().nullable().optional(),address:z.string().nullable().optional(),gstin:z.string().nullable().optional(),pan:z.string().nullable().optional(),accountId:z.string().cuid().nullable().optional()});
router.get("/finance/vendors",async(r:AuthRequest,res)=>{const ids=await scope(r);res.json({data:await prisma.financeVendor.findMany({where:ids?{branchId:{in:ids}}:{},include:{branch:true,account:true,_count:{select:{bills:true}}},orderBy:{name:"asc"}})})});
router.post("/finance/vendors", async (req: AuthRequest, res) => { const data = vendor.parse(req.body), permittedBranchIds = (await scope(req)) ?? []; assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, data.branchId); const created = await serializable(async tx => { assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, data.branchId); if (data.accountId) await activeAccounts(tx, data.branchId, [data.accountId]); const result = await tx.financeVendor.create({ data }); await audit(tx, req, "CREATE", "FinanceVendor", result.id, { branchId: data.branchId, code: data.code, hasLedgerAccount: Boolean(data.accountId) }); return result; }); res.status(201).json({ data: created }); });
router.patch("/finance/vendors/:id", async (req: AuthRequest, res) => { const data = vendor.partial().parse(req.body), permittedBranchIds = (await scope(req)) ?? []; const updated = await serializable(async tx => { const existing = await tx.financeVendor.findUnique({ where: { id: String(req.params.id) }, include: { _count: { select: { bills: true } } } }); if (!existing) throw new AppError(404, "NOT_FOUND", "Vendor not found"); assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, existing.branchId); const branchId = data.branchId ?? existing.branchId, accountId = data.accountId === undefined ? existing.accountId : data.accountId; assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, branchId); if (branchId !== existing.branchId && existing._count.bills) throw new AppError(409, "VENDOR_BRANCH_LOCKED", "A vendor with expense bills cannot move to another branch"); if (accountId) await activeAccounts(tx, branchId, [accountId]); const result = await tx.financeVendor.update({ where: { id: existing.id }, data }); await audit(tx, req, "UPDATE", "FinanceVendor", existing.id, { branchId, changedFields: Object.keys(data), hasLedgerAccount: Boolean(accountId) }); return result; }); res.json({ data: updated }); });
router.get("/finance/expense-categories", async (req: AuthRequest, res) => { const assigned = (await scope(req)) ?? []; if (!canReadFinanceMasterData(req.auth!.role, assigned)) return res.json({ data: [] }); res.json({ data: await prisma.expenseCategory.findMany({ orderBy: { name: "asc" } }) }); });
router.post("/finance/expense-categories", allow(Role.SUPER_ADMIN), async (req: AuthRequest, res) => { const data = z.object({ name: z.string().min(2), code: z.string().min(2), scope: z.enum(["OFFICE", "ACADEMIC", "OTHER"]).default("OFFICE") }).parse(req.body); const created = await prisma.$transaction(async tx => { const result = await tx.expenseCategory.create({ data }); await audit(tx, req, "CREATE", "ExpenseCategory", result.id, { code: result.code, scope: result.scope }); return result; }); res.status(201).json({ data: created }); });
const bill=z.object({branchId:z.string().cuid(),vendorId:z.string().cuid().nullable().optional(),categoryId:z.string().cuid(),expenseAccountId:z.string().cuid(),billNumber:z.string().min(2),billDate:z.coerce.date(),dueDate:z.coerce.date().nullable().optional(),taxablePaise:z.number().int().positive(),gstPaise:z.number().int().min(0).default(0),tdsPaise:z.number().int().min(0).default(0),totalPaise:z.number().int().positive(),remarks:z.string().optional(),attachment:z.object({name:z.string(),mimeType:z.enum(["application/pdf","image/jpeg","image/png"]),base64:z.string()}).nullable().optional()});
router.get("/finance/expenses",async(r:AuthRequest,res)=>{const q=page.extend({status:z.nativeEnum(FinanceApprovalStatus).optional()}).parse(r.query),ids=await scope(r),where={...(ids?{branchId:{in:ids}}:{}),...(q.status?{status:q.status}:{}),...(q.search?{OR:[{billNumber:{contains:q.search,mode:"insensitive"as const}},{vendor:{name:{contains:q.search,mode:"insensitive"as const}}}]}:{})};const[data,total]=await Promise.all([prisma.expenseBill.findMany({where,include:{vendor:true,category:true,expenseAccount:true,approver:true},skip:(q.page-1)*q.limit,take:q.limit,orderBy:{billDate:q.sortOrder}}),prisma.expenseBill.count({where})]);res.json({data:json(data),meta:{total,page:q.page,limit:q.limit,totalPages:Math.max(1,Math.ceil(total/q.limit))}})});
router.post("/finance/expenses", async (req: AuthRequest, res) => { const data = bill.parse(req.body); await access(req, data.branchId); if (data.totalPaise !== data.taxablePaise + data.gstPaise) throw new AppError(422, "INVALID_BILL_TOTAL", "Bill total must equal taxable amount plus GST"); let attachmentData: Uint8Array<ArrayBuffer> | undefined; if (data.attachment) { attachmentData = Uint8Array.from(Buffer.from(data.attachment.base64, "base64")); if (!attachmentData.length || attachmentData.length > 5242880) throw new AppError(422, "INVALID_ATTACHMENT", "Attachment must be 1 byte to 5 MB"); } const { attachment, ...head } = data; const created = await serializable(async tx => { if (data.vendorId) { const vendorRecord = await tx.financeVendor.findUnique({ where: { id: data.vendorId }, select: { branchId: true, isArchived: true } }); if (!vendorRecord || vendorRecord.isArchived) throw new AppError(422, "INVALID_VENDOR", "Vendor must be active and belong to the expense branch"); assertRelatedBranch("Vendor", data.branchId, vendorRecord.branchId); } const expenseAccount = (await activeAccounts(tx, data.branchId, [data.expenseAccountId]))[0]; if (expenseAccount.type !== AccountType.EXPENSE) throw new AppError(422, "INVALID_EXPENSE_ACCOUNT", "Expense bill account must use the EXPENSE account type"); const category = await tx.expenseCategory.findUnique({ where: { id: data.categoryId }, select: { isArchived: true } }); if (!category || category.isArchived) throw new AppError(422, "INVALID_EXPENSE_CATEGORY", "Expense category must be active"); const result = await tx.expenseBill.create({ data: { ...head, ...(attachment ? { attachmentName: attachment.name, attachmentMime: attachment.mimeType, attachmentData } : {}), status: FinanceApprovalStatus.PENDING } }); await audit(tx, req, "CREATE", "ExpenseBill", result.id, { branchId: data.branchId, billNumber: data.billNumber, totalPaise: data.totalPaise, hasAttachment: Boolean(attachment) }); return result; }); res.status(201).json({ data: json(created) }); });
router.patch("/finance/expenses/:id/approve", async (req: AuthRequest, res) => { const data = z.object({ financialYearId: z.string().cuid(), voucherNumber: z.string().min(2), creditAccountId: z.string().cuid(), status: z.enum([FinanceApprovalStatus.APPROVED, FinanceApprovalStatus.REJECTED]) }).parse(req.body), permittedBranchIds = (await scope(req)) ?? []; const decided = await serializable(async tx => { const billRecord = await tx.expenseBill.findUnique({ where: { id: String(req.params.id) } }); if (!billRecord) throw new AppError(404, "NOT_FOUND", "Expense bill not found"); assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, billRecord.branchId); if (billRecord.status !== FinanceApprovalStatus.PENDING) throw new AppError(409, "BILL_LOCKED", "Only pending bills can be decided"); if (data.status === FinanceApprovalStatus.REJECTED) { const result = await tx.expenseBill.update({ where: { id: billRecord.id }, data: { status: data.status, approverId: id(req) } }); await audit(tx, req, "REJECT", "ExpenseBill", billRecord.id, { branchId: billRecord.branchId, billNumber: billRecord.billNumber, totalPaise: Number(billRecord.totalPaise) }); return result; } const entry = await createBalanced(tx, req, { branchId: billRecord.branchId, financialYearId: data.financialYearId, voucherNumber: data.voucherNumber, type: VoucherType.PURCHASE, date: billRecord.billDate, narration: `Purchase bill ${billRecord.billNumber}`, sourceType: "EXPENSE_BILL", sourceId: billRecord.id, lines: [{ accountId: billRecord.expenseAccountId, debitPaise: Number(billRecord.totalPaise), creditPaise: 0 }, { accountId: data.creditAccountId, debitPaise: 0, creditPaise: Number(billRecord.totalPaise) }] }); const result = await tx.expenseBill.update({ where: { id: billRecord.id }, data: { status: FinanceApprovalStatus.APPROVED, approverId: id(req), journalEntryId: entry.id } }); await audit(tx, req, "APPROVE", "ExpenseBill", billRecord.id, { branchId: billRecord.branchId, journalEntryId: entry.id, totalPaise: Number(billRecord.totalPaise) }); return result; }); res.json({ data: json(decided) }); });
router.get("/finance/expenses/:id/attachment",async(r:AuthRequest,res)=>{const b=await prisma.expenseBill.findUnique({where:{id:String(r.params.id)}});if(!b?.attachmentData)throw new AppError(404,"NOT_FOUND","Attachment not found");await access(r,b.branchId);res.set({"Content-Type":b.attachmentMime!,"Content-Disposition":"attachment"}).send(Buffer.from(b.attachmentData))});
async function createBalanced(db: Prisma.TransactionClient, req: AuthRequest, data: { branchId: string; financialYearId: string; voucherNumber: string; type: VoucherType; date: Date; narration: string; sourceType?: string; sourceId?: string; lines: { accountId: string; debitPaise: number; creditPaise: number }[] }) { balanced(data.lines); await yearCheck(db, data); await activeAccounts(db, data.branchId, data.lines.map(line => line.accountId)); const { lines: journalLines, ...head } = data; return db.journalEntry.create({ data: { ...head, date: date(data.date), status: JournalStatus.POSTED, postedAt: new Date(), createdById: id(req), lines: { create: journalLines } }, include: entryInclude }); }
router.post("/finance/fee-adjustments", async (req: AuthRequest, res) => { const data = z.object({ feeId: z.string().cuid(), financialYearId: z.string().cuid(), voucherNumber: z.string().min(2), type: z.enum(["REFUND", "DISCOUNT", "SCHOLARSHIP", "FINE"]), amountPaise: z.number().int().positive(), reason: z.string().min(2), reference: z.string().min(2), debitAccountId: z.string().cuid(), creditAccountId: z.string().cuid() }).parse(req.body), permittedBranchIds = (await scope(req)) ?? []; if (data.debitAccountId === data.creditAccountId) throw new AppError(422, "INVALID_ADJUSTMENT_ACCOUNTS", "Debit and credit accounts must be different"); const created = await serializable(async tx => { const fee = await tx.fee.findUnique({ where: { id: data.feeId }, select: { id: true, branchId: true } }); if (!fee) throw new AppError(404, "NOT_FOUND", "Fee not found"); assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, fee.branchId); const entry = await createBalanced(tx, req, { branchId: fee.branchId, financialYearId: data.financialYearId, voucherNumber: data.voucherNumber, type: data.type === "REFUND" ? VoucherType.REFUND : VoucherType.JOURNAL, date: new Date(), narration: `${data.type}: ${data.reason}`, sourceType: "FEE_ADJUSTMENT", sourceId: data.reference, lines: [{ accountId: data.debitAccountId, debitPaise: data.amountPaise, creditPaise: 0 }, { accountId: data.creditAccountId, debitPaise: 0, creditPaise: data.amountPaise }] }); const adjustment = await tx.feeAdjustment.create({ data: { feeId: fee.id, journalEntryId: entry.id, type: data.type, amountPaise: data.amountPaise, reason: data.reason, reference: data.reference } }); await audit(tx, req, "CREATE", "FeeAdjustment", adjustment.id, { feeId: fee.id, branchId: fee.branchId, journalEntryId: entry.id, type: data.type, amountPaise: data.amountPaise, reference: data.reference }); return adjustment; }); res.status(201).json({ data: json(created) }); });

router.get("/finance/banks",async(r:AuthRequest,res)=>{const ids=await scope(r);res.json({data:json(await prisma.financeBankAccount.findMany({where:ids?{branchId:{in:ids}}:{},include:{ledgerAccount:true,_count:{select:{transactions:true}}}}))})});
router.post("/finance/banks", async (req: AuthRequest, res) => { const data = z.object({ branchId: z.string().cuid(), ledgerAccountId: z.string().cuid(), bankName: z.string().min(2), accountNumber: z.string().min(3), ifsc: z.string().min(3), openingBalancePaise: z.number().int().default(0) }).parse(req.body), permittedBranchIds = (await scope(req)) ?? []; assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, data.branchId); const created = await serializable(async tx => { assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, data.branchId); const ledger = (await activeAccounts(tx, data.branchId, [data.ledgerAccountId]))[0]; if (ledger.type !== AccountType.ASSET) throw new AppError(422, "INVALID_BANK_LEDGER", "Bank ledger account must use the ASSET account type"); const result = await tx.financeBankAccount.create({ data }); await audit(tx, req, "CREATE", "FinanceBankAccount", result.id, { branchId: data.branchId, ledgerAccountId: data.ledgerAccountId, openingBalancePaise: data.openingBalancePaise }); return result; }); res.status(201).json({ data: json(created) }); });
router.post("/finance/banks/:id/transactions", async (req: AuthRequest, res) => { const data = z.object({ journalEntryId: z.string().cuid().nullable().optional(), transactionDate: z.coerce.date(), reference: z.string().min(2), amountPaise: z.number().int().positive(), direction: z.enum(["IN", "OUT"]), mode: z.enum(["CHEQUE", "ONLINE", "UPI", "CASH", "TRANSFER"]), chequeNumber: z.string().nullable().optional(), chequeStatus: z.string().nullable().optional() }).parse(req.body), permittedBranchIds = (await scope(req)) ?? []; const created = await serializable(async tx => { const bank = await tx.financeBankAccount.findUnique({ where: { id: String(req.params.id) }, select: { id: true, branchId: true, isArchived: true } }); if (!bank) throw new AppError(404, "NOT_FOUND", "Bank account not found"); assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, bank.branchId); if (bank.isArchived) throw new AppError(409, "BANK_ACCOUNT_ARCHIVED", "Transactions cannot be added to an archived bank account"); if (data.journalEntryId) { const entry = await tx.journalEntry.findUnique({ where: { id: data.journalEntryId }, select: { branchId: true, status: true } }); if (!entry || entry.status !== JournalStatus.POSTED) throw new AppError(422, "INVALID_JOURNAL_ENTRY", "Bank transactions can link only to posted journal entries"); assertRelatedBranch("Journal entry", bank.branchId, entry.branchId); } const result = await tx.financeBankTransaction.create({ data: { ...data, bankAccountId: bank.id, transactionDate: date(data.transactionDate) } }); await audit(tx, req, "CREATE", "FinanceBankTransaction", result.id, { bankAccountId: bank.id, branchId: bank.branchId, journalEntryId: data.journalEntryId ?? null, amountPaise: data.amountPaise, direction: data.direction, mode: data.mode, reference: data.reference }); return result; }); res.status(201).json({ data: json(created) }); });
router.patch("/finance/bank-transactions/:id/reconcile", async (req: AuthRequest, res) => { const data = z.object({ reconciled: z.boolean(), statementReference: z.string().max(100).nullable().optional() }).parse(req.body), permittedBranchIds = (await scope(req)) ?? []; const updated = await serializable(async tx => { const transaction = await tx.financeBankTransaction.findUnique({ where: { id: String(req.params.id) }, include: { bankAccount: { select: { branchId: true } } } }); if (!transaction) throw new AppError(404, "NOT_FOUND", "Bank transaction not found"); assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, transaction.bankAccount.branchId); const result = await tx.financeBankTransaction.update({ where: { id: transaction.id }, data: { ...data, reconciledAt: data.reconciled ? new Date() : null } }); await audit(tx, req, data.reconciled ? "RECONCILE" : "UNRECONCILE", "FinanceBankTransaction", transaction.id, { bankAccountId: transaction.bankAccountId, branchId: transaction.bankAccount.branchId, amountPaise: Number(transaction.amountPaise), reference: transaction.reference }); return result; }); res.json({ data: json(updated) }); });
router.get("/finance/gst",async(r:AuthRequest,res)=>{const ids=await scope(r);res.json({data:await prisma.gstConfiguration.findMany({where:ids?{branchId:{in:ids}}:{},include:{branch:true},orderBy:{effectiveFrom:"desc"}})})});
router.post("/finance/gst", async (req: AuthRequest, res) => { const data = z.object({ branchId: z.string().cuid(), gstin: z.string().min(15).max(15), stateCode: z.string().length(2), defaultRate: z.number().min(0).max(100), tdsRate: z.number().min(0).max(100), effectiveFrom: z.coerce.date() }).parse(req.body); await access(req, data.branchId); const created = await prisma.$transaction(async tx => { const result = await tx.gstConfiguration.create({ data }); await audit(tx, req, "CREATE", "GstConfiguration", result.id, { branchId: data.branchId, effectiveFrom: data.effectiveFrom.toISOString(), defaultRate: data.defaultRate, tdsRate: data.tdsRate }); return result; }); res.status(201).json({ data: created }); });

router.post("/finance/import/accounts", async (req: AuthRequest, res) => { const data = z.object({ rows: z.array(account).min(1).max(1000) }).parse(req.body), permittedBranchIds = (await scope(req)) ?? []; for (const row of data.rows) { assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, row.branchId); assertSystemAccountCreationAllowed(req.auth!.role, row.isSystem); if (row.openingDebitPaise && row.openingCreditPaise) throw new AppError(422, "INVALID_OPENING_BALANCE", "Opening balance cannot be both debit and credit"); } const created = await serializable(async tx => { for (const row of data.rows) assertFinanceBranchAccess(req.auth!.role, permittedBranchIds, row.branchId); const groups = await tx.accountGroup.findMany({ where: { id: { in: [...new Set(data.rows.map(row => row.groupId))] }, isArchived: false }, select: { id: true, type: true } }); const byId = new Map(groups.map(group => [group.id, group.type])); for (const row of data.rows) if (byId.get(row.groupId) !== row.type) throw new AppError(422, "ACCOUNT_GROUP_TYPE_MISMATCH", "Every imported account must use an active group with the same account type"); const results = []; for (const row of data.rows) results.push(await tx.ledgerAccount.create({ data: row })); await audit(tx, req, "IMPORT", "LedgerAccount", undefined, { count: results.length, branchIds: [...new Set(data.rows.map(row => row.branchId))] }); return results; }); res.status(201).json({ data: json(created) }); });
router.get("/finance/export/:entity",async(r:AuthRequest,res)=>{const entity=String(r.params.entity),format=z.enum(["excel","pdf"]).default("excel").parse(r.query.format),ids=await scope(r);let rows:any[][]=[];if(entity==="accounts")rows=(await prisma.ledgerAccount.findMany({where:ids?{branchId:{in:ids}}:{},include:{group:true,branch:true}})).map(x=>[x.code,x.name,x.type,x.group.name,x.branch.branchName,x.openingDebitPaise,x.openingCreditPaise]);else rows=(await prisma.journalEntry.findMany({where:ids?{branchId:{in:ids}}:{},include:{lines:true,branch:true}})).map(x=>[x.voucherNumber,x.date.toISOString().slice(0,10),x.type,x.branch.branchName,x.status,x.lines.reduce((n,l)=>n+Number(l.debitPaise),0)]);if(format==="pdf")return pdf(res,entity.toUpperCase(),rows.map(x=>x.join(" | ")),`${entity}.pdf`);xls(res,rows,`${entity}.xls`)});
function xls(res:any,rows:any[][],file:string){const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Finance"><Table>${rows.map(r=>`<Row>${r.map(v=>`<Cell><Data ss:Type="String">${String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;")}</Data></Cell>`).join("")}</Row>`).join("")}</Table></Worksheet></Workbook>`;res.set({"Content-Type":"application/vnd.ms-excel","Content-Disposition":`attachment; filename=${file}`}).send(xml)}function pdf(res:any,title:string,rows:string[],file:string){const c=[title,...rows].slice(0,45).map((x,i)=>`BT /F1 ${i?8:16} Tf 25 ${810-i*17} Td (${x.replace(/[()\\]/g,"\\$&")}) Tj ET`).join("\n"),o=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",`<< /Length ${Buffer.byteLength(c)} >>\nstream\n${c}\nendstream`,"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"];let p="%PDF-1.4\n",a=[0];o.forEach((x,i)=>{a.push(Buffer.byteLength(p));p+=`${i+1} 0 obj\n${x}\nendobj\n`});const at=Buffer.byteLength(p);p+=`xref\n0 6\n0000000000 65535 f \n${a.slice(1).map(x=>String(x).padStart(10,"0")+" 00000 n ").join("\n")}\ntrailer << /Size 6 /Root 1 0 R >>\nstartxref\n${at}\n%%EOF`;res.set({"Content-Type":"application/pdf","Content-Disposition":`attachment; filename=${file}`}).send(Buffer.from(p))}export default router;
