import { AttendanceStatus, HalfDaySession, LeaveRequestStatus, LeaveType, Role } from "@prisma/client";
import { Router } from "express";
import { z } from "zod";
import { AppError } from "../lib/http.js";
import { assertLeaveAttendanceCompatible } from "../lib/leave-attendance-policy.js";
import { prisma } from "../lib/prisma.js";
import { decodeVerifiedUpload } from "../lib/secure-upload.js";
import { requireAuth, type AuthRequest } from "../middleware/auth.js";

const router = Router();
router.use(requireAuth);
const id = z.string().cuid();
const applicantRoles: Role[] = [Role.STUDENT, Role.TEACHER];
const administratorRoles: Role[] = [Role.SUPER_ADMIN, Role.BRANCH_ADMIN];
const requestInput = z.object({ fromDate: z.coerce.date(), toDate: z.coerce.date(), reason: z.string().trim().min(3).max(2000), leaveType: z.nativeEnum(LeaveType).default(LeaveType.FULL_DAY), halfDaySession: z.nativeEnum(HalfDaySession).nullable().optional(), attachment: z.object({ name: z.string().trim().min(1).max(180), mimeType: z.enum(["application/pdf", "image/jpeg", "image/png"]), base64: z.string().min(1) }).nullable().optional() });
const day = (value: Date) => new Date(Date.UTC(value.getUTCFullYear(), value.getUTCMonth(), value.getUTCDate()));
async function branch(req: AuthRequest) { if (req.auth!.role === Role.STUDENT) return (await prisma.studentProfile.findUnique({ where: { userId: req.auth!.userId }, select: { branchId: true } }))?.branchId; if (req.auth!.role === Role.TEACHER) return (await prisma.teacherProfile.findUnique({ where: { userId: req.auth!.userId }, select: { branchId: true } }))?.branchId; return undefined; }
function attachment(value: z.infer<typeof requestInput>["attachment"]) { if (!value) return {}; const data = decodeVerifiedUpload(value.base64, value.mimeType, 5 * 1024 * 1024); return { attachmentName: value.name, attachmentMime: value.mimeType, attachmentData: data }; }
async function access(req: AuthRequest, branchId: string) { if (req.auth!.role !== Role.BRANCH_ADMIN) return; if (!await prisma.branchUser.findFirst({ where: { userId: req.auth!.userId, branchId } })) throw new AppError(403, "BRANCH_FORBIDDEN", "Branch access denied"); }

router.post("/portal/leaves", async (req: AuthRequest, res) => { if (!applicantRoles.includes(req.auth!.role)) throw new AppError(403, "APPLICANT_ROLE_REQUIRED", "Student or teacher access is required"); const data = requestInput.parse(req.body); const fromDate = day(data.fromDate), toDate = day(data.toDate); if (toDate < fromDate) throw new AppError(422, "INVALID_DATES", "End date must be on or after start date"); if (data.leaveType === LeaveType.HALF_DAY && (!data.halfDaySession || fromDate.getTime() !== toDate.getTime())) throw new AppError(422, "INVALID_HALF_DAY", "Half-day leave requires one date and a half-day session"); if (data.leaveType === LeaveType.SHORT_LEAVE && fromDate.getTime() !== toDate.getTime()) throw new AppError(422, "INVALID_SHORT_LEAVE", "Short leave must use one date"); if (data.leaveType !== LeaveType.HALF_DAY && data.halfDaySession) throw new AppError(422, "INVALID_HALF_DAY_SESSION", "A half-day session is only valid for half-day leave"); const branchId = await branch(req); if (!branchId) throw new AppError(422, "BRANCH_REQUIRED", "A linked branch is required"); const overlap = await prisma.leaveRequest.findFirst({ where: { userId: req.auth!.userId, status: { in: [LeaveRequestStatus.PENDING, LeaveRequestStatus.APPROVED] }, fromDate: { lte: toDate }, toDate: { gte: fromDate } } }); if (overlap) throw new AppError(409, "OVERLAPPING_LEAVE", "An active leave request overlaps these dates"); const { attachment: file, ...rest } = data; res.status(201).json({ data: await prisma.leaveRequest.create({ data: { ...rest, fromDate, toDate, userId: req.auth!.userId, branchId, ...attachment(file) } }) }); });
router.delete("/portal/leaves/:leaveId", async (req: AuthRequest, res) => { const leave = await prisma.leaveRequest.findFirst({ where: { id: id.parse(req.params.leaveId), userId: req.auth!.userId } }); if (!leave) throw new AppError(404, "LEAVE_NOT_FOUND", "Leave request not found"); if (leave.status !== LeaveRequestStatus.PENDING) throw new AppError(409, "LEAVE_LOCKED", "Only pending leave requests can be cancelled"); res.json({ data: await prisma.leaveRequest.update({ where: { id: leave.id }, data: { status: LeaveRequestStatus.CANCELLED } }) }); });

router.get("/admin/leaves", async (req: AuthRequest, res) => { if (!administratorRoles.includes(req.auth!.role)) throw new AppError(403, "ADMIN_REQUIRED", "Administrator access is required"); const q = z.object({ page: z.coerce.number().int().positive().default(1), limit: z.coerce.number().int().min(1).max(100).default(20), branchId: id.optional(), status: z.nativeEnum(LeaveRequestStatus).optional(), applicantRole: z.enum([Role.STUDENT, Role.TEACHER]).optional(), search: z.string().trim().optional() }).parse(req.query); if (q.branchId) await access(req, q.branchId); const branchIds = req.auth!.role === Role.BRANCH_ADMIN ? (await prisma.branchUser.findMany({ where: { userId: req.auth!.userId }, select: { branchId: true } })).map(x => x.branchId) : undefined; const where = { ...(branchIds ? { branchId: { in: branchIds } } : {}), ...(q.branchId ? { branchId: q.branchId } : {}), ...(q.status ? { status: q.status } : {}), ...(q.applicantRole ? { user: { role: q.applicantRole } } : {}), ...(q.search ? { OR: [{ user: { name: { contains: q.search, mode: "insensitive" as const } } }, { reason: { contains: q.search, mode: "insensitive" as const } }] } : {}) }; const [data, total] = await prisma.$transaction([prisma.leaveRequest.findMany({ where, include: { user: { select: { id: true, name: true, role: true } }, branch: { select: { id: true, branchName: true } }, approvedBy: { select: { id: true, name: true } } }, skip: (q.page - 1) * q.limit, take: q.limit, orderBy: { createdAt: "desc" } }), prisma.leaveRequest.count({ where })]); res.json({ data, meta: { total, page: q.page, limit: q.limit, totalPages: Math.max(1, Math.ceil(total / q.limit)) } }); });
router.patch("/admin/leaves/:leaveId/decision", async (req: AuthRequest, res) => { if (!administratorRoles.includes(req.auth!.role)) throw new AppError(403, "ADMIN_REQUIRED", "Administrator access is required"); const data = z.object({ status: z.enum([LeaveRequestStatus.APPROVED, LeaveRequestStatus.REJECTED]), remarks: z.string().trim().max(2000).nullable().optional() }).parse(req.body), leave = await prisma.leaveRequest.findUnique({ where: { id: id.parse(req.params.leaveId) }, include: { user: { include: { studentProfile: true, teacherProfile: true } } } }); if (!leave) throw new AppError(404, "LEAVE_NOT_FOUND", "Leave request not found"); await access(req, leave.branchId); if (leave.status !== LeaveRequestStatus.PENDING) throw new AppError(409, "LEAVE_ALREADY_DECIDED", "Only pending requests can be approved or rejected"); const result = await prisma.$transaction(async tx => { const updated = await tx.leaveRequest.update({ where: { id: leave.id }, data: { status: data.status, remarks: data.remarks, approvedById: req.auth!.userId, approvedAt: new Date() } }); if (data.status === LeaveRequestStatus.APPROVED) { const attendanceStatus = leave.leaveType === LeaveType.FULL_DAY ? AttendanceStatus.FULL_DAY_LEAVE : leave.leaveType === LeaveType.HALF_DAY ? AttendanceStatus.HALF_DAY_LEAVE : AttendanceStatus.SHORT_LEAVE; for (let date = day(leave.fromDate); date <= day(leave.toDate); date = new Date(date.getTime() + 86_400_000)) { const remarks = `Approved ${leave.leaveType.toLowerCase().replaceAll("_", " ")}${leave.halfDaySession ? ` (${leave.halfDaySession.toLowerCase().replaceAll("_", " ")})` : ""}: ${leave.reason}`; if (leave.user.studentProfile) { const key = { studentId: leave.userId, batchId: leave.user.studentProfile.batchId, date }, existing = await tx.attendance.findUnique({ where: { studentId_batchId_date: key } }); assertLeaveAttendanceCompatible(existing?.status ?? null, attendanceStatus, "Student", date); if (!existing) await tx.attendance.create({ data: { ...key, status: attendanceStatus, remarks, markedById: req.auth!.userId } }); else if (existing.status !== attendanceStatus) await tx.attendance.update({ where: { id: existing.id }, data: { status: attendanceStatus, remarks, markedById: req.auth!.userId } }); } if (leave.user.teacherProfile) { const teacherId = leave.user.teacherProfile.id, existing = await tx.teacherAttendance.findUnique({ where: { teacherId_date: { teacherId, date } } }); assertLeaveAttendanceCompatible(existing?.status ?? null, attendanceStatus, "Teacher", date); if (!existing) await tx.teacherAttendance.create({ data: { teacherId, date, status: attendanceStatus, remarks, markedById: req.auth!.userId } }); else if (existing.status !== attendanceStatus) await tx.teacherAttendance.update({ where: { id: existing.id }, data: { status: attendanceStatus, remarks, markedById: req.auth!.userId } }); } } } return updated; }); res.json({ data: result }); });

export default router;
