const labels: Record<string, string> = {
  UNIT_TEST: "Unit Test",
  MID_TERM: "Mid Term",
  FINAL: "Final",
  PRACTICAL: "Practical",
  MOCK: "Mock",
  OTHER: "Other",
  DRAFT: "Draft",
  SCHEDULED: "Scheduled",
  COMPLETED: "Completed",
  RESULTS_PUBLISHED: "Results Published",
  ARCHIVED: "Archived",
  FULL_DAY: "Full Day",
  HALF_DAY: "Half Day",
  SHORT_LEAVE: "Short Leave",
  FIRST_HALF: "First Half",
  SECOND_HALF: "Second Half",
  IN_PROGRESS: "In Progress",
  FOLLOW_UP: "Follow Up",
  NOT_INTERESTED: "Not Interested",
  PAST_DUE: "Past Due",
  PENDING: "Pending",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  CANCELLED: "Cancelled",
  NEW: "New",
  CONTACTED: "Contacted",
  INTERESTED: "Interested",
  CONVERTED: "Converted",
  CLOSED: "Closed",
  LOW: "Low",
  MEDIUM: "Medium",
  HIGH: "High",
  URGENT: "Urgent",
  SUPER_ADMIN: "Super Admin",
  BRANCH_ADMIN: "Branch Admin",
  ACCOUNTANT: "Accountant",
  STUDENT: "Student",
  TEACHER: "Teacher",
  PARENT: "Parent",
  EMPLOYEE: "Employee",
};

export function displayLabel(value: string) {
  return labels[value] ?? value;
}
