"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  Camera, CameraOff, Circle, Download, Eraser, Hand, Lock, LogOut, MessageSquare,
  Mic, MicOff, MonitorUp, PenLine, Radio, Save, ShieldCheck, Square, Unlock, UserMinus, Users,
} from "lucide-react";
import { errorMessage, getAccessToken, useAuth } from "./auth-provider";
import { openAuthenticatedDocument } from "./authenticated-download";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api/v1";
const LIVEKIT_SCRIPT="https://cdn.jsdelivr.net/npm/livekit-client@2.22.3/dist/livekit-client.umd.min.js";
type Stroke={surface:"whiteboard"|"annotation";x1:number;y1:number;x2:number;y2:number;color:string;width:number;mode:"pen"|"erase";strokeId:string};
type Session={serverUrl:string;participantToken:string;meeting:{id:string;title:string;description?:string|null;startsAt:string;endsAt:string;type:string;recordingStatus?:string|null};meetingRole:string;manager:boolean;locked:boolean;settings:{allowChat:boolean;allowWhiteboard:boolean;allowAnnotation:boolean;allowScreenShare:boolean;allowParticipantMic:boolean;allowParticipantCamera:boolean};recordingConfigured:boolean;recordingAvailable:boolean;recordings:Array<{id:string;status:string;startedAt?:string|null;stoppedAt?:string|null;durationSeconds:number;available:boolean}>;whiteboardData:Stroke[]};
type Participant={identity:string;name:string;micTrackSid?:string;hand?:boolean};
type Chat={id:string;name:string;text:string;at:number;self?:boolean};
async function api(path:string,init?:RequestInit){const r=await fetch(API+path,{...init,headers:{Authorization:`Bearer ${getAccessToken()??""}`,...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers}});const j=await r.json().catch(()=>null);if(!r.ok)throw new Error(j?.error?.message??"Request failed");return j}
async function loadLiveKit(){if(typeof window==="undefined")return null;const existing=(window as any).LivekitClient;if(existing)return existing;await new Promise<void>((resolve,reject)=>{const old=document.querySelector<HTMLScriptElement>(`script[src="${LIVEKIT_SCRIPT}"]`);if(old){old.addEventListener("load",()=>resolve(),{once:true});old.addEventListener("error",()=>reject(new Error("Unable to load LiveKit")),{once:true});return}const s=document.createElement("script");s.src=LIVEKIT_SCRIPT;s.async=true;s.crossOrigin="anonymous";s.onload=()=>resolve();s.onerror=()=>reject(new Error("Unable to load meeting media engine"));document.head.appendChild(s)});return (window as any).LivekitClient}

export function NativeMeetingRoom({roomName}:{roomName:string}){
 const {user}=useAuth();const[session,setSession]=useState<Session|null>(null),[room,setRoom]=useState<any>(null),[loading,setLoading]=useState(true),[joining,setJoining]=useState(false),[joined,setJoined]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const[mic,setMic]=useState(false),[cam,setCam]=useState(false),[screen,setScreen]=useState(false),[locked,setLocked]=useState(false),[recording,setRecording]=useState(false),[participants,setParticipants]=useState<Participant[]>([]),[chat,setChat]=useState<Chat[]>([]),[chatText,setChatText]=useState(""),[hand,setHand]=useState(false),[hands,setHands]=useState<Record<string,boolean>>({});
 const[panel,setPanel]=useState<"meeting"|"whiteboard">("meeting"),[drawMode,setDrawMode]=useState<"pen"|"erase">("pen"),[annotation,setAnnotation]=useState(false),[annotationMode,setAnnotationMode]=useState<"pen"|"erase">("pen");
 const mediaRef=useRef<HTMLDivElement>(null),audioRef=useRef<HTMLDivElement>(null),whiteboardRef=useRef<HTMLCanvasElement>(null),annotationRef=useRef<HTMLCanvasElement>(null),strokesRef=useRef<Stroke[]>([]),drawingRef=useRef<{surface:Stroke["surface"];x:number;y:number;strokeId:string}|null>(null);
 const manager=Boolean(session?.manager),observer=session?.meetingRole==="OBSERVER";
 useEffect(()=>{let active=true;setLoading(true);api(`/meetings/native/${encodeURIComponent(roomName)}/session`,{method:"POST",body:"{}"}).then(r=>{if(!active)return;setSession(r.data);setLocked(Boolean(r.data.locked));strokesRef.current=Array.isArray(r.data.whiteboardData)?r.data.whiteboardData:[]}).catch(e=>active&&setError(errorMessage(e))).finally(()=>active&&setLoading(false));return()=>{active=false}},[roomName]);

 const resize=useCallback((canvas:HTMLCanvasElement|null)=>{if(!canvas)return;const w=Math.max(1,Math.floor(canvas.clientWidth)),h=Math.max(1,Math.floor(canvas.clientHeight));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}},[]);
 const draw=useCallback((stroke:Stroke)=>{const canvas=stroke.surface==="whiteboard"?whiteboardRef.current:annotationRef.current;if(!canvas)return;resize(canvas);const ctx=canvas.getContext("2d");if(!ctx)return;ctx.save();ctx.globalCompositeOperation=stroke.mode==="erase"?"destination-out":"source-over";ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle=stroke.color;ctx.lineWidth=stroke.width;ctx.beginPath();ctx.moveTo(stroke.x1*canvas.width,stroke.y1*canvas.height);ctx.lineTo(stroke.x2*canvas.width,stroke.y2*canvas.height);ctx.stroke();ctx.restore()},[resize]);
 const redraw=useCallback((surface:Stroke["surface"])=>{const canvas=surface==="whiteboard"?whiteboardRef.current:annotationRef.current;if(!canvas)return;resize(canvas);canvas.getContext("2d")?.clearRect(0,0,canvas.width,canvas.height);strokesRef.current.filter(s=>s.surface===surface).forEach(draw)},[draw,resize]);
 useEffect(()=>{const f=()=>{redraw("whiteboard");redraw("annotation")};window.addEventListener("resize",f);const t=window.setTimeout(f,100);return()=>{clearTimeout(t);window.removeEventListener("resize",f)}},[redraw,panel,annotation]);

 const publish=useCallback(async(payload:any,reliable=true)=>{if(!room)return;await room.localParticipant.publishData(new TextEncoder().encode(JSON.stringify(payload)),{reliable})},[room]);
 const refresh=useCallback((r:any)=>{if(!r)return;const all=[r.localParticipant,...Array.from(r.remoteParticipants?.values?.()??[])] as any[];setParticipants(all.map(p=>{const pubs=Array.from(p.trackPublications?.values?.()??[]) as any[];const micPub=pubs.find(x=>String(x.source??"").toLowerCase().includes("microphone")||String(x.kind??"").toLowerCase().includes("audio"));return{identity:p.identity,name:p.name||(p.identity===r.localParticipant.identity?user?.name??"You":"Participant"),micTrackSid:micPub?.trackSid??micPub?.sid,hand:Boolean(hands[p.identity])}}))},[hands,user?.name]);
 const rebuild=useCallback((r:any)=>{const target=mediaRef.current;if(!target||!r)return;target.innerHTML="";const all=[r.localParticipant,...Array.from(r.remoteParticipants?.values?.()??[])] as any[];for(const p of all){const pubs=Array.from(p.trackPublications?.values?.()??[]) as any[];const vids=pubs.filter(pub=>pub.track&&String(pub.kind??pub.track?.kind??"").toLowerCase().includes("video"));if(!vids.length){const card=document.createElement("div");card.className="grid min-h-44 place-items-center rounded-2xl bg-slate-900 p-4 text-center";card.textContent=p.name||"Participant";target.appendChild(card);continue}for(const pub of vids){const el=pub.track.attach();el.className="min-h-44 w-full rounded-2xl bg-black object-contain";const wrap=document.createElement("div");wrap.className="overflow-hidden rounded-2xl bg-black";wrap.appendChild(el);target.appendChild(wrap)}}refresh(r)},[refresh]);
 const handleData=useCallback((payload:Uint8Array,participant:any)=>{try{const data=JSON.parse(new TextDecoder().decode(payload));const name=participant?.name||"Participant";if(data.type==="chat"){setChat(v=>[...v,{id:crypto.randomUUID(),name,text:String(data.text??""),at:Number(data.at??Date.now())}].slice(-200));return}if(data.type==="raise-hand"){setHands(v=>({...v,[participant?.identity??data.identity]:Boolean(data.raised)}));return}if(data.type==="stroke"&&data.stroke){const stroke=data.stroke as Stroke;strokesRef.current.push(stroke);draw(stroke);return}if(data.type==="clear"){strokesRef.current=strokesRef.current.filter(s=>s.surface!==data.surface);redraw(data.surface)}}catch{}},[draw,redraw]);

 async function join(){if(!session||joined)return;setJoining(true);setError("");try{const lk=await loadLiveKit();if(!lk)throw new Error("Meeting media engine unavailable");const r=new lk.Room({adaptiveStream:true,dynacast:true});r.on(lk.RoomEvent.TrackSubscribed,(track:any)=>{if(String(track.kind).toLowerCase().includes("audio"))audioRef.current?.appendChild(track.attach());setTimeout(()=>rebuild(r),0)}).on(lk.RoomEvent.TrackUnsubscribed,(track:any)=>{track.detach();setTimeout(()=>rebuild(r),0)}).on(lk.RoomEvent.ParticipantConnected,()=>setTimeout(()=>rebuild(r),0)).on(lk.RoomEvent.ParticipantDisconnected,()=>setTimeout(()=>rebuild(r),0)).on(lk.RoomEvent.LocalTrackPublished,()=>setTimeout(()=>rebuild(r),0)).on(lk.RoomEvent.LocalTrackUnpublished,()=>setTimeout(()=>rebuild(r),0)).on(lk.RoomEvent.DataReceived,handleData).on(lk.RoomEvent.Disconnected,()=>{void api(`/meetings/native/${encodeURIComponent(roomName)}/leave`,{method:"POST",body:"{}"}).catch(()=>undefined);setRoom(null);setJoined(false);setMic(false);setCam(false);setScreen(false)});await Promise.race([r.connect(session.serverUrl,session.participantToken),new Promise((_,reject)=>setTimeout(()=>reject(new Error("Meeting connection timed out")),20_000))]);await api(`/meetings/native/${encodeURIComponent(roomName)}/join`,{method:"POST",body:"{}"});setRoom(r);setJoined(true);setTimeout(()=>{rebuild(r);redraw("whiteboard")},50)}catch(e){setError(errorMessage(e))}finally{setJoining(false)}}
 async function leave(){try{await api(`/meetings/native/${encodeURIComponent(roomName)}/leave`,{method:"POST",body:"{}"})}catch{}room?.disconnect?.();setRoom(null);setJoined(false)}
 useEffect(()=>()=>{room?.disconnect?.()},[room]);
 useEffect(()=>{if(!joined)return;const close=()=>{void fetch(`${API}/meetings/native/${encodeURIComponent(roomName)}/leave`,{method:"POST",keepalive:true,headers:{Authorization:`Bearer ${getAccessToken()??""}`,"Content-Type":"application/json"},body:"{}"}).catch(()=>undefined)};window.addEventListener("pagehide",close);return()=>window.removeEventListener("pagehide",close)},[joined,roomName]);

 async function toggleMic(){if(!room||observer)return;try{const next=!mic;await room.localParticipant.setMicrophoneEnabled(next);setMic(next);rebuild(room)}catch(e){setError(errorMessage(e))}}
 async function toggleCam(){if(!room||observer)return;try{const next=!cam;await room.localParticipant.setCameraEnabled(next);setCam(next);rebuild(room)}catch(e){setError(errorMessage(e))}}
 async function toggleScreen(){if(!room||observer||!session?.settings.allowScreenShare)return;try{const next=!screen;await room.localParticipant.setScreenShareEnabled(next);setScreen(next);rebuild(room)}catch(e){setError(errorMessage(e))}}
 async function sendChat(){const text=chatText.trim();if(!text||!session?.settings.allowChat)return;const at=Date.now();await publish({type:"chat",text,at},true);setChat(v=>[...v,{id:crypto.randomUUID(),name:user?.name??"You",text,at,self:true}].slice(-200));setChatText("");void api(`/meetings/native/${encodeURIComponent(roomName)}/interactions`,{method:"POST",body:JSON.stringify({type:"CHAT",content:{text}})}).catch(()=>undefined)}
 async function toggleHand(){const raised=!hand;setHand(raised);setHands(v=>({...v,[user?.id??"local"]:raised}));await publish({type:"raise-hand",raised,identity:user?.id},true);void api(`/meetings/native/${encodeURIComponent(roomName)}/interactions`,{method:"POST",body:JSON.stringify({type:"RAISE_HAND",content:{raised}})}).catch(()=>undefined)}

 function point(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
 function startDraw(surface:Stroke["surface"],e:React.PointerEvent<HTMLCanvasElement>){if(!joined||observer)return;if(surface==="whiteboard"&&!session?.settings.allowWhiteboard)return;if(surface==="annotation"&&!session?.settings.allowAnnotation)return;e.currentTarget.setPointerCapture(e.pointerId);const p=point(e);drawingRef.current={surface,...p,strokeId:crypto.randomUUID()}}
 async function moveDraw(surface:Stroke["surface"],e:React.PointerEvent<HTMLCanvasElement>){const prev=drawingRef.current;if(!prev||prev.surface!==surface)return;const p=point(e),mode=surface==="annotation"?annotationMode:drawMode;const stroke:Stroke={surface,x1:prev.x,y1:prev.y,x2:p.x,y2:p.y,color:surface==="annotation"?"#ef4444":"#0f172a",width:mode==="erase"?24:surface==="annotation"?5:3,mode,strokeId:prev.strokeId};drawingRef.current={surface,...p,strokeId:prev.strokeId};strokesRef.current.push(stroke);draw(stroke);await publish({type:"stroke",stroke},false)}
 function endDraw(){drawingRef.current=null}
 async function clear(surface:Stroke["surface"]){if(!manager)return;strokesRef.current=strokesRef.current.filter(s=>s.surface!==surface);redraw(surface);await publish({type:"clear",surface},true)}
 async function saveWhiteboard(){if(!manager)return;try{await api(`/meetings/native/${encodeURIComponent(roomName)}/whiteboard`,{method:"PUT",body:JSON.stringify({strokes:strokesRef.current.filter(s=>s.surface==="whiteboard")})});setNotice("Whiteboard saved.")}catch(e){setError(errorMessage(e))}}

 async function control(action:string,identity?:string,trackSid?:string){try{const r=await api(`/meetings/native/${encodeURIComponent(roomName)}/control`,{method:"POST",body:JSON.stringify({action,identity,trackSid})});if(action==="LOCK"||action==="UNLOCK")setLocked(Boolean(r.data.locked));setNotice(action.replaceAll("_"," ").toLowerCase())}catch(e){setError(errorMessage(e))}}
 async function startRecording(){try{await api(`/meetings/native/${encodeURIComponent(roomName)}/recording/start`,{method:"POST",body:"{}"});setRecording(true);setNotice("Recording started. All participants should be informed that the meeting is being recorded.")}catch(e){setError(errorMessage(e))}}
 async function stopRecording(){try{await api(`/meetings/native/${encodeURIComponent(roomName)}/recording/stop`,{method:"POST",body:"{}"});setRecording(false);setNotice("Recording is processing.");const s=await api(`/meetings/native/${encodeURIComponent(roomName)}/session`,{method:"POST",body:"{}"});setSession(s.data)}catch(e){setError(errorMessage(e))}}
 async function downloadRecording(id:string){try{await openAuthenticatedDocument({url:`${API}/meetings/native/${encodeURIComponent(roomName)}/recordings/${id}`,token:getAccessToken()??"",fileName:`${session?.meeting.title??"meeting"}-recording.mp4`,fallbackError:"Recording is not available yet"})}catch(e){setError(errorMessage(e))}}
 async function endMeeting(){if(!manager||!confirm("End this meeting for everyone?"))return;try{await api(`/meetings/native/${encodeURIComponent(roomName)}/end`,{method:"POST",body:"{}"});room?.disconnect?.();setJoined(false);setNotice("Meeting ended.")}catch(e){setError(errorMessage(e))}}

 const scheduled=useMemo(()=>session?Math.max(0,Math.round((new Date(session.meeting.endsAt).getTime()-new Date(session.meeting.startsAt).getTime())/60000)):0,[session]);
 if(loading)return <div className="grid min-h-screen place-items-center bg-slate-950 text-white">Loading meeting…</div>;
 if(!session)return <div className="grid min-h-screen place-items-center bg-slate-950 p-6 text-white"><div className="max-w-lg rounded-2xl border border-red-400/30 bg-red-950/50 p-6"><h1 className="text-xl font-bold">Unable to open meeting</h1><p className="mt-2 text-sm text-red-100">{error||"Meeting session unavailable."}</p></div></div>;
 if(!joined)return <div className="min-h-screen bg-slate-950 p-5 text-white"><div className="mx-auto grid max-w-5xl gap-5 lg:grid-cols-[1.4fr_.8fr]"><section className="rounded-3xl border border-white/10 bg-slate-900 p-7"><div className="flex items-center gap-2 text-blue-300"><ShieldCheck size={18}/><span className="text-xs font-bold uppercase tracking-wider">Native Staff Meeting</span></div><h1 className="mt-3 text-3xl font-black">{session.meeting.title}</h1><p className="mt-2 text-slate-300">{session.meeting.description||"Enterprise staff collaboration room."}</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Info label="Role" value={session.meetingRole.replaceAll("_"," ")}/><Info label="Duration" value={`${scheduled} min scheduled`}/><Info label="Room" value={locked?"Locked":"Open"}/></div>{session.recordingConfigured&&<p className="mt-4 rounded-xl bg-amber-950/60 p-3 text-sm text-amber-200">This meeting supports cloud recording. A visible recording indicator will appear while recording is active.</p>}{error&&<p className="mt-4 rounded-xl bg-red-950 p-3 text-sm text-red-200">{error}</p>}<div className="mt-6 flex flex-wrap gap-3">{session.recordings.filter(x=>x.available).map(r=><button key={r.id} onClick={()=>void downloadRecording(r.id)} className="inline-flex items-center gap-2 rounded-xl border border-white/20 px-4 py-3 font-semibold"><Download size={16}/>Recording</button>)}<button onClick={()=>void join()} disabled={joining||locked&&!manager} className="rounded-xl bg-blue-600 px-5 py-3 font-bold disabled:opacity-50">{joining?"Joining…":locked&&!manager?"Meeting locked":"Join Meeting"}</button></div></section><aside className="rounded-3xl border border-white/10 bg-slate-900 p-6"><h2 className="font-bold">Meeting capabilities</h2><div className="mt-4 space-y-3 text-sm text-slate-300">{["Camera & microphone","Screen sharing","Whiteboard & annotation","Chat & raise hand","Host/co-host moderation","Join/leave attendance",session.recordingConfigured?"Cloud recording enabled":"Recording unavailable"].map(x=><div key={x} className="flex items-center gap-2"><Circle size={8} className="fill-current text-blue-400"/>{x}</div>)}</div></aside></div></div>;
 return <div className="min-h-screen bg-slate-950 text-white"><header className="flex flex-col gap-3 border-b border-white/10 bg-slate-900 px-4 py-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-300">Native Staff Meeting</p><h1 className="text-lg font-bold">{session.meeting.title}</h1></div><div className="flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full bg-slate-800 px-3 py-1.5">{participants.length} participants</span>{locked&&<span className="rounded-full bg-amber-950 px-3 py-1.5 text-amber-200">Locked</span>}{recording&&<span className="inline-flex items-center gap-1 rounded-full bg-red-950 px-3 py-1.5 text-red-300"><Circle size={9} className="fill-current"/>Recording</span>}</div></header>
 {error&&<div className="mx-4 mt-3 rounded-xl bg-red-950 p-3 text-sm text-red-200">{error}</div>}{notice&&<div className="mx-4 mt-3 rounded-xl bg-blue-950 p-3 text-sm text-blue-200">{notice}</div>}
 <div className="grid min-h-[calc(100vh-74px)] lg:grid-cols-[1fr_340px]"><main className="relative min-w-0 p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div className="flex gap-2"><button onClick={()=>setPanel("meeting")} className={`rounded-xl px-4 py-2 text-sm font-semibold ${panel==="meeting"?"bg-blue-600":"bg-slate-800"}`}>Meeting</button>{session.settings.allowWhiteboard&&<button onClick={()=>{setPanel("whiteboard");setTimeout(()=>redraw("whiteboard"),30)}} className={`rounded-xl px-4 py-2 text-sm font-semibold ${panel==="whiteboard"?"bg-blue-600":"bg-slate-800"}`}>Whiteboard</button>}</div>{manager&&<div className="flex gap-2"><button onClick={()=>void control(locked?"UNLOCK":"LOCK")} className="rounded-xl bg-slate-800 p-2">{locked?<Unlock size={17}/>:<Lock size={17}/>}</button><button onClick={()=>void endMeeting()} className="rounded-xl bg-red-700 px-3 py-2 text-sm font-bold">End meeting</button></div>}</div>
 <div className={panel==="meeting"?"block":"hidden"}><div ref={mediaRef} className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"/>{session.settings.allowAnnotation&&<div className="mt-3"><button onClick={()=>{setAnnotation(v=>!v);setTimeout(()=>redraw("annotation"),30)}} className={`rounded-lg px-3 py-2 text-xs font-bold ${annotation?"bg-red-600":"bg-slate-800"}`}><PenLine size={14} className="mr-1 inline"/>Annotation</button></div>}{annotation&&<div className="pointer-events-none absolute inset-4 top-20"><canvas ref={annotationRef} className="pointer-events-auto h-[65vh] w-full rounded-2xl" onPointerDown={e=>startDraw("annotation",e)} onPointerMove={e=>void moveDraw("annotation",e)} onPointerUp={endDraw} onPointerCancel={endDraw}/><div className="pointer-events-auto absolute left-3 top-3 flex gap-2 rounded-xl bg-slate-950/80 p-2"><button onClick={()=>setAnnotationMode("pen")} className="p-2"><PenLine size={15}/></button><button onClick={()=>setAnnotationMode("erase")} className="p-2"><Eraser size={15}/></button>{manager&&<button onClick={()=>void clear("annotation")} className="p-2"><Square size={15}/></button>}</div></div>}</div>
 <div className={panel==="whiteboard"?"block":"hidden"}><div className="mb-2 flex gap-2"><button onClick={()=>setDrawMode("pen")} className="rounded-lg bg-slate-800 p-2"><PenLine size={16}/></button><button onClick={()=>setDrawMode("erase")} className="rounded-lg bg-slate-800 p-2"><Eraser size={16}/></button>{manager&&<><button onClick={()=>void saveWhiteboard()} className="inline-flex items-center gap-1 rounded-lg bg-slate-800 px-3 py-2 text-xs font-bold"><Save size={15}/>Save</button><button onClick={()=>void clear("whiteboard")} className="rounded-lg bg-slate-800 px-3 py-2 text-xs font-bold">Clear</button></>}</div><canvas ref={whiteboardRef} className="h-[68vh] w-full touch-none rounded-2xl bg-white" onPointerDown={e=>startDraw("whiteboard",e)} onPointerMove={e=>void moveDraw("whiteboard",e)} onPointerUp={endDraw} onPointerCancel={endDraw}/></div>
 <div className="fixed bottom-4 left-1/2 z-30 flex max-w-[95vw] -translate-x-1/2 flex-wrap justify-center gap-2 rounded-2xl border border-white/10 bg-slate-900/95 p-2 shadow-2xl">{!observer&&<><Control onClick={()=>void toggleMic()} active={mic} icon={mic?<Mic/>:<MicOff/>} label="Mic"/><Control onClick={()=>void toggleCam()} active={cam} icon={cam?<Camera/>:<CameraOff/>} label="Camera"/>{session.settings.allowScreenShare&&<Control onClick={()=>void toggleScreen()} active={screen} icon={<MonitorUp/>} label="Share"/>}<Control onClick={()=>void toggleHand()} active={hand} icon={<Hand/>} label="Hand"/></>} {manager&&session.recordingConfigured&&<Control onClick={()=>void(recording?stopRecording():startRecording())} active={recording} icon={<Radio/>} label={recording?"Stop rec":"Record"}/>}<Control onClick={()=>void leave()} icon={<LogOut/>} label="Leave"/></div></main>
 <aside className="border-l border-white/10 bg-slate-900 p-4"><div className="flex items-center gap-2"><Users size={18}/><h2 className="font-bold">Participants</h2></div><div className="mt-3 max-h-64 space-y-2 overflow-y-auto">{participants.map(p=><div key={p.identity} className="rounded-xl bg-slate-800 p-3"><div className="flex items-center justify-between gap-2"><div><b className="text-sm">{p.name}</b>{hands[p.identity]&&<span className="ml-2 text-amber-300">✋</span>}</div>{manager&&p.identity!==user?.id&&<div className="flex gap-1">{p.micTrackSid&&<button onClick={()=>void control("MUTE_TRACK",p.identity,p.micTrackSid)} className="rounded p-1 text-amber-300" title="Mute"><MicOff size={14}/></button>}<button onClick={()=>void control("REMOVE_PARTICIPANT",p.identity)} className="rounded p-1 text-red-300" title="Remove"><UserMinus size={14}/></button></div>}</div></div>)}</div><div className="mt-5 flex items-center gap-2"><MessageSquare size={18}/><h2 className="font-bold">Chat</h2></div><div className="mt-3 h-[42vh] overflow-y-auto rounded-xl bg-slate-950 p-3"><div className="space-y-2">{chat.map(m=><div key={m.id} className={`rounded-xl p-2 text-sm ${m.self?"bg-blue-950":"bg-slate-800"}`}><b className="text-xs">{m.name}</b><p>{m.text}</p></div>)}</div></div>{session.settings.allowChat&&!observer&&<div className="mt-2 flex gap-2"><input value={chatText} onChange={e=>setChatText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void sendChat()}}} placeholder="Message" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm"/><button onClick={()=>void sendChat()} className="rounded-xl bg-blue-600 px-3 font-bold">Send</button></div>}</aside></div><div ref={audioRef} className="hidden"/></div>
}
function Control({icon,label,active,onClick}:{icon:React.ReactNode;label:string;active?:boolean;onClick:()=>void}){return <button onClick={onClick} className={`inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold ${active?"bg-blue-600":"bg-slate-800"}`}>{icon}<span className="hidden sm:inline">{label}</span></button>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-950 p-3"><small className="text-slate-400">{label}</small><p className="mt-1 font-bold">{value}</p></div>}
