"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Award, BadgeCheck, BookOpen, Check, MessageCircle, Play, Sparkles, Star, Trophy, Users, X } from "lucide-react";
import { SiteHeader } from "./site-header";
import { CourseCard, type Course } from "./course-card";
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api/v1";
const WHATSAPP_NUMBER = process.env.NEXT_PUBLIC_WHATSAPP_NUMBER?.replace(/\D/g, "");

const faculty = [{ name: "Dr. Ananya Sharma", role: "Physics · IIT Delhi", initials: "AS" }, { name: "Priya Mehta", role: "Biology · 12 years", initials: "PM" }, { name: "Arjun Rao", role: "Mathematics · IIT Bombay", initials: "AR" }];
const stories = [{ score: "AIR 128", name: "Aarav", exam: "JEE Advanced" }, { score: "695/720", name: "Meera", exam: "NEET" }, { score: "99.2%", name: "Riya", exam: "CBSE XII" }];

export function PremiumLanding({ courses }: { courses: Course[] }) {
  const [open, setOpen] = useState(false), [sent, setSent] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function submit(formData: FormData) { setBusy(true); setError(""); try { const response=await fetch(`${API}/premium/leads`, { method: "POST", headers:{"content-type":"application/json"}, body: JSON.stringify({ name: formData.get("name"), mobile: formData.get("mobile"), email: formData.get("email") || undefined, targetExam: formData.get("targetExam"), demoAt: formData.get("demoAt") || undefined, trialRequested: true, emiRequested: formData.get("emi") === "on", couponCode: formData.get("coupon") || undefined, referralCode: formData.get("referral") || undefined }) }); const payload=await response.json(); if(!response.ok) throw new Error(payload?.error?.message??"Unable to book your demo"); setSent(true); } catch (e) { setError(e instanceof Error ? e.message : "Unable to book your demo"); } finally { setBusy(false); } }
  return <div className="premium-page"><SiteHeader /><main id="main-content">
    <section className="hero-grid overflow-hidden"><div className="container-page grid min-h-[680px] items-center gap-14 py-16 lg:grid-cols-[1.08fr_.92fr]"><div className="hero-reveal"><div className="pill inline-flex items-center gap-2"><Sparkles size={14}/> Admissions open · Scholarships up to 100%</div><h1 className="mt-6 max-w-3xl text-5xl font-black leading-[.98] tracking-[-.045em] sm:text-7xl">Your ambition.<br/><span className="gradient-text">Made unstoppable.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">India’s focused digital coaching ecosystem for CBSE, JEE, NEET and CUET—with brilliant teachers, personal mentoring and AI-powered practice.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => setOpen(true)} className="premium-cta">Book a free demo <ArrowRight size={18}/></button><Link href="/courses" className="premium-secondary"><Play size={17}/> Explore courses</Link></div><div className="mt-10 grid max-w-xl grid-cols-3 divide-x divide-slate-200"><Metric value="25K+" label="Learners"/><Metric value="96%" label="Success"/><Metric value="4.9/5" label="Rating"/></div></div><div className="relative" aria-label="Learning outcomes overview"><div className="hero-orbit" aria-hidden="true"/><div className="relative rounded-[2.2rem] border border-white/70 bg-white/80 p-7 shadow-2xl shadow-blue-200/60 backdrop-blur"><div className="flex items-center justify-between"><span className="pill">Your progress</span><span className="text-sm font-bold text-emerald-600">+18% this week</span></div><h2 className="mt-7 text-3xl font-black">A clear path to your dream rank.</h2><div className="mt-8 space-y-4"><Progress label="Physics mastery" value="84%"/><Progress label="Daily practice" value="92%"/><Progress label="Revision plan" value="76%"/></div><div className="mt-7 grid grid-cols-2 gap-3"><Feature icon={<BookOpen/>} text="Adaptive learning"/><Feature icon={<Trophy/>} text="Real exam practice"/></div></div><div className="floating-proof"><Star className="fill-amber-400 text-amber-400" size={18}/><b>2,400+ selections</b></div></div></div></section>
    <section className="border-y border-slate-100 bg-white py-7"><div className="container-page flex flex-wrap items-center justify-center gap-x-12 gap-y-4 text-sm font-bold text-slate-500"><span>TRUSTED FOR</span>{["CBSE", "JEE MAIN & ADVANCED", "NEET", "CUET"].map(x=><span key={x} className="text-base text-slate-800">{x}</span>)}</div></section>
    <section className="container-page py-24"><Eyebrow>Popular programmes</Eyebrow><div className="mt-3 flex items-end justify-between gap-6"><h2 className="section-title">Choose the batch built for your goal.</h2><Link href="/courses" className="font-bold text-brand-700">Compare all courses →</Link></div><div className="mt-10 grid gap-6 md:grid-cols-3">{courses.map(c=><CourseCard key={c.slug} course={c}/>)}</div><div className="mt-10 overflow-hidden rounded-3xl bg-gradient-to-r from-amber-300 via-orange-300 to-rose-300 p-1"><div className="flex flex-col items-start justify-between gap-5 rounded-[1.35rem] bg-slate-950 px-7 py-7 text-white sm:flex-row sm:items-center"><div><p className="font-black text-amber-300">BRILLIANT SCHOLARSHIP TEST</p><p className="mt-1 text-xl font-bold">Earn up to 100% scholarship on tuition fees.</p></div><button onClick={()=>setOpen(true)} className="rounded-xl bg-white px-5 py-3 font-bold text-slate-950">Claim your seat</button></div></div></section>
    <section id="results" className="bg-slate-950 py-24 text-white"><div className="container-page"><Eyebrow dark>Proven outcomes</Eyebrow><h2 className="section-title mt-3 max-w-2xl">Results that begin with confidence.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{stories.map(s=><article key={s.name} className="rounded-3xl border border-slate-800 bg-slate-900 p-7"><Award className="text-amber-400"/><p className="mt-8 text-4xl font-black">{s.score}</p><p className="mt-2 text-slate-300">{s.name} · {s.exam}</p></article>)}</div></div></section>
    <section className="container-page py-24"><div className="grid gap-12 lg:grid-cols-2"><div><Eyebrow>Faculty that cares</Eyebrow><h2 className="section-title mt-3">Learn from mentors, not just screens.</h2><p className="mt-5 max-w-xl leading-7 text-slate-600">Every class combines deep subject expertise with individual feedback, doubt support and a plan you can act on.</p></div><div className="space-y-3">{faculty.map(f=><article key={f.name} className="flex items-center gap-5 rounded-2xl border border-slate-200 p-5"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-brand-700 font-black text-white">{f.initials}</div><div><h3 className="font-bold">{f.name}</h3><p className="text-sm text-slate-500">{f.role}</p></div><BadgeCheck className="ml-auto text-brand-700"/></article>)}</div></div></section>
    <section className="bg-blue-50 py-24"><div className="container-page text-center"><Eyebrow>Student voices</Eyebrow><h2 className="section-title mt-3">A better way to feel prepared.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{["The study plan made my whole year feel manageable.","Teachers notice exactly where I get stuck.","Mocks felt like the real exam—and the analytics changed my revision."].map((q,i)=><figure key={q} className="rounded-3xl bg-white p-7 text-left shadow-sm"><div className="flex gap-1 text-amber-500" role="img" aria-label="5 out of 5 stars">{[1,2,3,4,5].map(x=><Star key={x} size={16} className="fill-current"/>)}</div><blockquote className="mt-5 text-lg font-semibold leading-7">“{q}”</blockquote><figcaption className="mt-5 text-sm text-slate-500">Verified learner · Class {10+i}</figcaption></figure>)}</div></div></section>
    <section className="container-page py-24"><div className="rounded-[2.5rem] bg-brand-700 px-8 py-14 text-center text-white md:px-16"><h2 className="text-4xl font-black">Your first brilliant class is free.</h2><p className="mx-auto mt-4 max-w-xl text-blue-100">Meet a mentor, experience the platform and leave with a personal study plan.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><button onClick={()=>setOpen(true)} className="rounded-xl bg-white px-6 py-3 font-bold text-brand-700">Book free demo</button><a href={WHATSAPP_NUMBER?`https://wa.me/${WHATSAPP_NUMBER}?text=I%20want%20a%20free%20trial%20class`:"/contact"} className="inline-flex items-center gap-2 rounded-xl border border-blue-300 px-6 py-3 font-bold"><MessageCircle size={18}/> WhatsApp us</a></div></div></section>
  </main><footer className="bg-slate-950 py-10 text-center text-sm text-slate-400">© {new Date().getFullYear()} Being Brilliant Academy · Learn. Practice. Succeed.</footer>
  {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/70 p-4" role="dialog" aria-modal="true" aria-labelledby="demo-title"><div className="w-full max-w-lg rounded-3xl bg-white p-7 shadow-2xl"><button aria-label="Close" onClick={()=>setOpen(false)} className="float-right rounded-lg p-2 hover:bg-slate-100"><X/></button>{sent?<div className="py-10 text-center"><BadgeCheck className="mx-auto text-emerald-600" size={48}/><h2 id="demo-title" className="mt-4 text-2xl font-black">You’re booked!</h2><p className="mt-2 text-slate-600">A counsellor will confirm your free class shortly.</p></div>:<><h2 id="demo-title" className="text-2xl font-black">Book your free demo</h2><p className="mt-2 text-sm text-slate-500">No payment required. Takes less than a minute.</p><form action={submit} className="mt-6 grid gap-4"><label>Student name<input required name="name" minLength={2} className="form-input"/></label><label>Mobile number<input required name="mobile" inputMode="numeric" pattern="[6-9][0-9]{9}" className="form-input"/></label><label>Email (optional)<input name="email" type="email" className="form-input"/></label><div className="grid grid-cols-2 gap-3"><label>Goal<select name="targetExam" className="form-input"><option>CBSE</option><option>JEE</option><option>NEET</option><option>CUET</option><option>FOUNDATION</option></select></label><label>Preferred time<input name="demoAt" type="datetime-local" className="form-input"/></label></div><div className="grid grid-cols-2 gap-3"><label>Coupon<input name="coupon" className="form-input"/></label><label>Referral<input name="referral" className="form-input"/></label></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="emi"/> I’m interested in EMI options</label>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={busy} className="premium-cta justify-center disabled:opacity-60">{busy?"Booking…":"Confirm free class"}</button></form></>}</div></div>}</div>;
}
function Metric({value,label}:{value:string;label:string}){return <span className="px-4 first:pl-0"><b className="block text-2xl font-black">{value}</b><span className="text-xs text-slate-500">{label}</span></span>}
function Progress({label,value}:{label:string;value:string}){return <div><div className="flex justify-between text-sm font-semibold"><span>{label}</span><span>{value}</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-brand-700 to-cyan-400" style={{width:value}}/></div></div>}
function Feature({icon,text}:{icon:React.ReactNode;text:string}){return <div className="rounded-2xl bg-blue-50 p-4 text-brand-700">{icon}<b className="mt-5 block text-sm text-slate-900">{text}</b></div>}
function Eyebrow({children,dark=false}:{children:React.ReactNode;dark?:boolean}){return <p className={`text-xs font-black uppercase tracking-[.2em] ${dark?"text-cyan-300":"text-brand-700"}`}>{children}</p>}
