"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarClock, CheckCircle2, ListTodo, RefreshCw, Video } from "lucide-react";
import { AuthGate, errorMessage, getAccessToken, useAuth } from "../../components/auth-provider";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api/v1";
type Row=Record<string,any>;
async function api(path:string,init?:RequestInit){const response=await fetch(API+path,{...init,headers:{Authorization:`Bearer ${getAccessToken()??""}`,...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers}});const json=await response.json().catch(()=>null);if(!response.ok)throw new Error(json?.error?.message??"Request failed");return json}
function Content(){
 const {user}=useAuth();const [meetings,setMeetings]=useState<Row[]>([]),[actions,setActions]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const[m,a]=await Promise.all([api("/meetings"),api("/meeting-actions/my")]);setMeetings(m.data??[]);setActions(a.data??[]);setError("")}catch(e){setError(errorMessage(e))}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);const now=Date.now();const upcoming=useMemo(()=>meetings.filter(m=>["OPEN_FOR_JOIN","LIVE"].includes(m.status)||(m.status==="SCHEDULED"&&new Date(m.endsAt).getTime()>=now)),[meetings,now]);const past=useMemo(()=>meetings.filter(m=>!upcoming.includes(m)),[meetings,upcoming]);
 return <main className="min-h-screen bg-slate-50 p-4 dark:bg-slate-950 md:p-8"><div className="mx-auto max-w-6xl"><header className="rounded-3xl bg-slate-950 p-6 text-white"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-300">Staff collaboration</p><h1 className="mt-1 text-3xl font-black">My Meetings</h1><p className="mt-2 text-sm text-slate-300">{user?.name} · {user?.role.replaceAll("_"," ")}</p></div><div className="flex gap-2">{(user?.role==="SUPER_ADMIN"||user?.role==="BRANCH_ADMIN")&&<Link href="/admin/meetings" className="rounded-xl border border-white/20 px-4 py-2 text-sm font-bold">Management workspace</Link>}<button onClick={()=>void load()} className="rounded-xl border border-white/20 p-2" aria-label="Refresh"><RefreshCw size={17}/></button></div></div></header>
 {error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 <section className="mt-6 grid gap-4 sm:grid-cols-3"><Stat icon={<CalendarClock/>} label="Upcoming" value={upcoming.length}/><Stat icon={<ListTodo/>} label="Open actions" value={actions.filter(a=>!["COMPLETED","CANCELLED"].includes(a.status)).length}/><Stat icon={<CheckCircle2/>} label="Overdue actions" value={actions.filter(a=>a.overdue).length}/></section>
 <section className="mt-6"><h2 className="text-xl font-black">Upcoming</h2><div className="mt-3 grid gap-4 md:grid-cols-2">{loading?<p className="text-sm text-slate-500">Loading meetings…</p>:upcoming.length?upcoming.map(m=><Link key={m.id} href={`/meetings/${m.id}`} className="rounded-2xl border bg-white p-5 transition hover:border-brand-400 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-bold text-brand-700">{m.type.replaceAll("_"," ")}</span><h3 className="mt-1 text-lg font-black">{m.title}</h3></div><Video className="text-brand-700" size={20}/></div><p className="mt-3 text-sm">{new Date(m.startsAt).toLocaleString("en-IN")}</p><p className="mt-1 text-xs text-slate-500">{m.timezone} · {m.status.replaceAll("_"," ")} · {m.participants?.length??0} participants</p></Link>):<p className="text-sm text-slate-500">No upcoming meetings.</p>}</div></section>
 <section className="mt-7 grid gap-5 lg:grid-cols-2"><article><h2 className="text-xl font-black">My action items</h2><div className="mt-3 space-y-3">{actions.slice(0,12).map(a=><Link href={`/meetings/${a.meetingId}`} key={a.id} className="block rounded-2xl border bg-white p-4 dark:bg-slate-900"><div className="flex justify-between gap-3"><b className="text-sm">{a.title}</b><span className={`text-xs font-bold ${a.overdue?"text-red-600":"text-slate-500"}`}>{a.overdue?"OVERDUE":a.status}</span></div><p className="mt-1 text-xs text-slate-500">{a.meeting?.title}{a.dueAt?` · Due ${new Date(a.dueAt).toLocaleString("en-IN")}`:""}</p></Link>)}{!actions.length&&<p className="text-sm text-slate-500">No assigned actions.</p>}</div></article><article><h2 className="text-xl font-black">Past meetings</h2><div className="mt-3 space-y-3">{past.slice(-10).reverse().map(m=><Link href={`/meetings/${m.id}`} key={m.id} className="block rounded-2xl border bg-white p-4 dark:bg-slate-900"><b className="text-sm">{m.title}</b><p className="mt-1 text-xs text-slate-500">{new Date(m.startsAt).toLocaleString("en-IN")} · {m.status.replaceAll("_"," ")}</p></Link>)}{!past.length&&<p className="text-sm text-slate-500">No past meetings.</p>}</div></article></section>
 </div></main>
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <article className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><div className="text-brand-700">{icon}</div><p className="mt-3 text-3xl font-black">{value}</p><p className="text-sm text-slate-500">{label}</p></article>}
export default function Page(){return <AuthGate roles={["SUPER_ADMIN","BRANCH_ADMIN","ACCOUNTANT","TEACHER","EMPLOYEE"]}><Content/></AuthGate>}
