ALTER TYPE "CourseType" ADD VALUE IF NOT EXISTS 'JEE';
ALTER TYPE "CourseType" ADD VALUE IF NOT EXISTS 'SCHOOL';
ALTER TYPE "CourseType" ADD VALUE IF NOT EXISTS 'NEET';
ALTER TYPE "CourseType" ADD VALUE IF NOT EXISTS 'CUET';
ALTER TYPE "CourseType" ADD VALUE IF NOT EXISTS 'NDA';
ALTER TYPE "CourseType" ADD VALUE IF NOT EXISTS 'CA_FOUNDATION';
ALTER TYPE "CourseType" ADD VALUE IF NOT EXISTS 'SKILL';
ALTER TYPE "CourseType" ADD VALUE IF NOT EXISTS 'OTHER';
