CREATE TYPE "TimetableDay" AS ENUM ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY');
CREATE TYPE "TimetableStatus" AS ENUM ('ACTIVE','INACTIVE','ARCHIVED');
CREATE TABLE "Classroom" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"code" TEXT NOT NULL,"branchId" TEXT NOT NULL,"capacity" INTEGER NOT NULL DEFAULT 30,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Classroom_pkey" PRIMARY KEY("id"));
CREATE TABLE "Timetable" ("id" TEXT NOT NULL,"branchId" TEXT NOT NULL,"courseId" TEXT NOT NULL,"batchId" TEXT NOT NULL,"subjectId" TEXT NOT NULL,"teacherId" TEXT NOT NULL,"classroomId" TEXT NOT NULL,"day" "TimetableDay" NOT NULL,"startMinute" INTEGER NOT NULL,"endMinute" INTEGER NOT NULL,"periodNumber" INTEGER NOT NULL,"academicSession" TEXT NOT NULL,"remarks" TEXT,"status" "TimetableStatus" NOT NULL DEFAULT 'ACTIVE',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Timetable_pkey" PRIMARY KEY("id"));
INSERT INTO "Classroom" ("id","name","code","branchId","capacity") SELECT 'room-'||substr(md5("id"),1,20),'Main Classroom','MAIN',"id",40 FROM "Branch";
CREATE UNIQUE INDEX "Classroom_branchId_code_key" ON "Classroom"("branchId","code");CREATE INDEX "Classroom_branchId_isActive_idx" ON "Classroom"("branchId","isActive");
CREATE UNIQUE INDEX "Timetable_branchId_batchId_day_startMinute_endMinute_key" ON "Timetable"("branchId","batchId","day","startMinute","endMinute");CREATE INDEX "Timetable_branchId_day_idx" ON "Timetable"("branchId","day");CREATE INDEX "Timetable_courseId_idx" ON "Timetable"("courseId");CREATE INDEX "Timetable_batchId_day_idx" ON "Timetable"("batchId","day");CREATE INDEX "Timetable_teacherId_day_idx" ON "Timetable"("teacherId","day");CREATE INDEX "Timetable_classroomId_day_idx" ON "Timetable"("classroomId","day");CREATE INDEX "Timetable_status_idx" ON "Timetable"("status");
ALTER TABLE "Classroom" ADD CONSTRAINT "Classroom_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Timetable" ADD CONSTRAINT "Timetable_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "Timetable" ADD CONSTRAINT "Timetable_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "Timetable" ADD CONSTRAINT "Timetable_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "Batch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "Timetable" ADD CONSTRAINT "Timetable_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "Timetable" ADD CONSTRAINT "Timetable_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "TeacherProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "Timetable" ADD CONSTRAINT "Timetable_classroomId_fkey" FOREIGN KEY ("classroomId") REFERENCES "Classroom"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
