"use client";

import { FormEvent, useEffect, useState } from "react";
import { AuthGate, getAccessToken } from "../../../components/auth-provider";
import Sidebar from "../../../components/sidebar";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api/v1";
type Branch = { id: string; branchName: string; branchCode: string };

function Content() {
  const [branches, setBranches] = useState<Branch[]>([]), [selected, setSelected] = useState<string[]>([]), [name, setName] = useState(""), [email, setEmail] = useState(""), [phone, setPhone] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  useEffect(() => { fetch(`${API}/admin/branches?limit=100&status=active`, { headers: { Authorization: `Bearer ${getAccessToken() ?? ""}` } }).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message ?? "Unable to load branches"); setBranches(body.data ?? []); }).catch(cause => setError(cause instanceof Error ? cause.message : "Unable to load branches")); }, []);
  const toggle = (id: string) => setSelected(value => value.includes(id) ? value.filter(item => item !== id) : [...value, id]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(""); setNotice(""); try { const response = await fetch(`${API}/admin/users/accountants`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${getAccessToken() ?? ""}` }, body: JSON.stringify({ name, email, phone: phone || null, branchIds: selected }) }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message ?? "Unable to create Accountant"); setNotice(body.data?.setup?.skipped ? "Accountant created, but the setup email was not sent." : "Accountant created and the setup email was sent."); setName(""); setEmail(""); setPhone(""); setSelected([]); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to create Accountant"); } finally { setBusy(false); } };
  return <div className="min-h-screen bg-slate-50 dark:bg-slate-950"><Sidebar /><main className="p-5 md:ml-64 md:p-10"><div className="mx-auto max-w-3xl"><p className="text-sm font-bold text-brand-700">USER MANAGEMENT</p><h1 className="mt-1 text-3xl font-bold">Create Accountant</h1><p className="mt-2 text-sm text-slate-500">Assign one or more branches. An Accountant with no branches has no finance access.</p>{error && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice && <p className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}<form onSubmit={submit} className="mt-6 space-y-5 rounded-2xl border bg-white p-6 shadow-sm dark:bg-slate-900"><label className="block text-sm font-semibold">Full name<input required minLength={2} className="field mt-1" value={name} onChange={event => setName(event.target.value)} /></label><label className="block text-sm font-semibold">Email<input required type="email" className="field mt-1" value={email} onChange={event => setEmail(event.target.value)} /></label><label className="block text-sm font-semibold">Phone<input className="field mt-1" value={phone} onChange={event => setPhone(event.target.value)} /></label><fieldset><legend className="text-sm font-semibold">Assigned branches</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{branches.map(branch => <label key={branch.id} className="flex items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={selected.includes(branch.id)} onChange={() => toggle(branch.id)} />{branch.branchName} <span className="text-xs text-slate-500">({branch.branchCode})</span></label>)}{!branches.length && <p className="text-sm text-slate-500">No active branches available.</p>}</div></fieldset><button disabled={busy} className="w-full rounded-xl bg-brand-700 px-4 py-3 font-bold text-white disabled:opacity-60">{busy ? "Creating…" : "Create Accountant and send setup"}</button></form></div></main><style jsx global>{`.field{width:100%;border:1px solid #dbe1ea;border-radius:.75rem;padding:.65rem .8rem;background:transparent}`}</style></div>;
}

export default function Page() { return <AuthGate roles={["SUPER_ADMIN"]}><Content /></AuthGate>; }
