"use client";

import { useCallback, useEffect, useState } from "react";
import { Check, ChevronLeft, ChevronRight, Download, Eye, Loader2, Search, X } from "lucide-react";
import { AuthGate, getAccessToken } from "../../../components/auth-provider";
import Sidebar from "../../../components/sidebar";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api/v1";
const headers = () => ({ "Content-Type": "application/json", Authorization: `Bearer ${getAccessToken() ?? ""}` });
type Leave = { id: string; fromDate: string; toDate: string; leaveType: string; halfDaySession: string | null; reason: string; status: string; remarks: string | null; attachmentName: string | null; approvedAt: string | null; createdAt: string; user: { name: string; role: string }; branch: { id: string; branchName: string }; approvedBy: { name: string } | null };
type Branch = { id: string; branchName: string };
async function json(response: Response) { const body = await response.json().catch(() => null); if (!response.ok) throw Error(body?.error?.message ?? "Request failed"); return body; }
const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, character => character.toUpperCase());

function Content() {
  const [rows, setRows] = useState<Leave[]>([]), [branches, setBranches] = useState<Branch[]>([]), [page, setPage] = useState(1), [pages, setPages] = useState(1), [total, setTotal] = useState(0), [pendingStudents, setPendingStudents] = useState(0), [pendingTeachers, setPendingTeachers] = useState(0), [search, setSearch] = useState(""), [status, setStatus] = useState("PENDING"), [role, setRole] = useState(""), [branchId, setBranchId] = useState(""), [from, setFrom] = useState(""), [to, setTo] = useState(""), [selected, setSelected] = useState<Leave | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const params = new URLSearchParams({ page: String(page), limit: "20" }); Object.entries({ search, status, applicantRole: role, branchId, from, to }).forEach(([key, value]) => value && params.set(key, value)); const result = await fetch(`${API}/admin/leaves?${params}`, { headers: headers() }).then(json); setRows(result.data); setPages(result.meta.totalPages); setTotal(result.meta.total); setPendingStudents(result.meta.pendingStudents); setPendingTeachers(result.meta.pendingTeachers); setBranches(result.meta.branches); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load leaves"); } finally { setLoading(false); } }, [page, search, status, role, branchId, from, to]);
  useEffect(() => { void load(); }, [load]);
  async function decide(item: Leave, next: "APPROVED" | "REJECTED") { if (!window.confirm(`${next === "APPROVED" ? "Approve" : "Reject"} ${item.user.name}'s leave request?`)) return; const remarks = window.prompt(next === "APPROVED" ? "Approval remarks (optional)" : "Reason for rejection") ?? ""; if (next === "REJECTED" && remarks.trim().length < 3) return setError("A rejection reason of at least 3 characters is required"); try { await fetch(`${API}/admin/leaves/${item.id}/decision`, { method: "PATCH", headers: headers(), body: JSON.stringify({ status: next, remarks: remarks || null }) }).then(json); setSelected(null); setNotice(`Leave ${next.toLowerCase()}`); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Decision failed"); } }
  async function download(item: Leave) { const response = await fetch(`${API}/admin/leaves/${item.id}/attachment`, { headers: { Authorization: `Bearer ${getAccessToken() ?? ""}` } }); if (!response.ok) return setError("Unable to download attachment"); const url = URL.createObjectURL(await response.blob()), anchor = document.createElement("a"); anchor.href = url; anchor.download = item.attachmentName ?? "leave-attachment"; anchor.click(); URL.revokeObjectURL(url); }
  const resetPage = () => setPage(1);

  return <div className="min-h-screen bg-slate-50"><Sidebar/><main className="p-5 md:ml-64 md:p-10"><div className="mx-auto max-w-7xl"><header><p className="text-sm font-bold text-brand-700">PEOPLE</p><h1 className="text-3xl font-bold">Leave Management</h1><p className="text-slate-500">Review student and teacher leave with conflict-safe attendance synchronization.</p></header><section className="mt-6 grid gap-3 sm:grid-cols-3">{[["Pending students", pendingStudents], ["Pending teachers", pendingTeachers], ["Filtered requests", total]].map(([name, value]) => <article key={name} className="rounded-2xl border bg-white p-4"><p className="text-xs font-bold uppercase text-slate-400">{name}</p><p className="text-2xl font-bold">{value}</p></article>)}</section>{notice && <p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-emerald-700">{notice}</p>}{error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
    <section className="mt-5 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-3 lg:grid-cols-6"><label className="relative"><Search className="absolute left-3 top-3" size={16}/><input className="field pl-9" value={search} onChange={event => { setSearch(event.target.value); resetPage(); }} placeholder="Applicant or reason"/></label><select className="field" value={branchId} onChange={event => { setBranchId(event.target.value); resetPage(); }}><option value="">All branches</option>{branches.map(branch => <option key={branch.id} value={branch.id}>{branch.branchName}</option>)}</select><select className="field" value={status} onChange={event => { setStatus(event.target.value); resetPage(); }}><option value="">All statuses</option>{["PENDING", "APPROVED", "REJECTED", "CANCELLED"].map(value => <option key={value}>{value}</option>)}</select><select className="field" value={role} onChange={event => { setRole(event.target.value); resetPage(); }}><option value="">Students and teachers</option><option>STUDENT</option><option>TEACHER</option></select><input aria-label="From date" type="date" className="field" value={from} onChange={event => { setFrom(event.target.value); resetPage(); }}/><input aria-label="To date" type="date" min={from || undefined} className="field" value={to} onChange={event => { setTo(event.target.value); resetPage(); }}/></section>
    <section className="mt-5 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[1000px] text-left text-sm"><thead><tr>{["Applicant", "Branch", "Dates", "Type", "Reason", "Status", "Actions"].map(value => <th key={value} className="p-4">{value}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={7} className="p-16"><Loader2 className="mx-auto animate-spin"/></td></tr> : rows.length ? rows.map(item => <tr key={item.id} className="border-t"><td className="p-4"><b>{item.user.name}</b><br/>{label(item.user.role)}</td><td>{item.branch.branchName}</td><td>{item.fromDate.slice(0, 10)} — {item.toDate.slice(0, 10)}</td><td>{label(item.leaveType)}{item.halfDaySession && <><br/>{label(item.halfDaySession)}</>}</td><td className="max-w-xs">{item.reason}</td><td><span className="font-bold">{label(item.status)}</span>{item.approvedBy && <><br/><small>by {item.approvedBy.name}</small></>}</td><td><div className="flex gap-2"><button aria-label="View" className="icon" onClick={() => setSelected(item)}><Eye size={18}/></button>{item.status === "PENDING" && <><button aria-label="Approve" className="icon text-emerald-700" onClick={() => void decide(item, "APPROVED")}><Check/></button><button aria-label="Reject" className="icon text-red-700" onClick={() => void decide(item, "REJECTED")}><X/></button></>}</div></td></tr>) : <tr><td colSpan={7} className="p-16 text-center">No leave requests found.</td></tr>}</tbody></table><footer className="flex justify-between border-t p-4"><span>{total} requests</span><div className="flex gap-3"><button disabled={page <= 1} onClick={() => setPage(value => value - 1)}><ChevronLeft/></button>{page}/{pages}<button disabled={page >= pages} onClick={() => setPage(value => value + 1)}><ChevronRight/></button></div></footer></section>
  </div></main>{selected && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><section className="w-full max-w-xl rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">Leave request details</h2><button aria-label="Close" onClick={() => setSelected(null)}><X/></button></div><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt>Applicant</dt><dd className="font-bold">{selected.user.name} · {label(selected.user.role)}</dd></div><div><dt>Branch</dt><dd className="font-bold">{selected.branch.branchName}</dd></div><div><dt>Dates</dt><dd className="font-bold">{selected.fromDate.slice(0, 10)} — {selected.toDate.slice(0, 10)}</dd></div><div><dt>Type</dt><dd className="font-bold">{label(selected.leaveType)} {selected.halfDaySession ? `· ${label(selected.halfDaySession)}` : ""}</dd></div><div className="sm:col-span-2"><dt>Reason</dt><dd>{selected.reason}</dd></div>{selected.remarks && <div className="sm:col-span-2"><dt>Review remarks</dt><dd>{selected.remarks}</dd></div>}</dl>{selected.attachmentName && <button className="mt-5 inline-flex items-center gap-2 rounded-xl border px-4 py-2 font-bold" onClick={() => void download(selected)}><Download size={17}/>{selected.attachmentName}</button>}<div className="mt-6 flex gap-3">{selected.status === "PENDING" && <><button className="rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white" onClick={() => void decide(selected, "APPROVED")}>Approve</button><button className="rounded-xl bg-red-700 px-4 py-2 font-bold text-white" onClick={() => void decide(selected, "REJECTED")}>Reject</button></>}</div></section></div>}<style jsx global>{`.field{width:100%;border:1px solid #dbe1ea;border-radius:.75rem;padding:.65rem .8rem}.icon{border:1px solid #dbe1ea;border-radius:.5rem;padding:.4rem}`}</style></div>;
}

export default function Page() { return <AuthGate roles={["SUPER_ADMIN", "BRANCH_ADMIN"]}><Content/></AuthGate>; }
