"use client";

import Link from "next/link";
import Image from "next/image";
import { ReactNode, useEffect, useState } from "react";
import { ArrowLeft, Building2, Loader2, Mail, Phone, UserRoundCheck } from "lucide-react";
import { useParams } from "next/navigation";
import { AuthGate, getAccessToken } from "../../../../components/auth-provider";
import Sidebar from "../../../../components/sidebar";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api/v1";
type Teacher = { employeeNo: string; qualification: string | null; specialization: string | null; specializationsNormalized: Array<{ specialization: { name: string } }>; createdAt: string; user: { name: string; email: string; phone: string | null; avatarUrl: string | null; isActive: boolean }; branch: { name: string; code: string } };
function TeacherProfile() { const { id } = useParams<{ id: string }>(); const [teacher, setTeacher] = useState<Teacher | null>(null); const [error, setError] = useState(""); useEffect(() => { fetch(`${API_URL}/admin/teachers/${id}`, { headers: { Authorization: `Bearer ${getAccessToken() ?? ""}` } }).then(async response => { const json = await response.json(); if (!response.ok) throw new Error(json?.error?.message ?? "Unable to load teacher"); setTeacher(json.data); }).catch(cause => setError(cause instanceof Error ? cause.message : "Unable to load teacher")); }, [id]); return <div className="min-h-screen bg-slate-50 dark:bg-slate-950"><Sidebar /><main className="min-h-screen p-5 md:ml-64 md:p-10"><div className="mx-auto max-w-4xl"><Link href="/admin/teachers" className="inline-flex items-center gap-2 text-sm font-semibold text-brand-700"><ArrowLeft size={16} />Back to Teachers</Link>{error ? <div role="alert" className="mt-6 rounded-xl bg-red-50 p-4 text-red-700">{error}</div> : !teacher ? <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-brand-700" /></div> : <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="bg-brand-700 p-8 text-white"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="grid h-20 w-20 place-items-center overflow-hidden rounded-full bg-white/15 text-2xl font-bold">{teacher.user.avatarUrl ? <Image src={teacher.user.avatarUrl} alt="" width={80} height={80} className="h-full w-full object-cover" /> : teacher.user.name.split(" ").map(part => part[0]).slice(0, 2).join("")}</div><div><p className="text-sm font-semibold text-white/70">{teacher.employeeNo}</p><h1 className="mt-1 text-3xl font-bold">{teacher.user.name}</h1><p className="mt-1">{teacher.specializationsNormalized.map(row => row.specialization.name).join(", ") || teacher.specialization || "Faculty member"}</p></div><span className={`sm:ml-auto rounded-full px-3 py-1 text-sm font-bold ${teacher.user.isActive ? "bg-emerald-400/20 text-emerald-50" : "bg-white/15"}`}>{teacher.user.isActive ? "Active" : "Inactive"}</span></div></div><div className="grid gap-6 p-6 sm:grid-cols-2"><Detail icon={<Mail size={18} />} label="Email" value={teacher.user.email} /><Detail icon={<Phone size={18} />} label="Mobile" value={teacher.user.phone ?? "Not provided"} /><Detail icon={<UserRoundCheck size={18} />} label="Qualification" value={teacher.qualification ?? "Not provided"} /><Detail icon={<Building2 size={18} />} label="Branch" value={`${teacher.branch.name} (${teacher.branch.code})`} /></div></section>}</div></main></div>; }
function Detail({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="flex gap-3 rounded-xl bg-slate-50 p-4 dark:bg-slate-950"><span className="text-brand-700">{icon}</span><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 font-medium">{value}</p></div></div>; }
export default function TeacherProfilePage() { return <AuthGate roles={["SUPER_ADMIN", "BRANCH_ADMIN"]}><TeacherProfile /></AuthGate>; }
