-- PostgreSQL requires newly added enum values to be committed before a later
-- migration may reference them in constraints or data.
ALTER TYPE "ClassLevel" ADD VALUE IF NOT EXISTS 'PLAY' BEFORE 'CLASS_6';
ALTER TYPE "ClassLevel" ADD VALUE IF NOT EXISTS 'NURSERY' BEFORE 'CLASS_6';
ALTER TYPE "ClassLevel" ADD VALUE IF NOT EXISTS 'LKG' BEFORE 'CLASS_6';
ALTER TYPE "ClassLevel" ADD VALUE IF NOT EXISTS 'UKG' BEFORE 'CLASS_6';
ALTER TYPE "ClassLevel" ADD VALUE IF NOT EXISTS 'CLASS_1' BEFORE 'CLASS_6';
ALTER TYPE "ClassLevel" ADD VALUE IF NOT EXISTS 'CLASS_2' BEFORE 'CLASS_6';
ALTER TYPE "ClassLevel" ADD VALUE IF NOT EXISTS 'CLASS_3' BEFORE 'CLASS_6';
ALTER TYPE "ClassLevel" ADD VALUE IF NOT EXISTS 'CLASS_4' BEFORE 'CLASS_6';
ALTER TYPE "ClassLevel" ADD VALUE IF NOT EXISTS 'CLASS_5' BEFORE 'CLASS_6';
